x86_64-bndldx32_EXTRICATE_ARGS := cpu_ldl_le_data_ra
x86_64-bndldx64_EXTRICATE_ARGS := cpu_ldq_le_data_ra
x86_64-bndstx32_EXTRICATE_ARGS := cpu_ldl_le_data_ra cpu_stl_le_data_ra
x86_64-bndstx64_EXTRICATE_ARGS := cpu_ldq_le_data_ra cpu_stq_le_data_ra
x86_64-lsl_EXTRICATE_ARGS := cpu_ldl_le_mmuidx_ra cpu_cc_compute_all
x86_64-lar_EXTRICATE_ARGS := cpu_ldl_le_mmuidx_ra cpu_cc_compute_all
x86_64-verr_EXTRICATE_ARGS := cpu_ldl_le_mmuidx_ra cpu_cc_compute_all
x86_64-verw_EXTRICATE_ARGS := cpu_ldl_le_mmuidx_ra cpu_cc_compute_all
x86_64-boundw_EXTRICATE_ARGS := cpu_ldsw_le_data_ra
x86_64-boundl_EXTRICATE_ARGS := cpu_ldl_le_data_ra
x86_64-fldt_ST0_EXTRICATE_ARGS := cpu_lduw_le_data_ra cpu_ldq_le_data_ra
x86_64-fstt_ST0_EXTRICATE_ARGS := cpu_stw_le_data_ra cpu_stq_le_data_ra
x86_64-fbld_ST0_EXTRICATE_ARGS := cpu_ldub_data_ra
x86_64-fbst_ST0_EXTRICATE_ARGS := cpu_stb_data_ra
x86_64-fstenv_EXTRICATE_ARGS := cpu_stw_le_data_ra cpu_stl_le_data_ra
x86_64-fldenv_EXTRICATE_ARGS := cpu_lduw_le_data_ra
x86_64-fsave_EXTRICATE_ARGS := cpu_stq_le_data_ra cpu_stw_le_data_ra cpu_stl_le_data_ra
x86_64-frstor_EXTRICATE_ARGS := cpu_ldq_le_data_ra cpu_lduw_le_data_ra
x86_64-fxsave_EXTRICATE_ARGS := cpu_stl_le_data_ra cpu_stq_le_data_ra cpu_stw_le_data_ra
x86_64-fxrstor_EXTRICATE_ARGS := cpu_ldl_le_data_ra cpu_ldq_le_data_ra cpu_lduw_le_data_ra
x86_64-xsave_EXTRICATE_ARGS := cpu_stw_le_data_ra cpu_stq_le_data_ra cpu_stl_le_data_ra cpu_ldq_le_data_ra
x86_64-xsaveopt_EXTRICATE_ARGS := cpu_stw_le_data_ra cpu_stq_le_data_ra cpu_stl_le_data_ra cpu_ldq_le_data_ra
x86_64-xrstor_EXTRICATE_ARGS := cpu_ldl_le_data_ra cpu_lduw_le_data_ra cpu_sync_bndcs_hflags cpu_ldq_le_data_ra
x86_64-maskmov_mmx_EXTRICATE_ARGS := cpu_stb_data_ra
x86_64-maskmov_xmm_EXTRICATE_ARGS := cpu_stb_data_ra
x86_64-vpmaskmovd_st_xmm_EXTRICATE_ARGS := cpu_stl_le_data_ra
x86_64-vpmaskmovq_st_xmm_EXTRICATE_ARGS := cpu_stq_le_data_ra
x86_64-vpgatherdd_xmm_EXTRICATE_ARGS := cpu_ldl_le_data_ra
x86_64-vpgatherdq_xmm_EXTRICATE_ARGS := cpu_ldq_le_data_ra
x86_64-vpgatherqd_xmm_EXTRICATE_ARGS := cpu_ldl_le_data_ra
x86_64-vpgatherqq_xmm_EXTRICATE_ARGS := cpu_ldq_le_data_ra
x86_64-vpmaskmovd_st_ymm_EXTRICATE_ARGS := cpu_stl_le_data_ra
x86_64-vpmaskmovq_st_ymm_EXTRICATE_ARGS := cpu_stq_le_data_ra
x86_64-vpgatherdd_ymm_EXTRICATE_ARGS := cpu_ldl_le_data_ra
x86_64-vpgatherdq_ymm_EXTRICATE_ARGS := cpu_ldq_le_data_ra
x86_64-vpgatherqd_ymm_EXTRICATE_ARGS := cpu_ldl_le_data_ra
x86_64-vpgatherqq_ymm_EXTRICATE_ARGS := cpu_ldq_le_data_ra
x86_64-aaa_EXTRICATE_ARGS := cpu_cc_compute_all
x86_64-aas_EXTRICATE_ARGS := cpu_cc_compute_all
x86_64-daa_EXTRICATE_ARGS := cpu_cc_compute_all
x86_64-das_EXTRICATE_ARGS := cpu_cc_compute_all
x86_64-into_EXTRICATE_ARGS := cpu_cc_compute_all
x86_64-fcomi_ST0_FT0_EXTRICATE_ARGS := cpu_cc_compute_all
x86_64-fucomi_ST0_FT0_EXTRICATE_ARGS := cpu_cc_compute_all
x86_64-write_eflags_EXTRICATE_ARGS := cpu_load_eflags
x86_64-aesdeclast_xmm_EXTRICATE_ARGS := AES_ishifts
x86_64-aesenc_xmm_EXTRICATE_ARGS := AES_shifts
x86_64-aeskeygenassist_xmm_EXTRICATE_ARGS := AES_sbox
x86_64-aesdec_xmm_EXTRICATE_ARGS := AES_ishifts
x86_64-aesenclast_xmm_EXTRICATE_ARGS := AES_shifts
x86_64-aesimc_xmm_EXTRICATE_ARGS := AES_imc
x86_64-aesdec_ymm_EXTRICATE_ARGS := AES_ishifts
x86_64-aesdeclast_ymm_EXTRICATE_ARGS := AES_ishifts
x86_64-aesenc_ymm_EXTRICATE_ARGS := AES_shifts
x86_64-aesenclast_ymm_EXTRICATE_ARGS := AES_shifts
