#pragma once
#include <bitset>
#include <array>
#include <cstdint>

/* NOTE: THIS FILE IS AUTO-GENERATED BY GEN-TCGCONSTANTS */
namespace jove {

//
// I64 _frame
// I64 env
// I32 cc_op
// I64 cc_dst
// I64 cc_src
// I64 cc_src2
// I64 rax
// I64 rcx
// I64 rdx
// I64 rbx
// I64 rsp
// I64 rbp
// I64 rsi
// I64 rdi
// I64 r8
// I64 r9
// I64 r10
// I64 r11
// I64 r12
// I64 r13
// I64 r14
// I64 r15
// I64 es_base
// I64 cs_base
// I64 ss_base
// I64 ds_base
// I64 fs_base
// I64 gs_base
// I64 bnd0_lb
// I64 bnd0_ub
// I64 bnd1_lb
// I64 bnd1_ub
// I64 bnd2_lb
// I64 bnd2_ub
// I64 bnd3_lb
// I64 bnd3_ub
//

typedef uint64_t tcg_uintptr_t;
constexpr int tcg_num_globals = 36;
constexpr int tcg_num_helpers = 821;
constexpr int tcg_max_temps = 512;
constexpr int tcg_env_index = 1;
constexpr int tcg_program_counter_index = -1;
constexpr int tcg_frame_pointer_index = 11;
constexpr int tcg_stack_pointer_index = 10;
constexpr int tcg_program_counter_env_offset = 128;
constexpr int tcg_syscall_number_index = 6;
constexpr int tcg_syscall_return_index = 6;
constexpr int tcg_syscall_arg1_index = 13;
constexpr int tcg_syscall_arg2_index = 12;
constexpr int tcg_syscall_arg3_index = 8;
constexpr int tcg_syscall_arg4_index = 16;
constexpr int tcg_syscall_arg5_index = 14;
constexpr int tcg_syscall_arg6_index = 15;
constexpr int tcg_fs_base_index = 26;
constexpr int tcg_r12_index = 18;
constexpr int tcg_r13_index = 19;
constexpr int tcg_r14_index = 20;
constexpr int tcg_r15_index = 21;
typedef std::bitset<tcg_num_globals> tcg_global_set_t;
constexpr tcg_global_set_t NotArgs(68715282495);
constexpr tcg_global_set_t NotRets(68715282495);
constexpr tcg_global_set_t CallConvArgs(61824);
typedef std::array<unsigned, 6> CallConvArgArrayTy;
static const CallConvArgArrayTy CallConvArgArray{13, 12, 8, 7, 14, 15};
constexpr tcg_global_set_t CallConvRets(320);
typedef std::array<unsigned, 2> CallConvRetArrayTy;
static const CallConvRetArrayTy CallConvRetArray{6, 8};
constexpr tcg_global_set_t CalleeSavedRegs(3934720);
static const uint8_t tcg_global_by_offset_lookup_table[529] = {
[0 ... 528] = 0xff,
[168] = 2,
[144] = 3,
[152] = 4,
[160] = 5,
[0] = 6,
[8] = 7,
[16] = 8,
[24] = 9,
[32] = 10,
[40] = 11,
[48] = 12,
[56] = 13,
[64] = 14,
[72] = 15,
[80] = 16,
[88] = 17,
[96] = 18,
[104] = 19,
[112] = 20,
[120] = 21,
[192] = 22,
[216] = 23,
[240] = 24,
[264] = 25,
[288] = 26,
[312] = 27,
[472] = 28,
[480] = 29,
[488] = 30,
[496] = 31,
[504] = 32,
[512] = 33,
[520] = 34,
[528] = 35,
};
constexpr tcg_global_set_t PinnedEnvGlbs(0);
}
