i386-aaa_EXTRICATE_ARGS := cpu_cc_compute_all
i386-aas_EXTRICATE_ARGS := cpu_cc_compute_all
i386-aesdec_xmm_EXTRICATE_ARGS := aesdec_ISB_ISR_IMC_AK_gen
i386-aesdec_ymm_EXTRICATE_ARGS := aesdec_ISB_ISR_IMC_AK_gen
i386-aesdeclast_xmm_EXTRICATE_ARGS := aesdec_ISB_ISR_AK_gen
i386-aesdeclast_ymm_EXTRICATE_ARGS := aesdec_ISB_ISR_AK_gen
i386-aesenc_xmm_EXTRICATE_ARGS := aesenc_SB_SR_MC_AK_gen
i386-aesenc_ymm_EXTRICATE_ARGS := aesenc_SB_SR_MC_AK_gen
i386-aesenclast_xmm_EXTRICATE_ARGS := aesenc_SB_SR_AK_gen
i386-aesenclast_ymm_EXTRICATE_ARGS := aesenc_SB_SR_AK_gen
i386-aesimc_xmm_EXTRICATE_ARGS := aesdec_IMC_gen
i386-bndldx32_EXTRICATE_ARGS := cpu_ldl_le_data_ra
i386-bndldx64_EXTRICATE_ARGS := cpu_ldq_le_data_ra
i386-bndstx32_EXTRICATE_ARGS := cpu_ldl_le_data_ra cpu_stl_le_data_ra
i386-bndstx64_EXTRICATE_ARGS := cpu_ldq_le_data_ra cpu_stq_le_data_ra
i386-boundl_EXTRICATE_ARGS := cpu_ldl_le_data_ra
i386-boundw_EXTRICATE_ARGS := cpu_ldsw_le_data_ra
i386-daa_EXTRICATE_ARGS := cpu_cc_compute_all
i386-das_EXTRICATE_ARGS := cpu_cc_compute_all
i386-fbld_ST0_EXTRICATE_ARGS := cpu_ldub_data_ra
i386-fbst_ST0_EXTRICATE_ARGS := cpu_stb_data_ra
i386-fcomi_ST0_FT0_EXTRICATE_ARGS := cpu_cc_compute_all
i386-fldenv_EXTRICATE_ARGS := cpu_lduw_le_data_ra
i386-fldt_ST0_EXTRICATE_ARGS := cpu_lduw_le_data_ra cpu_ldq_le_data_ra
i386-frstor_EXTRICATE_ARGS := cpu_ldq_le_data_ra cpu_lduw_le_data_ra
i386-fsave_EXTRICATE_ARGS := cpu_stq_le_data_ra cpu_stw_le_data_ra cpu_stl_le_data_ra
i386-fstenv_EXTRICATE_ARGS := cpu_stw_le_data_ra cpu_stl_le_data_ra
i386-fstt_ST0_EXTRICATE_ARGS := cpu_stw_le_data_ra cpu_stq_le_data_ra
i386-fucomi_ST0_FT0_EXTRICATE_ARGS := cpu_cc_compute_all
i386-fxrstor_EXTRICATE_ARGS := cpu_ldl_le_data_ra cpu_ldq_le_data_ra cpu_lduw_le_data_ra
i386-fxsave_EXTRICATE_ARGS := cpu_stl_le_data_ra cpu_stq_le_data_ra cpu_stw_le_data_ra
i386-into_EXTRICATE_ARGS := cpu_cc_compute_all
i386-lar_EXTRICATE_ARGS := cpu_mmu_index_kernel cpu_ldl_le_mmuidx_ra cpu_cc_compute_all
i386-lsl_EXTRICATE_ARGS := cpu_mmu_index_kernel cpu_ldl_le_mmuidx_ra cpu_cc_compute_all
i386-maskmov_mmx_EXTRICATE_ARGS := cpu_stb_data_ra
i386-maskmov_xmm_EXTRICATE_ARGS := cpu_stb_data_ra
i386-mulsh_i64_EXTRICATE_ARGS := muls64
i386-muluh_i64_EXTRICATE_ARGS := mulu64
i386-pclmulqdq_xmm_EXTRICATE_ARGS := clmul_64_gen
i386-pclmulqdq_ymm_EXTRICATE_ARGS := clmul_64_gen
i386-verr_EXTRICATE_ARGS := cpu_mmu_index_kernel cpu_ldl_le_mmuidx_ra cpu_cc_compute_all
i386-verw_EXTRICATE_ARGS := cpu_mmu_index_kernel cpu_ldl_le_mmuidx_ra cpu_cc_compute_all
i386-vpgatherdd_xmm_EXTRICATE_ARGS := cpu_ldl_le_data_ra
i386-vpgatherdd_ymm_EXTRICATE_ARGS := cpu_ldl_le_data_ra
i386-vpgatherdq_xmm_EXTRICATE_ARGS := cpu_ldq_le_data_ra
i386-vpgatherdq_ymm_EXTRICATE_ARGS := cpu_ldq_le_data_ra
i386-vpgatherqd_xmm_EXTRICATE_ARGS := cpu_ldl_le_data_ra
i386-vpgatherqd_ymm_EXTRICATE_ARGS := cpu_ldl_le_data_ra
i386-vpgatherqq_xmm_EXTRICATE_ARGS := cpu_ldq_le_data_ra
i386-vpgatherqq_ymm_EXTRICATE_ARGS := cpu_ldq_le_data_ra
i386-vpmaskmovd_st_xmm_EXTRICATE_ARGS := cpu_stl_le_data_ra
i386-vpmaskmovd_st_ymm_EXTRICATE_ARGS := cpu_stl_le_data_ra
i386-vpmaskmovq_st_xmm_EXTRICATE_ARGS := cpu_stq_le_data_ra
i386-vpmaskmovq_st_ymm_EXTRICATE_ARGS := cpu_stq_le_data_ra
i386-write_eflags_EXTRICATE_ARGS := cpu_load_eflags
i386-xrstor_EXTRICATE_ARGS := cpu_ldl_le_data_ra cpu_lduw_le_data_ra cpu_sync_bndcs_hflags cpu_ldq_le_data_ra
i386-xsave_EXTRICATE_ARGS := cpu_stl_le_data_ra cpu_stw_le_data_ra cpu_stq_le_data_ra cpu_ldq_le_data_ra
i386-xsave_EXTRICATE_ARGS := xsave_area_size
i386-xsaveopt_EXTRICATE_ARGS := cpu_stl_le_data_ra cpu_stw_le_data_ra cpu_stq_le_data_ra cpu_ldq_le_data_ra
i386-xsaveopt_EXTRICATE_ARGS := xsave_area_size
i386-xsetbv_EXTRICATE_ARGS := cpu_sync_avx_hflag cpu_sync_bndcs_hflags cpu_x86_cpuid
