#include "syscalls.inc.macros_begin.h"

#if !defined(___DFSAN) || defined(___DFSAN_SYSENTRS)
___SYSCALL1(252, exit_group, int, error_code)
___SYSCALL1(1, exit, int, error_code)
#endif

#if !defined(___DFSAN) || defined(___DFSAN_SYSEXITS)
___SYSCALL3(4, write, unsigned int, fd, const char __user *, buf, size_t, count)
___SYSCALL3(3, read, unsigned int, fd, char __user *, buf, size_t, count)
___SYSCALL2(102, socketcall, int, call, unsigned long __user *, args)
___SYSCALL6(369, sendto, int, fd, void __user *, buff, size_t, len, unsigned int, flags, struct sockaddr __user *, addr, int, addr_len)
___SYSCALL6(371, recvfrom, int, fd, void __user *, ubuf, size_t, size, unsigned int, flags, struct sockaddr __user *, addr, int __user *, addr_len)
___SYSCALL3(372, recvmsg, int, fd, struct msghdr __user *, msg, unsigned int, flags)
___SYSCALL6(192, mmap_pgoff, unsigned long, addr, unsigned long, len, unsigned long, prot, unsigned long, flags, unsigned long, fd, unsigned long, pgoff)
___SYSCALL2(108, newfstat, unsigned int, fd, struct stat __user *, statbuf)
___SYSCALL3(54, ioctl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL2(106, newstat, const char __user *, filename, struct stat __user *, statbuf)
___SYSCALL2(107, newlstat, const char __user *, filename, struct stat __user *, statbuf)
___SYSCALL2(183, getcwd, char __user *, buf, unsigned long, size)
___SYSCALL4(364, accept4, int, fd, struct sockaddr __user *, upeer_sockaddr, int __user *, upeer_addrlen, int, flags)
___SYSCALL3(359, socket, int, family, int, type, int, protocol)
___SYSCALL1(6, close, unsigned int, fd)
___SYSCALL0(2, fork)
___SYSCALL2(77, getrusage, int, who, struct rusage __user *, ru)
___SYSCALL2(191, getrlimit, unsigned int, resource, struct rlimit __user *, rlim)
___SYSCALL4(360, socketpair, int, family, int, type, int, protocol, int __user *, usockvec)
___SYSCALL3(141, getdents, unsigned int, fd, struct linux_dirent __user *, dirent, unsigned int, count)
___SYSCALL3(220, getdents64, unsigned int, fd, struct linux_dirent64 __user *, dirent, unsigned int, count)
#endif

#if !defined(___DFSAN)
___SYSCALL0(0, restart_syscall)
___SYSCALL3(5, open, const char __user *, filename, int, flags, mode_t, mode)
___SYSCALL3(7, waitpid, pid_t, pid, int __user *, stat_addr, int, options)
___SYSCALL2(8, creat, const char __user *, pathname, mode_t, mode)
___SYSCALL2(9, link, const char __user *, oldname, const char __user *, newname)
___SYSCALL1(10, unlink, const char __user *, pathname)
___SYSCALL3(11, execve, const char __user *, filename, const char __user *const __user *, argv, const char __user *const __user *, envp)
___SYSCALL1(12, chdir, const char __user *, filename)
___SYSCALL1(13, time32, old_time32_t __user *, tloc)
___SYSCALL3(14, mknod, const char __user *, filename, mode_t, mode, unsigned, dev)
___SYSCALL2(15, chmod, const char __user *, filename, mode_t, mode)
___SYSCALL3(16, lchown16, const char __user *, filename, old_uid_t, user, old_gid_t, group)
___SYSCALL2(18, stat, const char __user *, filename, struct __old_kernel_stat __user *, statbuf)
___SYSCALL3(19, lseek, unsigned int, fd, off_t, offset, unsigned int, whence)
___SYSCALL0(20, getpid)
___SYSCALL5(21, mount, char __user *, dev_name, char __user *, dir_name, char __user *, type, unsigned long, flags, void __user *, data)
___SYSCALL1(22, oldumount, char __user *, name)
___SYSCALL1(23, setuid16, old_uid_t, uid)
___SYSCALL0(24, getuid16)
___SYSCALL1(25, stime32, old_time32_t __user *, tptr)
___SYSCALL4(26, ptrace, long, request, long, pid, unsigned long, addr, unsigned long, data)
___SYSCALL1(27, alarm, unsigned int, seconds)
___SYSCALL2(28, fstat, unsigned int, fd, struct __old_kernel_stat __user *, statbuf)
___SYSCALL0(29, pause)
___SYSCALL2(30, utime32, const char __user *, filename, struct old_utimbuf32 __user *, t)
___SYSCALL2(33, access, const char __user *, filename, int, mode)
___SYSCALL1(34, nice, int, increment)
___SYSCALL0(36, sync)
___SYSCALL2(37, kill, pid_t, pid, int, sig)
___SYSCALL2(38, rename, const char __user *, oldname, const char __user *, newname)
___SYSCALL2(39, mkdir, const char __user *, pathname, mode_t, mode)
___SYSCALL1(40, rmdir, const char __user *, pathname)
___SYSCALL1(41, dup, unsigned int, fildes)
___SYSCALL1(42, pipe, int __user *, fildes)
___SYSCALL1(43, times, struct tms __user *, tbuf)
___SYSCALL1(45, brk, unsigned long, brk)
___SYSCALL1(46, setgid16, old_gid_t, gid)
___SYSCALL0(47, getgid16)
___SYSCALL2(48, signal, int, sig, __sighandler_t, handler)
___SYSCALL0(49, geteuid16)
___SYSCALL0(50, getegid16)
___SYSCALL1(51, acct, const char __user *, name)
___SYSCALL2(52, umount, char __user *, name, int, flags)
___SYSCALL3(55, fcntl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL2(57, setpgid, pid_t, pid, pid_t, pgid)
___SYSCALL1(59, olduname, struct oldold_utsname __user *, name)
___SYSCALL1(60, umask, int, mask)
___SYSCALL1(61, chroot, const char __user *, filename)
___SYSCALL2(62, ustat, unsigned, dev, struct ustat __user *, ubuf)
___SYSCALL2(63, dup2, unsigned int, oldfd, unsigned int, newfd)
___SYSCALL0(64, getppid)
___SYSCALL0(65, getpgrp)
___SYSCALL0(66, setsid)
___SYSCALL3(67, sigaction, int, sig, const struct old_sigaction __user *, act, struct old_sigaction __user *, oact)
___SYSCALL0(68, sgetmask)
___SYSCALL1(69, ssetmask, int, newmask)
___SYSCALL2(70, setreuid16, old_uid_t, ruid, old_uid_t, euid)
___SYSCALL2(71, setregid16, old_gid_t, rgid, old_gid_t, egid)
___SYSCALL3(72, sigsuspend, int, unused1, int, unused2, old_sigset_t, mask)
___SYSCALL1(73, sigpending, old_sigset_t __user *, uset)
___SYSCALL2(74, sethostname, char __user *, name, int, len)
___SYSCALL2(75, setrlimit, unsigned int, resource, struct rlimit __user *, rlim)
___SYSCALL2(76, old_getrlimit, unsigned int, resource, struct rlimit __user *, rlim)
___SYSCALL2(78, gettimeofday, struct timeval __user *, tv, struct timezone __user *, tz)
___SYSCALL2(79, settimeofday, struct timeval __user *, tv, struct timezone __user *, tz)
___SYSCALL2(80, getgroups16, int, gidsetsize, old_gid_t __user *, grouplist)
___SYSCALL2(81, setgroups16, int, gidsetsize, old_gid_t __user *, grouplist)
___SYSCALL1(82, old_select, struct sel_arg_struct __user *, arg)
___SYSCALL2(83, symlink, const char __user *, oldname, const char __user *, newname)
___SYSCALL2(84, lstat, const char __user *, filename, struct __old_kernel_stat __user *, statbuf)
___SYSCALL3(85, readlink, const char __user *, path, char __user *, buf, int, bufsiz)
___SYSCALL1(86, uselib, const char __user *, library)
___SYSCALL2(87, swapon, const char __user *, specialfile, int, swap_flags)
___SYSCALL4(88, reboot, int, magic1, int, magic2, unsigned int, cmd, void __user *, arg)
___SYSCALL3(89, old_readdir, unsigned int, fd, struct old_linux_dirent __user *, dirent, unsigned int, count)
___SYSCALL1(90, old_mmap, struct mmap_arg_struct __user *, arg)
___SYSCALL2(91, munmap, unsigned long, addr, size_t, len)
___SYSCALL2(92, truncate, const char __user *, path, long, length)
___SYSCALL2(93, ftruncate, unsigned int, fd, unsigned long, length)
___SYSCALL2(94, fchmod, unsigned int, fd, mode_t, mode)
___SYSCALL3(95, fchown16, unsigned int, fd, old_uid_t, user, old_gid_t, group)
___SYSCALL2(96, getpriority, int, which, int, who)
___SYSCALL3(97, setpriority, int, which, int, who, int, niceval)
___SYSCALL2(99, statfs, const char __user *, pathname, struct statfs __user *, buf)
___SYSCALL2(100, fstatfs, unsigned int, fd, struct statfs __user *, buf)
___SYSCALL3(101, ioperm, unsigned long, from, unsigned long, num, int, turn_on)
___SYSCALL3(103, syslog, int, type, char __user *, buf, int, len)
___SYSCALL3(104, setitimer, int, which, struct itimerval __user *, value, struct itimerval __user *, ovalue)
___SYSCALL2(105, getitimer, int, which, struct itimerval __user *, value)
___SYSCALL1(109, uname, struct old_utsname __user *, name)
___SYSCALL1(110, iopl, unsigned int, level)
___SYSCALL0(111, vhangup)
___SYSCALL1(113, vm86old, struct vm86_struct __user *, user_vm86)
___SYSCALL4(114, wait4, pid_t, upid, int __user *, stat_addr, int, options, struct rusage __user *, ru)
___SYSCALL1(115, swapoff, const char __user *, specialfile)
___SYSCALL1(116, sysinfo, struct sysinfo __user *, info)
___SYSCALL6(117, ipc, unsigned int, call, int, first, unsigned long, second, unsigned long, third, void __user *, ptr, long, fifth)
___SYSCALL1(118, fsync, unsigned int, fd)
___SYSCALL0(119, sigreturn)
___SYSCALL5(120, clone, unsigned long, clone_flags, unsigned long, newsp, int __user *, parent_tidptr, int __user *, child_tidptr, unsigned long, tls)
___SYSCALL2(121, setdomainname, char __user *, name, int, len)
___SYSCALL1(122, newuname, struct new_utsname __user *, name)
___SYSCALL3(123, modify_ldt, int, func, void __user *, ptr, unsigned long, bytecount)
___SYSCALL1(124, adjtimex_time32, struct old_timex32 __user *, utp)
___SYSCALL3(125, mprotect, unsigned long, start, size_t, len, unsigned long, prot)
___SYSCALL3(126, sigprocmask, int, how, old_sigset_t __user *, nset, old_sigset_t __user *, oset)
___SYSCALL3(128, init_module, void __user *, umod, unsigned long, len, const char __user *, uargs)
___SYSCALL2(129, delete_module, const char __user *, name_user, unsigned int, flags)
___SYSCALL4(131, quotactl, unsigned int, cmd, const char __user *, special, int, id, void __user *, addr)
___SYSCALL1(132, getpgid, pid_t, pid)
___SYSCALL1(133, fchdir, unsigned int, fd)
___SYSCALL2(134, bdflush, int, func, long, data)
___SYSCALL3(135, sysfs, int, option, unsigned long, arg1, unsigned long, arg2)
___SYSCALL1(136, personality, unsigned int, personality)
___SYSCALL1(138, setfsuid16, old_uid_t, uid)
___SYSCALL1(139, setfsgid16, old_gid_t, gid)
___SYSCALL5(140, llseek, unsigned int, fd, unsigned long, offset_high, unsigned long, offset_low, loff_t __user *, result, unsigned int, whence)
___SYSCALL5(142, select, int, n, fd_set __user *, inp, fd_set __user *, outp, fd_set __user *, exp, struct timeval __user *, tvp)
___SYSCALL2(143, flock, unsigned int, fd, unsigned int, cmd)
___SYSCALL3(144, msync, unsigned long, start, size_t, len, int, flags)
___SYSCALL3(145, readv, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen)
___SYSCALL3(146, writev, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen)
___SYSCALL1(147, getsid, pid_t, pid)
___SYSCALL1(148, fdatasync, unsigned int, fd)
___SYSCALL1(149, sysctl, struct __sysctl_args __user *, args)
___SYSCALL2(150, mlock, unsigned long, start, size_t, len)
___SYSCALL2(151, munlock, unsigned long, start, size_t, len)
___SYSCALL1(152, mlockall, int, flags)
___SYSCALL0(153, munlockall)
___SYSCALL2(154, sched_setparam, pid_t, pid, struct sched_param __user *, param)
___SYSCALL2(155, sched_getparam, pid_t, pid, struct sched_param __user *, param)
___SYSCALL3(156, sched_setscheduler, pid_t, pid, int, policy, struct sched_param __user *, param)
___SYSCALL1(157, sched_getscheduler, pid_t, pid)
___SYSCALL0(158, sched_yield)
___SYSCALL1(159, sched_get_priority_max, int, policy)
___SYSCALL1(160, sched_get_priority_min, int, policy)
___SYSCALL2(161, sched_rr_get_interval_time32, pid_t, pid, struct old_timespec32 __user *, interval)
___SYSCALL2(162, nanosleep_time32, struct old_timespec32 __user *, rqtp, struct old_timespec32 __user *, rmtp)
___SYSCALL5(163, mremap, unsigned long, addr, unsigned long, old_len, unsigned long, new_len, unsigned long, flags, unsigned long, new_addr)
___SYSCALL3(164, setresuid16, old_uid_t, ruid, old_uid_t, euid, old_uid_t, suid)
___SYSCALL3(165, getresuid16, old_uid_t __user *, ruidp, old_uid_t __user *, euidp, old_uid_t __user *, suidp)
___SYSCALL2(166, vm86, unsigned long, cmd, unsigned long, arg)
___SYSCALL3(168, poll, struct pollfd __user *, ufds, unsigned int, nfds, int, timeout_msecs)
___SYSCALL3(170, setresgid16, old_gid_t, rgid, old_gid_t, egid, old_gid_t, sgid)
___SYSCALL3(171, getresgid16, old_gid_t __user *, rgidp, old_gid_t __user *, egidp, old_gid_t __user *, sgidp)
___SYSCALL5(172, prctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
___SYSCALL0(173, rt_sigreturn)
___SYSCALL4(174, rt_sigaction, int, sig, const struct sigaction __user *, act, struct sigaction __user *, oact, size_t, sigsetsize)
___SYSCALL4(175, rt_sigprocmask, int, how, sigset_t __user *, nset, sigset_t __user *, oset, size_t, sigsetsize)
___SYSCALL2(176, rt_sigpending, sigset_t __user *, uset, size_t, sigsetsize)
___SYSCALL4(177, rt_sigtimedwait_time32, const sigset_t __user *, uthese, siginfo_t __user *, uinfo, const struct old_timespec32 __user *, uts, size_t, sigsetsize)
___SYSCALL3(178, rt_sigqueueinfo, pid_t, pid, int, sig, siginfo_t __user *, uinfo)
___SYSCALL2(179, rt_sigsuspend, sigset_t __user *, unewset, size_t, sigsetsize)
___SYSCALL5(180, pread64, unsigned int, fd, char __user *, buf, size_t, count, uint32_t, pos_l, uint32_t, pos_h)
___SYSCALL5(181, pwrite64, unsigned int, fd, const char __user *, buf, size_t, count, uint32_t, pos_l, uint32_t, pos_h)
___SYSCALL3(182, chown16, const char __user *, filename, old_uid_t, user, old_gid_t, group)
___SYSCALL2(184, capget, cap_user_header_t, header, cap_user_data_t, dataptr)
___SYSCALL2(185, capset, cap_user_header_t, header, const cap_user_data_t, data)
___SYSCALL2(186, sigaltstack, const stack_t __user *, uss, stack_t __user *, uoss)
___SYSCALL4(187, sendfile, int, out_fd, int, in_fd, off_t __user *, offset, size_t, count)
___SYSCALL0(190, vfork)
___SYSCALL3(193, truncate64, const char __user *, path, uint32_t, length_l, uint32_t, length_h)
___SYSCALL3(194, ftruncate64, unsigned int, fd, uint32_t, length_l, uint32_t, length_h)
___SYSCALL2(195, stat64, const char __user *, filename, struct stat64 __user *, statbuf)
___SYSCALL2(196, lstat64, const char __user *, filename, struct stat64 __user *, statbuf)
___SYSCALL2(197, fstat64, unsigned long, fd, struct stat64 __user *, statbuf)
___SYSCALL3(198, lchown, const char __user *, filename, uid_t, user, gid_t, group)
___SYSCALL0(199, getuid)
___SYSCALL0(200, getgid)
___SYSCALL0(201, geteuid)
___SYSCALL0(202, getegid)
___SYSCALL2(203, setreuid, uid_t, ruid, uid_t, euid)
___SYSCALL2(204, setregid, gid_t, rgid, gid_t, egid)
___SYSCALL2(205, getgroups, int, gidsetsize, gid_t __user *, grouplist)
___SYSCALL2(206, setgroups, int, gidsetsize, gid_t __user *, grouplist)
___SYSCALL3(207, fchown, unsigned int, fd, uid_t, user, gid_t, group)
___SYSCALL3(208, setresuid, uid_t, ruid, uid_t, euid, uid_t, suid)
___SYSCALL3(209, getresuid, uid_t __user *, ruidp, uid_t __user *, euidp, uid_t __user *, suidp)
___SYSCALL3(210, setresgid, gid_t, rgid, gid_t, egid, gid_t, sgid)
___SYSCALL3(211, getresgid, gid_t __user *, rgidp, gid_t __user *, egidp, gid_t __user *, sgidp)
___SYSCALL3(212, chown, const char __user *, filename, uid_t, user, gid_t, group)
___SYSCALL1(213, setuid, uid_t, uid)
___SYSCALL1(214, setgid, gid_t, gid)
___SYSCALL1(215, setfsuid, uid_t, uid)
___SYSCALL1(216, setfsgid, gid_t, gid)
___SYSCALL2(217, pivot_root, const char __user *, new_root, const char __user *, put_old)
___SYSCALL3(218, mincore, unsigned long, start, size_t, len, unsigned char __user *, vec)
___SYSCALL3(219, madvise, unsigned long, start, size_t, len_in, int, behavior)
___SYSCALL3(221, fcntl64, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL0(224, gettid)
___SYSCALL4(225, readahead, int, fd, uint32_t, offset_l, uint32_t, offset_h, size_t, count)
___SYSCALL5(226, setxattr, const char __user *, pathname, const char __user *, name, const void __user *, value, size_t, size, int, flags)
___SYSCALL5(227, lsetxattr, const char __user *, pathname, const char __user *, name, const void __user *, value, size_t, size, int, flags)
___SYSCALL5(228, fsetxattr, int, fd, const char __user *, name, const void __user *,value, size_t, size, int, flags)
___SYSCALL4(229, getxattr, const char __user *, pathname, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL4(230, lgetxattr, const char __user *, pathname, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL4(231, fgetxattr, int, fd, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL3(232, listxattr, const char __user *, pathname, char __user *, list, size_t, size)
___SYSCALL3(233, llistxattr, const char __user *, pathname, char __user *, list, size_t, size)
___SYSCALL3(234, flistxattr, int, fd, char __user *, list, size_t, size)
___SYSCALL2(235, removexattr, const char __user *, pathname, const char __user *, name)
___SYSCALL2(236, lremovexattr, const char __user *, pathname, const char __user *, name)
___SYSCALL2(237, fremovexattr, int, fd, const char __user *, name)
___SYSCALL2(238, tkill, pid_t, pid, int, sig)
___SYSCALL4(239, sendfile64, int, out_fd, int, in_fd, loff_t __user *, offset, size_t, count)
___SYSCALL6(240, futex_time32, u32 __user *, uaddr, int, op, u32, val, struct old_timespec32 __user *, utime, u32 __user *, uaddr2, u32, val3)
___SYSCALL3(241, sched_setaffinity, pid_t, pid, unsigned int, len, unsigned long __user *, user_mask_ptr)
___SYSCALL3(242, sched_getaffinity, pid_t, pid, unsigned int, len, unsigned long __user *, user_mask_ptr)
___SYSCALL1(243, set_thread_area, struct user_desc __user *, u_info)
___SYSCALL1(244, get_thread_area, struct user_desc __user *, u_info)
___SYSCALL2(245, io_setup, unsigned, nr_events, aio_context_t __user *, ctxp)
___SYSCALL1(246, io_destroy, aio_context_t, ctx)
___SYSCALL5(247, io_getevents_time32, __u32, ctx_id, __s32, min_nr, __s32, nr, struct io_event __user *, events, struct old_timespec32 __user *, timeout)
___SYSCALL3(248, io_submit, aio_context_t, ctx_id, long, nr, struct iocb __user * __user *, iocbpp)
___SYSCALL3(249, io_cancel, aio_context_t, ctx_id, struct iocb __user *, iocb, struct io_event __user *, result)
___SYSCALL5(250, fadvise64, int, fd, uint32_t, offset_l, uint32_t, offset_h, size_t, len, int, advice)
___SYSCALL4(253, lookup_dcookie, uint32_t, cookie64_l, uint32_t, cookie64_h, char __user *, buf, size_t, len)
___SYSCALL1(254, epoll_create, int, size)
___SYSCALL4(255, epoll_ctl, int, epfd, int, op, int, fd, struct epoll_event __user *, event)
___SYSCALL4(256, epoll_wait, int, epfd, struct epoll_event __user *, events, int, maxevents, int, timeout)
___SYSCALL5(257, remap_file_pages, unsigned long, start, unsigned long, size, unsigned long, prot, unsigned long, pgoff, unsigned long, flags)
___SYSCALL1(258, set_tid_address, int __user *, tidptr)
___SYSCALL3(259, timer_create, const clockid_t, which_clock, struct sigevent __user *, timer_event_spec, timer_t __user *, created_timer_id)
___SYSCALL4(260, timer_settime32, timer_t, timer_id, int, flags, struct old_itimerspec32 __user *, new, struct old_itimerspec32 __user *, old)
___SYSCALL2(261, timer_gettime32, timer_t, timer_id, struct old_itimerspec32 __user *, setting)
___SYSCALL1(262, timer_getoverrun, timer_t, timer_id)
___SYSCALL1(263, timer_delete, timer_t, timer_id)
___SYSCALL2(264, clock_settime32, clockid_t, which_clock, struct old_timespec32 __user *, tp)
___SYSCALL2(265, clock_gettime32, clockid_t, which_clock, struct old_timespec32 __user *, tp)
___SYSCALL2(266, clock_getres_time32, clockid_t, which_clock, struct old_timespec32 __user *, tp)
___SYSCALL4(267, clock_nanosleep_time32, clockid_t, which_clock, int, flags, struct old_timespec32 __user *, rqtp, struct old_timespec32 __user *, rmtp)
___SYSCALL3(268, statfs64, const char __user *, pathname, size_t, sz, struct statfs64 __user *, buf)
___SYSCALL3(269, fstatfs64, unsigned int, fd, size_t, sz, struct statfs64 __user *, buf)
___SYSCALL3(270, tgkill, pid_t, tgid, pid_t, pid, int, sig)
___SYSCALL2(271, utimes_time32, const char __user *, filename, struct old_timeval32 __user *, t)
___SYSCALL6(272, fadvise64_64, int, fd, uint32_t, offset_l, uint32_t, offset_h, uint32_t, len_l, uint32_t, len_h, int, advice)
___SYSCALL6(274, mbind, unsigned long, start, unsigned long, len, unsigned long, mode, const unsigned long __user *, nmask, unsigned long, maxnode, unsigned int, flags)
___SYSCALL5(275, get_mempolicy, int __user *, policy, unsigned long __user *, nmask, unsigned long, maxnode, unsigned long, addr, unsigned long, flags)
___SYSCALL3(276, set_mempolicy, int, mode, const unsigned long __user *, nmask, unsigned long, maxnode)
___SYSCALL4(277, mq_open, const char __user *, u_name, int, oflag, mode_t, mode, struct mq_attr __user *, u_attr)
___SYSCALL1(278, mq_unlink, const char __user *, u_name)
___SYSCALL5(279, mq_timedsend_time32, mqd_t, mqdes, const char __user *, u_msg_ptr, unsigned int, msg_len, unsigned int, msg_prio, const struct old_timespec32 __user *, u_abs_timeout)
___SYSCALL5(280, mq_timedreceive_time32, mqd_t, mqdes, char __user *, u_msg_ptr, unsigned int, msg_len, unsigned int __user *, u_msg_prio, const struct old_timespec32 __user *, u_abs_timeout)
___SYSCALL2(281, mq_notify, mqd_t, mqdes, const struct sigevent __user *, u_notification)
___SYSCALL3(282, mq_getsetattr, mqd_t, mqdes, const struct mq_attr __user *, u_mqstat, struct mq_attr __user *, u_omqstat)
___SYSCALL4(283, kexec_load, unsigned long, entry, unsigned long, nr_segments, struct kexec_segment __user *, segments, unsigned long, flags)
___SYSCALL5(284, waitid, int, which, pid_t, upid, struct siginfo __user *, infop, int, options, struct rusage __user *, ru)
___SYSCALL5(286, add_key, const char __user *, _type, const char __user *, _description, const void __user *, _payload, size_t, plen, key_serial_t, ringid)
___SYSCALL4(287, request_key, const char __user *, _type, const char __user *, _description, const char __user *, _callout_info, key_serial_t, destringid)
___SYSCALL5(288, keyctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
___SYSCALL3(289, ioprio_set, int, which, int, who, int, ioprio)
___SYSCALL2(290, ioprio_get, int, which, int, who)
___SYSCALL0(291, inotify_init)
___SYSCALL3(292, inotify_add_watch, int, fd, const char __user *, pathname, uint32_t, mask)
___SYSCALL2(293, inotify_rm_watch, int, fd, __s32, wd)
___SYSCALL4(294, migrate_pages, pid_t, pid, unsigned long, maxnode, const unsigned long __user *, old_nodes, const unsigned long __user *, new_nodes)
___SYSCALL4(295, openat, int, dfd, const char __user *, filename, int, flags, mode_t, mode)
___SYSCALL3(296, mkdirat, int, dfd, const char __user *, pathname, mode_t, mode)
___SYSCALL4(297, mknodat, int, dfd, const char __user *, filename, mode_t, mode, unsigned int, dev)
___SYSCALL5(298, fchownat, int, dfd, const char __user *, filename, uid_t, user, gid_t, group, int, flag)
___SYSCALL3(299, futimesat_time32, unsigned int, dfd, const char __user *, filename, struct old_timeval32 __user *, t)
___SYSCALL4(300, fstatat64, int, dfd, const char __user *, filename, struct stat64 __user *, statbuf, int, flag)
___SYSCALL3(301, unlinkat, int, dfd, const char __user *, pathname, int, flag)
___SYSCALL4(302, renameat, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname)
___SYSCALL5(303, linkat, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname, int, flags)
___SYSCALL3(304, symlinkat, const char __user *, oldname, int, newdfd, const char __user *, newname)
___SYSCALL4(305, readlinkat, int, dfd, const char __user *, pathname, char __user *, buf, int, bufsiz)
___SYSCALL3(306, fchmodat, int, dfd, const char __user *, filename, mode_t, mode)
___SYSCALL3(307, faccessat, int, dfd, const char __user *, filename, int, mode)
___SYSCALL6(308, pselect6_time32, int, n, fd_set __user *, inp, fd_set __user *, outp, fd_set __user *, exp, struct old_timespec32 __user *, tsp, void __user *, sig)
___SYSCALL5(309, ppoll_time32, struct pollfd __user *, ufds, unsigned int, nfds, struct old_timespec32 __user *, tsp, const sigset_t __user *, sigmask, size_t, sigsetsize)
___SYSCALL1(310, unshare, unsigned long, unshare_flags)
___SYSCALL2(311, set_robust_list, struct robust_list_head __user *, head, size_t, len)
___SYSCALL3(312, get_robust_list, int, pid, struct robust_list_head __user * __user *, head_ptr, size_t __user *, len_ptr)
___SYSCALL6(313, splice, int, fd_in, loff_t __user *, off_in, int, fd_out, loff_t __user *, off_out, size_t, len, unsigned int, flags)
___SYSCALL6(314, sync_file_range, int, fd, uint32_t, offset_l, uint32_t, offset_h, uint32_t, nbytes_l, uint32_t, nbytes_h, unsigned int, flags)
___SYSCALL4(315, tee, int, fdin, int, fdout, size_t, len, unsigned int, flags)
___SYSCALL4(316, vmsplice, int, fd, const struct iovec __user *, uiov, unsigned long, nr_segs, unsigned int, flags)
___SYSCALL6(317, move_pages, pid_t, pid, unsigned long, nr_pages, const void __user * __user *, pages, const int __user *, nodes, int __user *, status, int, flags)
___SYSCALL3(318, getcpu, unsigned __user *, cpup, unsigned __user *, nodep, struct getcpu_cache __user *, unused)
___SYSCALL6(319, epoll_pwait, int, epfd, struct epoll_event __user *, events, int, maxevents, int, timeout, const sigset_t __user *, sigmask, size_t, sigsetsize)
___SYSCALL4(320, utimensat_time32, unsigned int, dfd, const char __user *, filename, struct old_timespec32 __user *, t, int, flags)
___SYSCALL3(321, signalfd, int, ufd, sigset_t __user *, user_mask, size_t, sizemask)
___SYSCALL2(322, timerfd_create, int, clockid, int, flags)
___SYSCALL1(323, eventfd, unsigned int, count)
___SYSCALL6(324, fallocate, int, fd, int, mode, uint32_t, offset_l, uint32_t, offset_h, uint32_t, len_l, uint32_t, len_h)
___SYSCALL4(325, timerfd_settime32, int, ufd, int, flags, const struct old_itimerspec32 __user *, utmr, struct old_itimerspec32 __user *, otmr)
___SYSCALL2(326, timerfd_gettime32, int, ufd, struct old_itimerspec32 __user *, otmr)
___SYSCALL4(327, signalfd4, int, ufd, sigset_t __user *, user_mask, size_t, sizemask, int, flags)
___SYSCALL2(328, eventfd2, unsigned int, count, int, flags)
___SYSCALL1(329, epoll_create1, int, flags)
___SYSCALL3(330, dup3, unsigned int, oldfd, unsigned int, newfd, int, flags)
___SYSCALL2(331, pipe2, int __user *, fildes, int, flags)
___SYSCALL1(332, inotify_init1, int, flags)
___SYSCALL5(333, preadv, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
___SYSCALL5(334, pwritev, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
___SYSCALL4(335, rt_tgsigqueueinfo, pid_t, tgid, pid_t, pid, int, sig, siginfo_t __user *, uinfo)
___SYSCALL5(336, perf_event_open, struct perf_event_attr __user *, attr_uptr, pid_t, pid, int, cpu, int, group_fd, unsigned long, flags)
___SYSCALL5(337, recvmmsg_time32, int, fd, struct mmsghdr __user *, mmsg, unsigned int, vlen, unsigned int, flags, struct old_timespec32 __user *, timeout)
___SYSCALL2(338, fanotify_init, unsigned int, flags, unsigned int, event_f_flags)
___SYSCALL6(339, fanotify_mark, int, fanotify_fd, unsigned int, flags, uint32_t, mask_l, uint32_t, mask_h, int, dfd, const char  __user *, pathname)
___SYSCALL4(340, prlimit64, pid_t, pid, unsigned int, resource, const struct rlimit64 __user *, new_rlim, struct rlimit64 __user *, old_rlim)
___SYSCALL5(341, name_to_handle_at, int, dfd, const char __user *, name, struct file_handle __user *, handle, int __user *, mnt_id, int, flag)
___SYSCALL3(342, open_by_handle_at, int, mountdirfd, struct file_handle __user *, handle, int, flags)
___SYSCALL2(343, clock_adjtime32, clockid_t, which_clock, struct old_timex32 __user *, utp)
___SYSCALL1(344, syncfs, int, fd)
___SYSCALL4(345, sendmmsg, int, fd, struct mmsghdr __user *, mmsg, unsigned int, vlen, unsigned int, flags)
___SYSCALL2(346, setns, int, fd, int, nstype)
___SYSCALL6(347, process_vm_readv, pid_t, pid, const struct iovec __user *, lvec, unsigned long, liovcnt, const struct iovec __user *, rvec, unsigned long, riovcnt, unsigned long, flags)
___SYSCALL6(348, process_vm_writev, pid_t, pid, const struct iovec __user *, lvec, unsigned long, liovcnt, const struct iovec __user *, rvec, unsigned long, riovcnt,	unsigned long, flags)
___SYSCALL5(349, kcmp, pid_t, pid1, pid_t, pid2, int, type, unsigned long, idx1, unsigned long, idx2)
___SYSCALL3(350, finit_module, int, fd, const char __user *, uargs, int, flags)
___SYSCALL3(351, sched_setattr, pid_t, pid, struct sched_attr __user *, uattr, unsigned int, flags)
___SYSCALL4(352, sched_getattr, pid_t, pid, struct sched_attr __user *, uattr, unsigned int, size, unsigned int, flags)
___SYSCALL5(353, renameat2, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname, unsigned int, flags)
___SYSCALL3(354, seccomp, unsigned int, op, unsigned int, flags, void __user *, uargs)
___SYSCALL3(355, getrandom, char __user *, buf, size_t, count, unsigned int, flags)
___SYSCALL2(356, memfd_create, const char __user *, uname, unsigned int, flags)
___SYSCALL3(357, bpf, int, cmd, union bpf_attr __user *, uattr, unsigned int, size)
___SYSCALL5(358, execveat, int, fd, const char __user *, filename, const char __user *const __user *, argv, const char __user *const __user *, envp, int, flags)
___SYSCALL3(361, bind, int, fd, struct sockaddr __user *, umyaddr, int, addrlen)
___SYSCALL3(362, connect, int, fd, struct sockaddr __user *, uservaddr, int, addrlen)
___SYSCALL2(363, listen, int, fd, int, backlog)
___SYSCALL5(365, getsockopt, int, fd, int, level, int, optname, char __user *, optval, int __user *, optlen)
___SYSCALL5(366, setsockopt, int, fd, int, level, int, optname, char __user *, optval, int, optlen)
___SYSCALL3(367, getsockname, int, fd, struct sockaddr __user *, usockaddr, int __user *, usockaddr_len)
___SYSCALL3(368, getpeername, int, fd, struct sockaddr __user *, usockaddr, int __user *, usockaddr_len)
___SYSCALL3(370, sendmsg, int, fd, struct msghdr __user *, msg, unsigned int, flags)
___SYSCALL2(373, shutdown, int, fd, int, how)
___SYSCALL1(374, userfaultfd, int, flags)
___SYSCALL2(375, membarrier, int, cmd, int, flags)
___SYSCALL3(376, mlock2, unsigned long, start, size_t, len, int, flags)
___SYSCALL6(377, copy_file_range, int, fd_in, loff_t __user *, off_in, int, fd_out, loff_t __user *, off_out, size_t, len, unsigned int, flags)
___SYSCALL6(378, preadv2, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, int, flags)
___SYSCALL6(379, pwritev2, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, int, flags)
___SYSCALL4(380, pkey_mprotect, unsigned long, start, size_t, len, unsigned long, prot, int, pkey)
___SYSCALL2(381, pkey_alloc, unsigned long, flags, unsigned long, init_val)
___SYSCALL1(382, pkey_free, int, pkey)
___SYSCALL5(383, statx, int, dfd, const char __user *, filename, unsigned, flags, unsigned int, mask, struct statx __user *, buffer)
___SYSCALL2(384, arch_prctl, int, option, unsigned long, arg2)
___SYSCALL6(385, io_pgetevents_time32, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event __user *, events, struct old_timespec32 __user *, timeout, const struct __aio_sigset __user *, usig)
___SYSCALL4(386, rseq, struct rseq __user *, rseq, uint32_t, rseq_len, int, flags, uint32_t, sig)
___SYSCALL3(393, semget, key_t, key, int, nsems, int, semflg)
___SYSCALL4(394, semctl, int, semid, int, semnum, int, cmd, unsigned long, arg)
___SYSCALL3(395, shmget, key_t, key, size_t, size, int, shmflg)
___SYSCALL3(396, shmctl, int, shmid, int, cmd, struct shmid_ds __user *, buf)
___SYSCALL3(397, shmat, int, shmid, char __user *, shmaddr, int, shmflg)
___SYSCALL1(398, shmdt, char __user *, shmaddr)
___SYSCALL2(399, msgget, key_t, key, int, msgflg)
___SYSCALL4(400, msgsnd, int, msqid, void __user *, msgp, size_t, msgsz, int, msgflg)
___SYSCALL5(401, msgrcv, int, msqid, void __user *, msgp, size_t, msgsz, long, msgtyp, int, msgflg)
___SYSCALL3(402, msgctl, int, msqid, int, cmd, struct msqid_ds __user *, buf)
___SYSCALL2(403, clock_gettime, const clockid_t, which_clock, struct __kernel_timespec __user *, tp)
___SYSCALL2(404, clock_settime, const clockid_t, which_clock, const struct __kernel_timespec __user *, tp)
___SYSCALL2(405, clock_adjtime, const clockid_t, which_clock, struct __kernel_timex __user *, utx)
___SYSCALL2(406, clock_getres, const clockid_t, which_clock, struct __kernel_timespec __user *, tp)
___SYSCALL4(407, clock_nanosleep, const clockid_t, which_clock, int, flags, const struct __kernel_timespec __user *, rqtp, struct __kernel_timespec __user *, rmtp)
___SYSCALL2(408, timer_gettime, timer_t, timer_id, struct __kernel_itimerspec __user *, setting)
___SYSCALL4(409, timer_settime, timer_t, timer_id, int, flags, const struct __kernel_itimerspec __user *, new_setting, struct __kernel_itimerspec __user *, old_setting)
___SYSCALL2(410, timerfd_gettime, int, ufd, struct __kernel_itimerspec __user *, otmr)
___SYSCALL4(411, timerfd_settime, int, ufd, int, flags, const struct __kernel_itimerspec __user *, utmr, struct __kernel_itimerspec __user *, otmr)
___SYSCALL4(412, utimensat, int, dfd, const char __user *, filename, struct __kernel_timespec __user *, utimes, int, flags)
___SYSCALL6(413, pselect6, int, n, fd_set __user *, inp, fd_set __user *, outp, fd_set __user *, exp, struct __kernel_timespec __user *, tsp, void __user *, sig)
___SYSCALL5(414, ppoll, struct pollfd __user *, ufds, unsigned int, nfds, struct __kernel_timespec __user *, tsp, const sigset_t __user *, sigmask, size_t, sigsetsize)
___SYSCALL6(416, io_pgetevents, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event __user *, events, struct __kernel_timespec __user *, timeout, const struct __aio_sigset __user *, usig)
___SYSCALL5(417, recvmmsg, int, fd, struct mmsghdr __user *, mmsg, unsigned int, vlen, unsigned int, flags, struct __kernel_timespec __user *, timeout)
___SYSCALL5(418, mq_timedsend, mqd_t, mqdes, const char __user *, u_msg_ptr, size_t, msg_len, unsigned int, msg_prio, const struct __kernel_timespec __user *, u_abs_timeout)
___SYSCALL5(419, mq_timedreceive, mqd_t, mqdes, char __user *, u_msg_ptr, size_t, msg_len, unsigned int __user *, u_msg_prio, const struct __kernel_timespec __user *, u_abs_timeout)
___SYSCALL4(420, semtimedop, int, semid, struct sembuf __user *, tsops, unsigned int, nsops, const struct __kernel_timespec __user *, timeout)
___SYSCALL4(421, rt_sigtimedwait, const sigset_t __user *, uthese, siginfo_t __user *, uinfo, const struct __kernel_timespec __user *, uts, size_t, sigsetsize)
___SYSCALL6(422, futex, uint32_t __user *, uaddr, int, op, uint32_t, val, struct __kernel_timespec __user *, utime, uint32_t __user *, uaddr2, uint32_t, val3)
___SYSCALL2(423, sched_rr_get_interval, pid_t, pid, struct timespec __user *, interval)
___SYSCALL4(424, pidfd_send_signal, int, pidfd, int, sig, siginfo_t __user *, info, unsigned int, flags)
___SYSCALL2(425, io_uring_setup, uint32_t, entries, struct io_uring_params __user *, params)
___SYSCALL6(426, io_uring_enter, unsigned int, fd, uint32_t, to_submit, uint32_t, min_complete, uint32_t, flags, const sigset_t __user *, sig, size_t, sigsz)
___SYSCALL4(427, io_uring_register, unsigned int, fd, unsigned int, opcode, void __user *, arg, unsigned int, nr_args)
___SYSCALL3(428, open_tree, int, dfd, const char *, filename, unsigned, flags)
___SYSCALL5(429, move_mount, int, from_dfd, const char *, from_pathname, int, to_dfd, const char *, to_pathname, unsigned int, flags)
___SYSCALL2(430, fsopen, const char __user *, _fs_name, unsigned int, flags)
___SYSCALL5(431, fsconfig, int, fd, unsigned int, cmd, const char __user *, _key, const void __user *, _value, int, aux)
___SYSCALL3(432, fsmount, int, fs_fd, unsigned int, flags, unsigned int, attr_flags)
___SYSCALL3(433, fspick, int, dfd, const char __user *, path, unsigned int, flags)
___SYSCALL2(434, pidfd_open, pid_t, pid, unsigned int, flags)
___SYSCALL2(435, clone3, struct clone_args __user *, uargs, size_t, size)
#endif

#include "syscalls.inc.macros_end.h"
