#include "syscalls.inc.macros_begin.h"

#if !defined(___DFSAN) || defined(___DFSAN_SYSENTRS)
___SYSCALL1(4001, exit, int, exit_code)
___SYSCALL1(4246, exit_group, int, error_code)

___SYSCALL3(4011, execve, const char *, filename, const char **, argv, const char **, envp)
___SYSCALL5(4356, execveat, int, fd, const char *, filename, const char *const *, argv, const char *const *, envp, int, flags)
#endif

#if !defined(___DFSAN) || defined(___DFSAN_SYSEXITS)
___SYSCALL3(4004, write, unsigned int, fd, const char *, buf, size_t, count)
___SYSCALL3(4003, read, unsigned int, fd, char *, buf, size_t, count)
___SYSCALL2(4102, socketcall, int, call, unsigned long *, args)
___SYSCALL6(4180, sendto, int, fd, void *, buff, size_t, len, unsigned int, flags, struct sockaddr *, addr, int, addr_len)
___SYSCALL6(4176, recvfrom, int, fd, void *, ubuf, size_t, size, unsigned int, flags, struct sockaddr *, addr, int *, addr_len)
___SYSCALL3(4177, recvmsg, int, fd, struct user_msghdr *, msg, unsigned int, flags)
___SYSCALL4(4175, recv, int, fd, void *, ubuf, size_t, size, unsigned int, flags)

___SYSCALL6(4090, mips_mmap,  unsigned long, addr, unsigned long, len, unsigned long, prot, unsigned long, flags, unsigned long, fd, off_t, offset)
___SYSCALL6(4210, mips_mmap2, unsigned long, addr, unsigned long, len, unsigned long, prot, unsigned long, flags, unsigned long, fd, unsigned long, pgoff)

___SYSCALL2(4108, newfstat, unsigned int, fd, struct stat *, statbuf)
___SYSCALL3(4054, ioctl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL2(4106, newstat, const char *, filename, struct stat *, statbuf)
___SYSCALL2(4107, newlstat, const char *, filename, struct stat *, statbuf)
___SYSCALL2(4203, getcwd, char *, buf, unsigned long, size)
___SYSCALL3(4168, accept, int, fd, struct sockaddr *, upeer_sockaddr, int *, upeer_addrlen)
___SYSCALL4(4334, accept4, int, fd, struct sockaddr *, upeer_sockaddr, int *, upeer_addrlen, int, flags)
___SYSCALL3(4183, socket, int, family, int, type, int, protocol)
___SYSCALL1(4006, close, unsigned int, fd)
___SYSCALL0(4002, fork)
___SYSCALL2(4077, getrusage, int, who, struct rusage *, ru)
___SYSCALL2(4076, getrlimit, unsigned int, resource, struct rlimit *, rlim)
___SYSCALL4(4184, socketpair, int, family, int, type, int, protocol, int *, usockvec)
___SYSCALL3(4141, getdents, unsigned int, fd, struct linux_dirent *, dirent, unsigned int, count)
___SYSCALL3(4219, getdents64, unsigned int, fd, struct linux_dirent64 *, dirent, unsigned int, count)
#endif

#if !defined(___DFSAN)

___SYSCALL6(4000, syscall, long, arg1, long, arg2, long, arg3, long, arg4, long, arg5, long, arg6)
___SYSCALL3(4005, open, const char *, filename, int, flags, mode_t, mode)
___SYSCALL3(4007, waitpid, pid_t, pid, int *, stat_addr, int, options)
___SYSCALL2(4008, creat, const char *, pathname, mode_t, mode)
___SYSCALL2(4009, link, const char *, oldname, const char *, newname)
___SYSCALL1(4010, unlink, const char *, pathname)
___SYSCALL1(4012, chdir, const char *, filename)
___SYSCALL1(4013, time32, old_time32_t *, tloc)
___SYSCALL3(4014, mknod, const char *, filename, mode_t, mode, unsigned, dev)
___SYSCALL2(4015, chmod, const char *, filename, mode_t, mode)
___SYSCALL3(4016, lchown, const char *, filename, uid_t, user, gid_t, group)
___SYSCALL3(4019, lseek, unsigned int, fd, off_t, offset, unsigned int, whence)
___SYSCALL0(4020, getpid)
___SYSCALL5(4021, mount, char *, dev_name, char *, dir_name, char *, type, unsigned long, flags, void *, data)
___SYSCALL1(4022, oldumount, char *, name)
___SYSCALL1(4023, setuid, uid_t, uid)
___SYSCALL0(4024, getuid)
___SYSCALL1(4025, stime32, old_time32_t *, tptr)
___SYSCALL4(4026, ptrace, long, request, long, pid, unsigned long, addr, unsigned long, data)
___SYSCALL1(4027, alarm, unsigned int, seconds)
___SYSCALL0(4029, pause)
___SYSCALL2(4030, utime32, const char *, filename, struct old_utimbuf32 *, t)
___SYSCALL2(4033, access, const char *, filename, int, mode)
___SYSCALL1(4034, nice, int, increment)
___SYSCALL0(4036, sync)
___SYSCALL2(4037, kill, pid_t, pid, int, sig)
___SYSCALL2(4038, rename, const char *, oldname, const char *, newname)
___SYSCALL2(4039, mkdir, const char *, pathname, mode_t, mode)
___SYSCALL1(4040, rmdir, const char *, pathname)
___SYSCALL1(4041, dup, unsigned int, fildes)
___SYSCALL0(4042, sysm_pipe)
___SYSCALL1(4043, times, struct tms *, tbuf)
___SYSCALL1(4045, brk, unsigned long, brk)
___SYSCALL1(4046, setgid, gid_t, gid)
___SYSCALL0(4047, getgid)
___SYSCALL0(4049, geteuid)
___SYSCALL0(4050, getegid)
___SYSCALL1(4051, acct, const char *, name)
___SYSCALL2(4052, umount, char *, name, int, flags)
___SYSCALL3(4055, fcntl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL2(4057, setpgid, pid_t, pid, pid_t, pgid)
___SYSCALL1(4059, olduname, struct oldold_utsname *, name)
___SYSCALL1(4060, umask, int, mask)
___SYSCALL1(4061, chroot, const char *, filename)
___SYSCALL2(4062, ustat, unsigned, dev, struct ustat *, ubuf)
___SYSCALL2(4063, dup2, unsigned int, oldfd, unsigned int, newfd)
___SYSCALL0(4064, getppid)
___SYSCALL0(4065, getpgrp)
___SYSCALL0(4066, setsid)
___SYSCALL3(4067, sigaction, int, sig, const struct old_sigaction *, act, struct old_sigaction *, oact)
___SYSCALL0(4068, sgetmask)
___SYSCALL1(4069, ssetmask, int, newmask)
___SYSCALL2(4070, setreuid, uid_t, ruid, uid_t, euid)
___SYSCALL2(4071, setregid, gid_t, rgid, gid_t, egid)
___SYSCALL1(4072, sigsuspend, sigset_t *, uset)
___SYSCALL1(4073, sigpending, old_sigset_t *, uset)
___SYSCALL2(4074, sethostname, char *, name, int, len)
___SYSCALL2(4075, setrlimit, unsigned int, resource, struct rlimit *, rlim)
___SYSCALL2(4078, gettimeofday, struct __kernel_old_timeval *, tv, struct timezone *, tz)
___SYSCALL2(4079, settimeofday, struct __kernel_old_timeval *, tv, struct timezone *, tz)
___SYSCALL2(4080, getgroups, int, gidsetsize, gid_t *, grouplist)
___SYSCALL2(4081, setgroups, int, gidsetsize, gid_t *, grouplist)
___SYSCALL2(4083, symlink, const char *, oldname, const char *, newname)
___SYSCALL3(4085, readlink, const char *, path, char *, buf, int, bufsiz)
___SYSCALL1(4086, uselib, const char *, library)
___SYSCALL2(4087, swapon, const char *, specialfile, int, swap_flags)
___SYSCALL4(4088, reboot, int, magic1, int, magic2, unsigned int, cmd, void *, arg)
___SYSCALL3(4089, old_readdir, unsigned int, fd, struct old_linux_dirent *, dirent, unsigned int, count)
___SYSCALL2(4091, munmap, unsigned long, addr, size_t, len)
___SYSCALL2(4092, truncate, const char *, path, long, length)
___SYSCALL2(4093, ftruncate, unsigned int, fd, unsigned long, length)
___SYSCALL2(4094, fchmod, unsigned int, fd, mode_t, mode)
___SYSCALL3(4095, fchown, unsigned int, fd, uid_t, user, gid_t, group)
___SYSCALL2(4096, getpriority, int, which, int, who)
___SYSCALL3(4097, setpriority, int, which, int, who, int, niceval)
___SYSCALL2(4099, statfs, const char *, pathname, struct statfs *, buf)
___SYSCALL2(4100, fstatfs, unsigned int, fd, struct statfs *, buf)
___SYSCALL3(4103, syslog, int, type, char *, buf, int, len)
___SYSCALL3(4104, setitimer, int, which, struct __kernel_old_itimerval *, value, struct __kernel_old_itimerval *, ovalue)
___SYSCALL2(4105, getitimer, int, which, struct __kernel_old_itimerval *, value)
___SYSCALL1(4109, uname, struct old_utsname *, name)
___SYSCALL0(4111, vhangup)
___SYSCALL4(4114, wait4, pid_t, upid, int *, stat_addr, int, options, struct rusage *, ru)
___SYSCALL1(4115, swapoff, const char *, specialfile)
___SYSCALL1(4116, sysinfo, struct sysinfo *, info)
___SYSCALL6(4117, ipc, unsigned int, call, int, first, unsigned long, second, unsigned long, third, void *, ptr, long, fifth)
___SYSCALL1(4118, fsync, unsigned int, fd)
___SYSCALL0(4119, sigreturn)
___SYSCALL5(4120, clone, unsigned long, clone_flags, unsigned long, newsp, int *, parent_tidptr, unsigned long, tls, int *, child_tidptr)
___SYSCALL2(4121, setdomainname, char *, name, int, len)
___SYSCALL1(4122, newuname, struct new_utsname *, name)
___SYSCALL1(4124, adjtimex_time32, struct old_timex32 *, utp)
___SYSCALL3(4125, mprotect, unsigned long, start, size_t, len, unsigned long, prot)
___SYSCALL3(4126, sigprocmask, int, how, old_sigset_t *, nset, old_sigset_t *, oset)
___SYSCALL3(4128, init_module, void *, umod, unsigned long, len, const char *, uargs)
___SYSCALL2(4129, delete_module, const char *, name_user, unsigned int, flags)
___SYSCALL4(4131, quotactl, unsigned int, cmd, const char *, special, qid_t, id, void *, addr)
___SYSCALL1(4132, getpgid, pid_t, pid)
___SYSCALL1(4133, fchdir, unsigned int, fd)
___SYSCALL2(4134, bdflush, int, func, long, data)
___SYSCALL3(4135, sysfs, int, option, unsigned long, arg1, unsigned long, arg2)
___SYSCALL1(4136, personality, unsigned int, personality)
___SYSCALL1(4138, setfsuid, uid_t, uid)
___SYSCALL1(4139, setfsgid, gid_t, gid)
___SYSCALL5(4140, llseek, unsigned int, fd, unsigned long, offset_high, unsigned long, offset_low, loff_t *, result, unsigned int, whence)
___SYSCALL5(4142, select, int, n, fd_set *, inp, fd_set *, outp, fd_set *, exp, struct __kernel_old_timeval *, tvp)
___SYSCALL2(4143, flock, unsigned int, fd, unsigned int, cmd)
___SYSCALL3(4144, msync, unsigned long, start, size_t, len, int, flags)
___SYSCALL3(4145, readv, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen)
___SYSCALL3(4146, writev, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen)
___SYSCALL3(4147, cacheflush, unsigned long, addr, unsigned long, bytes, unsigned int, cache)
___SYSCALL3(4148, cachectl, char *, addr, int, nbytes, int, op)
___SYSCALL3(4149, sysmips, long, cmd, long, arg1, long, arg2)
___SYSCALL1(4151, getsid, pid_t, pid)
___SYSCALL1(4152, fdatasync, unsigned int, fd)
___SYSCALL1(4153, sysctl, struct __sysctl_args *, args)
___SYSCALL2(4154, mlock, unsigned long, start, size_t, len)
___SYSCALL2(4155, munlock, unsigned long, start, size_t, len)
___SYSCALL1(4156, mlockall, int, flags)
___SYSCALL0(4157, munlockall)
___SYSCALL2(4158, sched_setparam, pid_t, pid, struct sched_param *, param)
___SYSCALL2(4159, sched_getparam, pid_t, pid, struct sched_param *, param)
___SYSCALL3(4160, sched_setscheduler, pid_t, pid, int, policy, struct sched_param *, param)
___SYSCALL1(4161, sched_getscheduler, pid_t, pid)
___SYSCALL0(4162, sched_yield)
___SYSCALL1(4163, sched_get_priority_max, int, policy)
___SYSCALL1(4164, sched_get_priority_min, int, policy)
___SYSCALL2(4165, sched_rr_get_interval_time32, pid_t, pid, struct old_timespec32 *, interval)
___SYSCALL2(4166, nanosleep_time32, struct old_timespec32 *, rqtp, struct old_timespec32 *, rmtp)
___SYSCALL5(4167, mremap, unsigned long, addr, unsigned long, old_len, unsigned long, new_len, unsigned long, flags, unsigned long, new_addr)
___SYSCALL3(4169, bind, int, fd, struct sockaddr *, umyaddr, int, addrlen)
___SYSCALL3(4170, connect, int, fd, struct sockaddr *, uservaddr, int, addrlen)
___SYSCALL3(4171, getpeername, int, fd, struct sockaddr *, usockaddr, int *, usockaddr_len)
___SYSCALL3(4172, getsockname, int, fd, struct sockaddr *, usockaddr, int *, usockaddr_len)
___SYSCALL5(4173, getsockopt, int, fd, int, level, int, optname, char *, optval, int *, optlen)
___SYSCALL2(4174, listen, int, fd, int, backlog)
___SYSCALL4(4178, send, int, fd, void *, buff, size_t, len, unsigned int, flags)
___SYSCALL3(4179, sendmsg, int, fd, struct user_msghdr *, msg, unsigned int, flags)
___SYSCALL5(4181, setsockopt, int, fd, int, level, int, optname, char *, optval, int, optlen)
___SYSCALL2(4182, shutdown, int, fd, int, how)
___SYSCALL3(4185, setresuid, uid_t, ruid, uid_t, euid, uid_t, suid)
___SYSCALL3(4186, getresuid, uid_t *, ruidp, uid_t *, euidp, uid_t *, suidp)
___SYSCALL3(4188, poll, struct pollfd *, ufds, unsigned int, nfds, int, timeout_msecs)
___SYSCALL3(4190, setresgid, gid_t, rgid, gid_t, egid, gid_t, sgid)
___SYSCALL3(4191, getresgid, gid_t *, rgidp, gid_t *, egidp, gid_t *, sgidp)
___SYSCALL5(4192, prctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
___SYSCALL0(4193, rt_sigreturn)
___SYSCALL4(4194, rt_sigaction, int, sig, const struct sigaction *, act, struct sigaction *, oact, size_t, sigsetsize)
___SYSCALL4(4195, rt_sigprocmask, int, how, sigset_t *, nset, sigset_t *, oset, size_t, sigsetsize)
___SYSCALL2(4196, rt_sigpending, sigset_t *, uset, size_t, sigsetsize)
___SYSCALL4(4197, rt_sigtimedwait_time32, const sigset_t *, uthese, siginfo_t *, uinfo, const struct old_timespec32 *, uts, size_t, sigsetsize)
___SYSCALL3(4198, rt_sigqueueinfo, pid_t, pid, int, sig, siginfo_t *, uinfo)
___SYSCALL2(4199, rt_sigsuspend, sigset_t *, unewset, size_t, sigsetsize)
___SYSCALL6(4200, pread64, unsigned int, fd, char *, buf, size_t, count, unsigned long, unused, unsigned long, pos_low, unsigned long, pos_high)
___SYSCALL6(4201, pwrite64, unsigned int, fd, const char *, buf, size_t, count, unsigned long, unused, unsigned long, pos_low, unsigned long, pos_high)
___SYSCALL3(4202, chown, const char *, filename, uid_t, user, gid_t, group)
___SYSCALL2(4204, capget, cap_user_header_t, header, cap_user_data_t, dataptr)
___SYSCALL2(4205, capset, cap_user_header_t, header, const cap_user_data_t, data)
___SYSCALL2(4206, sigaltstack, const stack_t *, uss, stack_t *, uoss)
___SYSCALL4(4207, sendfile, int, out_fd, int, in_fd, off_t *, offset, size_t, count)
___SYSCALL4(4211, truncate64, const char *, path, unsigned long, unused, unsigned long, length_low, unsigned long, length_high)
___SYSCALL4(4212, ftruncate64, unsigned int, fd, unsigned long, unused, unsigned long, length_low, unsigned long, length_high)
___SYSCALL2(4213, stat64, const char *, filename, struct stat64 *, statbuf)
___SYSCALL2(4214, lstat64, const char *, filename, struct stat64 *, statbuf)
___SYSCALL2(4215, fstat64, unsigned long, fd, struct stat64 *, statbuf)
___SYSCALL2(4216, pivot_root, const char *, new_root, const char *, put_old)
___SYSCALL3(4217, mincore, unsigned long, start, size_t, len, unsigned char *, vec)
___SYSCALL3(4218, madvise, unsigned long, start, size_t, len_in, int, behavior)
___SYSCALL3(4220, fcntl64, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL0(4222, gettid)
___SYSCALL5(4223, readahead, int, fd, unsigned long, unused, unsigned long, offset_low, unsigned long, offset_high, size_t, count)
___SYSCALL5(4224, setxattr, const char *, pathname, const char *, name, const void *, value, size_t, size, int, flags)
___SYSCALL5(4225, lsetxattr, const char *, pathname, const char *, name, const void *, value, size_t, size, int, flags)
___SYSCALL5(4226, fsetxattr, int, fd, const char *, name, const void *,value, size_t, size, int, flags)
___SYSCALL4(4227, getxattr, const char *, pathname, const char *, name, void *, value, size_t, size)
___SYSCALL4(4228, lgetxattr, const char *, pathname, const char *, name, void *, value, size_t, size)
___SYSCALL4(4229, fgetxattr, int, fd, const char *, name, void *, value, size_t, size)
___SYSCALL3(4230, listxattr, const char *, pathname, char *, list, size_t, size)
___SYSCALL3(4231, llistxattr, const char *, pathname, char *, list, size_t, size)
___SYSCALL3(4232, flistxattr, int, fd, char *, list, size_t, size)
___SYSCALL2(4233, removexattr, const char *, pathname, const char *, name)
___SYSCALL2(4234, lremovexattr, const char *, pathname, const char *, name)
___SYSCALL2(4235, fremovexattr, int, fd, const char *, name)
___SYSCALL2(4236, tkill, pid_t, pid, int, sig)
___SYSCALL4(4237, sendfile64, int, out_fd, int, in_fd, loff_t *, offset, size_t, count)
___SYSCALL6(4238, futex_time32, u32 *, uaddr, int, op, u32, val, struct old_timespec32 *, utime, u32 *, uaddr2, u32, val3)
___SYSCALL3(4239, sched_setaffinity, pid_t, pid, unsigned int, len, unsigned long *, user_mask_ptr)
___SYSCALL3(4240, sched_getaffinity, pid_t, pid, unsigned int, len, unsigned long *, user_mask_ptr)
___SYSCALL2(4241, io_setup, unsigned, nr_events, aio_context_t *, ctxp)
___SYSCALL1(4242, io_destroy, aio_context_t, ctx)
___SYSCALL5(4243, io_getevents_time32, __u32, ctx_id, __s32, min_nr, __s32, nr, struct io_event *, events, struct old_timespec32 *, timeout)
___SYSCALL3(4244, io_submit, aio_context_t, ctx_id, long, nr, struct iocb **, iocbpp)
___SYSCALL3(4245, io_cancel, aio_context_t, ctx_id, struct iocb *, iocb, struct io_event *, result)
___SYSCALL3(4247, lookup_dcookie, u64, cookie64, char *, buf, size_t, len)
___SYSCALL1(4248, epoll_create, int, size)
___SYSCALL4(4249, epoll_ctl, int, epfd, int, op, int, fd, struct epoll_event *, event)
___SYSCALL4(4250, epoll_wait, int, epfd, struct epoll_event *, events, int, maxevents, int, timeout)
___SYSCALL5(4251, remap_file_pages, unsigned long, start, unsigned long, size, unsigned long, prot, unsigned long, pgoff, unsigned long, flags)
___SYSCALL1(4252, set_tid_address, int *, tidptr)
___SYSCALL0(4253, restart_syscall)
___SYSCALL6(4254, fadvise64_64, int, fd, unsigned long, offset_low, unsigned long, offset_high, unsigned long, len_low, unsigned long, len_high, int, advice)
___SYSCALL3(4255, statfs64, const char *, pathname, size_t, sz, struct statfs64 *, buf)
___SYSCALL3(4256, fstatfs64, unsigned int, fd, size_t, sz, struct statfs64 *, buf)
___SYSCALL3(4257, timer_create, const clockid_t, which_clock, struct sigevent *, timer_event_spec, timer_t *, created_timer_id)
___SYSCALL4(4258, timer_settime32, timer_t, timer_id, int, flags, struct old_itimerspec32 *, new_spec, struct old_itimerspec32 *, old_spec)
___SYSCALL2(4259, timer_gettime32, timer_t, timer_id, struct old_itimerspec32 *, setting)
___SYSCALL1(4260, timer_getoverrun, timer_t, timer_id)
___SYSCALL1(4261, timer_delete, timer_t, timer_id)
___SYSCALL2(4262, clock_settime32, clockid_t, which_clock, struct old_timespec32 *, tp)
___SYSCALL2(4263, clock_gettime32, clockid_t, which_clock, struct old_timespec32 *, tp)
___SYSCALL2(4264, clock_getres_time32, clockid_t, which_clock, struct old_timespec32 *, tp)
___SYSCALL4(4265, clock_nanosleep_time32, clockid_t, which_clock, int, flags, struct old_timespec32 *, rqtp, struct old_timespec32 *, rmtp)
___SYSCALL3(4266, tgkill, pid_t, tgid, pid_t, pid, int, sig)
___SYSCALL2(4267, utimes_time32, const char *, filename, struct old_timeval32 *, t)
___SYSCALL6(4268, mbind, unsigned long, start, unsigned long, len, unsigned long, mode, const unsigned long *, nmask, unsigned long, maxnode, unsigned int, flags)
___SYSCALL5(4269, get_mempolicy, int *, policy, unsigned long *, nmask, unsigned long, maxnode, unsigned long, addr, unsigned long, flags)
___SYSCALL3(4270, set_mempolicy, int, mode, const unsigned long *, nmask, unsigned long, maxnode)
___SYSCALL4(4271, mq_open, const char *, u_name, int, oflag, mode_t, mode, struct mq_attr *, u_attr)
___SYSCALL1(4272, mq_unlink, const char *, u_name)
___SYSCALL5(4273, mq_timedsend_time32, mqd_t, mqdes, const char *, u_msg_ptr, unsigned int, msg_len, unsigned int, msg_prio, const struct old_timespec32 *, u_abs_timeout)
___SYSCALL5(4274, mq_timedreceive_time32, mqd_t, mqdes, char *, u_msg_ptr, unsigned int, msg_len, unsigned int *, u_msg_prio, const struct old_timespec32 *, u_abs_timeout)
___SYSCALL2(4275, mq_notify, mqd_t, mqdes, const struct sigevent *, u_notification)
___SYSCALL3(4276, mq_getsetattr, mqd_t, mqdes, const struct mq_attr *, u_mqstat, struct mq_attr *, u_omqstat)
___SYSCALL5(4278, waitid, int, which, pid_t, upid, struct siginfo *, infop, int, options, struct rusage *, ru)
___SYSCALL5(4280, add_key, const char *, _type, const char *, _description, const void *, _payload, size_t, plen, key_serial_t, ringid)
___SYSCALL4(4281, request_key, const char *, _type, const char *, _description, const char *, _callout_info, key_serial_t, destringid)
___SYSCALL5(4282, keyctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
___SYSCALL1(4283, set_thread_area, unsigned long, addr)
___SYSCALL0(4284, inotify_init)
___SYSCALL3(4285, inotify_add_watch, int, fd, const char *, pathname, u32, mask)
___SYSCALL2(4286, inotify_rm_watch, int, fd, __s32, wd)
___SYSCALL4(4287, migrate_pages, pid_t, pid, unsigned long, maxnode, const unsigned long *, old_nodes, const unsigned long *, new_nodes)
___SYSCALL4(4288, openat, int, dfd, const char *, filename, int, flags, mode_t, mode)
___SYSCALL3(4289, mkdirat, int, dfd, const char *, pathname, mode_t, mode)
___SYSCALL4(4290, mknodat, int, dfd, const char *, filename, mode_t, mode, unsigned int, dev)
___SYSCALL5(4291, fchownat, int, dfd, const char *, filename, uid_t, user, gid_t, group, int, flag)
___SYSCALL3(4292, futimesat_time32, unsigned int, dfd, const char *, filename, struct old_timeval32 *, t)
___SYSCALL4(4293, fstatat64, int, dfd, const char *, filename, struct stat64 *, statbuf, int, flag)
___SYSCALL3(4294, unlinkat, int, dfd, const char *, pathname, int, flag)
___SYSCALL4(4295, renameat, int, olddfd, const char *, oldname, int, newdfd, const char *, newname)
___SYSCALL5(4296, linkat, int, olddfd, const char *, oldname, int, newdfd, const char *, newname, int, flags)
___SYSCALL3(4297, symlinkat, const char *, oldname, int, newdfd, const char *, newname)
___SYSCALL4(4298, readlinkat, int, dfd, const char *, pathname, char *, buf, int, bufsiz)
___SYSCALL3(4299, fchmodat, int, dfd, const char *, filename, mode_t, mode)
___SYSCALL3(4300, faccessat, int, dfd, const char *, filename, int, mode)
___SYSCALL6(4301, pselect6_time32, int, n, fd_set *, inp, fd_set *, outp, fd_set *, exp, struct old_timespec32 *, tsp, void *, sig)
___SYSCALL5(4302, ppoll_time32,  struct pollfd *, ufds, unsigned int, nfds, struct old_timespec32 *, tsp, const sigset_t *, sigmask, size_t, sigsetsize)
___SYSCALL1(4303, unshare, unsigned long, unshare_flags)
___SYSCALL6(4304, splice, int, fd_in, loff_t *, off_in, int, fd_out, loff_t *, off_out, size_t, len, unsigned int, flags)
___SYSCALL6(4305, sync_file_range, int, fd, unsigned long, offset_low, unsigned long, offset_high, unsigned long, nbytes_low, unsigned long, nbytes_high, unsigned int, flags)
___SYSCALL4(4306, tee, int, fdin, int, fdout, size_t, len, unsigned int, flags)
___SYSCALL4(4307, vmsplice, int, fd, const struct iovec *, uiov, unsigned long, nr_segs, unsigned int, flags)
___SYSCALL6(4308, move_pages, pid_t, pid, unsigned long, nr_pages, const void **, pages, const int *, nodes, int *, status, int, flags)
___SYSCALL2(4309, set_robust_list, struct robust_list_head *, head, size_t, len)
___SYSCALL3(4310, get_robust_list, int, pid, struct robust_list_head **, head_ptr, size_t *, len_ptr)
___SYSCALL4(4311, kexec_load, unsigned long, entry, unsigned long, nr_segments, struct kexec_segment *, segments, unsigned long, flags)
___SYSCALL3(4312, getcpu, unsigned *, cpup, unsigned *, nodep, struct getcpu_cache *, unused)
___SYSCALL6(4313, epoll_pwait, int, epfd, struct epoll_event *, events, int, maxevents, int, timeout, const sigset_t *, sigmask, size_t, sigsetsize)
___SYSCALL3(4314, ioprio_set, int, which, int, who, int, ioprio)
___SYSCALL2(4315, ioprio_get, int, which, int, who)
___SYSCALL4(4316, utimensat_time32, unsigned int, dfd, const char *, filename, struct old_timespec32 *, t, int, flags)
___SYSCALL3(4317, signalfd, int, ufd, sigset_t *, user_mask, size_t, sizemask)
___SYSCALL1(4319, eventfd, unsigned int, count)
___SYSCALL6(4320, fallocate, int, fd, int, mode, unsigned long, offset_low, unsigned long, offset_high, unsigned long, len_low, unsigned long, len_high)
___SYSCALL2(4321, timerfd_create, int, clockid, int, flags)
___SYSCALL2(4322, timerfd_gettime32, int, ufd, struct old_itimerspec32 *, otmr)
___SYSCALL4(4323, timerfd_settime32, int, ufd, int, flags, const struct old_itimerspec32 *, utmr, struct old_itimerspec32 *, otmr)
___SYSCALL4(4324, signalfd4, int, ufd, sigset_t *, user_mask, size_t, sizemask, int, flags)
___SYSCALL2(4325, eventfd2, unsigned int, count, int, flags)
___SYSCALL1(4326, epoll_create1, int, flags)
___SYSCALL3(4327, dup3, unsigned int, oldfd, unsigned int, newfd, int, flags)
___SYSCALL2(4328, pipe2, int *, fildes, int, flags)
___SYSCALL1(4329, inotify_init1, int, flags)
___SYSCALL5(4330, preadv, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
___SYSCALL5(4331, pwritev, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
___SYSCALL4(4332, rt_tgsigqueueinfo, pid_t, tgid, pid_t, pid, int, sig, siginfo_t *, uinfo)
___SYSCALL5(4333, perf_event_open, struct perf_event_attr *, attr_uptr, pid_t, pid, int, cpu, int, group_fd, unsigned long, flags)
___SYSCALL5(4335, recvmmsg_time32, int, fd, struct mmsghdr *, mmsg, unsigned int, vlen, unsigned int, flags, struct old_timespec32 *, timeout)
___SYSCALL2(4336, fanotify_init, unsigned int, flags, unsigned int, event_f_flags)
___SYSCALL5(4337, fanotify_mark, int, fanotify_fd, unsigned int, flags, __u64, mask, int, dfd, const char *, pathname)
___SYSCALL4(4338, prlimit64, pid_t, pid, unsigned int, resource, const struct rlimit64 *, new_rlim, struct rlimit64 *, old_rlim)
___SYSCALL5(4339, name_to_handle_at, int, dfd, const char *, name, struct file_handle *, handle, int *, mnt_id, int, flag)
___SYSCALL3(4340, open_by_handle_at, int, mountdirfd, struct file_handle *, handle, int, flags)
___SYSCALL2(4341, clock_adjtime32, clockid_t, which_clock, struct old_timex32 *, utp)
___SYSCALL1(4342, syncfs, int, fd)
___SYSCALL4(4343, sendmmsg, int, fd, struct mmsghdr *, mmsg, unsigned int, vlen, unsigned int, flags)
___SYSCALL2(4344, setns, int, fd, int, flags)
___SYSCALL6(4345, process_vm_readv, pid_t, pid, const struct iovec *, lvec, unsigned long, liovcnt, const struct iovec *, rvec, unsigned long, riovcnt, unsigned long, flags)
___SYSCALL6(4346, process_vm_writev, pid_t, pid, const struct iovec *, lvec, unsigned long, liovcnt, const struct iovec *, rvec, unsigned long, riovcnt, unsigned long, flags)
___SYSCALL5(4347, kcmp, pid_t, pid1, pid_t, pid2, int, type, unsigned long, idx1, unsigned long, idx2)
___SYSCALL3(4348, finit_module, int, fd, const char *, uargs, int, flags)
___SYSCALL3(4349, sched_setattr, pid_t, pid, struct sched_attr *, uattr, unsigned int, flags)
___SYSCALL4(4350, sched_getattr, pid_t, pid, struct sched_attr *, uattr, unsigned int, usize, unsigned int, flags)
___SYSCALL5(4351, renameat2, int, olddfd, const char *, oldname, int, newdfd, const char *, newname, unsigned int, flags)
___SYSCALL3(4352, seccomp, unsigned int, op, unsigned int, flags, void *, uargs)
___SYSCALL3(4353, getrandom, char *, buf, size_t, count, unsigned int, flags)
___SYSCALL2(4354, memfd_create, const char *, uname, unsigned int, flags)
___SYSCALL3(4355, bpf, int, cmd, union bpf_attr *, uattr, unsigned int, size)
___SYSCALL1(4357, userfaultfd, int, flags)
___SYSCALL2(4358, membarrier, int, cmd, int, flags)
___SYSCALL3(4359, mlock2, unsigned long, start, size_t, len, int, flags)
___SYSCALL6(4360, copy_file_range, int, fd_in, loff_t *, off_in, int, fd_out, loff_t *, off_out, size_t, len, unsigned int, flags)
___SYSCALL6(4361, preadv2, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, rwf_t, flags)
___SYSCALL6(4362, pwritev2, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, rwf_t, flags)
___SYSCALL4(4363, pkey_mprotect, unsigned long, start, size_t, len, unsigned long, prot, int, pkey)
___SYSCALL2(4364, pkey_alloc, unsigned long, flags, unsigned long, init_val)
___SYSCALL1(4365, pkey_free, int, pkey)
___SYSCALL5(4366, statx, int, dfd, const char *, filename, unsigned, flags, unsigned int, mask, struct statx *, buffer)
___SYSCALL4(4367, rseq, struct rseq *, rseq, u32, rseq_len, int, flags, u32, sig)
___SYSCALL6(4368, io_pgetevents_time32, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event *, events, struct old_timespec32 *, timeout, const struct __aio_sigset *, usig)
___SYSCALL3(4393, semget, key_t, key, int, nsems, int, semflg)
___SYSCALL4(4394, semctl, int, semid, int, semnum, int, cmd, unsigned long, arg)
___SYSCALL3(4395, shmget, key_t, key, size_t, size, int, shmflg)
___SYSCALL3(4396, shmctl, int, shmid, int, cmd, struct shmid_ds *, buf)
___SYSCALL3(4397, shmat, int, shmid, char *, shmaddr, int, shmflg)
___SYSCALL1(4398, shmdt, char *, shmaddr)
___SYSCALL2(4399, msgget, key_t, key, int, msgflg)
___SYSCALL4(4400, msgsnd, int, msqid, struct msgbuf *, msgp, size_t, msgsz, int, msgflg)
___SYSCALL5(4401, msgrcv, int, msqid, struct msgbuf *, msgp, size_t, msgsz, long, msgtyp, int, msgflg)
___SYSCALL3(4402, msgctl, int, msqid, int, cmd, struct msqid_ds *, buf)
___SYSCALL2(4403, clock_gettime, const clockid_t, which_clock, struct __kernel_timespec *, tp)
___SYSCALL2(4404, clock_settime, const clockid_t, which_clock, const struct __kernel_timespec *, tp)
___SYSCALL2(4405, clock_adjtime, const clockid_t, which_clock, struct __kernel_timex *, utx)
___SYSCALL2(4406, clock_getres, const clockid_t, which_clock, struct __kernel_timespec *, tp)
___SYSCALL4(4407, clock_nanosleep, const clockid_t, which_clock, int, flags, const struct __kernel_timespec *, rqtp, struct __kernel_timespec *, rmtp)
___SYSCALL2(4408, timer_gettime, timer_t, timer_id, struct __kernel_itimerspec *, setting)
___SYSCALL4(4409, timer_settime, timer_t, timer_id, int, flags, const struct __kernel_itimerspec *, new_setting, struct __kernel_itimerspec *, old_setting)
___SYSCALL2(4410, timerfd_gettime, int, ufd, struct __kernel_itimerspec *, otmr)
___SYSCALL4(4411, timerfd_settime, int, ufd, int, flags, const struct __kernel_itimerspec *, utmr, struct __kernel_itimerspec *, otmr)
___SYSCALL4(4412, utimensat, int, dfd, const char *, filename, struct __kernel_timespec *, utimes, int, flags)
___SYSCALL6(4413, pselect6, int, n, fd_set *, inp, fd_set *, outp, fd_set *, exp, struct __kernel_timespec *, tsp, void *, sig)
___SYSCALL5(4414, ppoll, struct pollfd *, ufds, unsigned int, nfds, struct __kernel_timespec *, tsp, const sigset_t *, sigmask, size_t, sigsetsize)
___SYSCALL6(4416, io_pgetevents, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event *, events, struct __kernel_timespec *, timeout, const struct __aio_sigset *, usig)
___SYSCALL5(4417, recvmmsg, int, fd, struct mmsghdr *, mmsg, unsigned int, vlen, unsigned int, flags, struct __kernel_timespec *, timeout)
___SYSCALL5(4418, mq_timedsend, mqd_t, mqdes, const char *, u_msg_ptr, size_t, msg_len, unsigned int, msg_prio, const struct __kernel_timespec *, u_abs_timeout)
___SYSCALL5(4419, mq_timedreceive, mqd_t, mqdes, char *, u_msg_ptr, size_t, msg_len, unsigned int *, u_msg_prio, const struct __kernel_timespec *, u_abs_timeout)
___SYSCALL4(4420, semtimedop, int, semid, struct sembuf *, tsops, unsigned int, nsops, const struct __kernel_timespec *, timeout)
___SYSCALL4(4421, rt_sigtimedwait, const sigset_t *, uthese, siginfo_t *, uinfo, const struct __kernel_timespec *, uts, size_t, sigsetsize)
___SYSCALL6(4422, futex, u32 *, uaddr, int, op, u32, val, struct __kernel_timespec *, utime, u32 *, uaddr2, u32, val3)
___SYSCALL2(4423, sched_rr_get_interval, pid_t, pid, struct __kernel_timespec *, interval)
___SYSCALL4(4424, pidfd_send_signal, int, pidfd, int, sig, siginfo_t *, info, unsigned int, flags)
___SYSCALL2(4425, io_uring_setup, u32, entries, struct io_uring_params *, params)
___SYSCALL6(4426, io_uring_enter, unsigned int, fd, u32, to_submit, u32, min_complete, u32, flags, const sigset_t *, sig, size_t, sigsz)
___SYSCALL4(4427, io_uring_register, unsigned int, fd, unsigned int, opcode, void *, arg, unsigned int, nr_args)
___SYSCALL3(4428, open_tree, int, dfd, const char *, filename, unsigned, flags)
___SYSCALL5(4429, move_mount, int, from_dfd, const char *, from_pathname, int, to_dfd, const char *, to_pathname, unsigned int, flags)
___SYSCALL2(4430, fsopen, const char *, _fs_name, unsigned int, flags)
___SYSCALL5(4431, fsconfig, int, fd, unsigned int, cmd, const char *, _key, const void *, _value, int, aux)
___SYSCALL3(4432, fsmount, int, fs_fd, unsigned int, flags, unsigned int, attr_flags)
___SYSCALL3(4433, fspick, int, dfd, const char *, path, unsigned int, flags)
___SYSCALL2(4434, pidfd_open, pid_t, pid, unsigned int, flags)
___SYSCALL2(4435, clone3, struct clone_args *, uargs, size_t, size)
___SYSCALL4(4437, openat2, int, dfd, const char *, filename, struct open_how *, how, size_t, usize)
___SYSCALL3(4438, pidfd_getfd, int, pidfd, int, fd, unsigned int, flags)

#endif

#include "syscalls.inc.macros_end.h"
