#include "syscalls.inc.macros_begin.h"

___SYSCALL2(0, io_setup, unsigned, nr_events, aio_context_t __user *, ctxp)
___SYSCALL1(1, io_destroy, aio_context_t, ctx)
___SYSCALL3(2, io_submit, aio_context_t, ctx_id, long, nr, struct iocb __user * __user *, iocbpp)
___SYSCALL3(3, io_cancel, aio_context_t, ctx_id, struct iocb __user *, iocb, struct io_event __user *, result)
___SYSCALL5(4, io_getevents, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event __user *, events, struct __kernel_timespec __user *, timeout)
___SYSCALL5(5, setxattr, const char __user *, pathname, const char __user *, name, const void __user *, value, size_t, size, int, flags)
___SYSCALL5(6, lsetxattr, const char __user *, pathname, const char __user *, name, const void __user *, value, size_t, size, int, flags)
___SYSCALL5(7, fsetxattr, int, fd, const char __user *, name, const void __user *,value, size_t, size, int, flags)
___SYSCALL4(8, getxattr, const char __user *, pathname, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL4(9, lgetxattr, const char __user *, pathname, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL4(10, fgetxattr, int, fd, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL3(11, listxattr, const char __user *, pathname, char __user *, list, size_t, size)
___SYSCALL3(12, llistxattr, const char __user *, pathname, char __user *, list, size_t, size)
___SYSCALL3(13, flistxattr, int, fd, char __user *, list, size_t, size)
___SYSCALL2(14, removexattr, const char __user *, pathname, const char __user *, name)
___SYSCALL2(15, lremovexattr, const char __user *, pathname, const char __user *, name)
___SYSCALL2(16, fremovexattr, int, fd, const char __user *, name)
___SYSCALL2(17, getcwd, char __user *, buf, unsigned long, size)
___SYSCALL3(18, lookup_dcookie, u64, cookie64, char __user *, buf, size_t, len)
___SYSCALL2(19, eventfd2, unsigned int, count, int, flags)
___SYSCALL1(20, epoll_create1, int, flags)
___SYSCALL4(21, epoll_ctl, int, epfd, int, op, int, fd, struct epoll_event __user *, event)
___SYSCALL6(22, epoll_pwait, int, epfd, struct epoll_event __user *, events, int, maxevents, int, timeout, const sigset_t __user *, sigmask, size_t, sigsetsize)
___SYSCALL1(23, dup, unsigned int, fildes)
___SYSCALL3(24, dup3, unsigned int, oldfd, unsigned int, newfd, int, flags)
___SYSCALL3(25, fcntl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL1(26, inotify_init1, int, flags)
___SYSCALL3(27, inotify_add_watch, int, fd, const char __user *, pathname, u32, mask)
___SYSCALL2(28, inotify_rm_watch, int, fd, __s32, wd)
___SYSCALL3(29, ioctl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL3(30, ioprio_set, int, which, int, who, int, ioprio)
___SYSCALL2(31, ioprio_get, int, which, int, who)
___SYSCALL2(32, flock, unsigned int, fd, unsigned int, cmd)
___SYSCALL4(33, mknodat, int, dfd, const char __user *, filename, mode_t, mode, unsigned int, dev)
___SYSCALL3(34, mkdirat, int, dfd, const char __user *, pathname, mode_t, mode)
___SYSCALL3(35, unlinkat, int, dfd, const char __user *, pathname, int, flag)
___SYSCALL3(36, symlinkat, const char __user *, oldname, int, newdfd, const char __user *, newname)
___SYSCALL5(37, linkat, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname, int, flags)
___SYSCALL4(38, renameat, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname)
___SYSCALL2(39, umount, char __user *, name, int, flags)
___SYSCALL5(40, mount, char __user *, dev_name, char __user *, dir_name, char __user *, type, unsigned long, flags, void __user *, data)
___SYSCALL2(41, pivot_root, const char __user *, new_root, const char __user *, put_old)
___SYSCALL2(43, statfs, const char __user *, pathname, struct statfs __user *, buf)
___SYSCALL2(44, fstatfs, unsigned int, fd, struct statfs __user *, buf)
___SYSCALL2(45, truncate, const char __user *, path, long, length)
___SYSCALL2(46, ftruncate, unsigned int, fd, unsigned long, length)
___SYSCALL4(47, fallocate, int, fd, int, mode, loff_t, offset, loff_t, len)
___SYSCALL3(48, faccessat, int, dfd, const char __user *, filename, int, mode)
___SYSCALL1(49, chdir, const char __user *, filename)
___SYSCALL1(50, fchdir, unsigned int, fd)
___SYSCALL1(51, chroot, const char __user *, filename)
___SYSCALL2(52, fchmod, unsigned int, fd, mode_t, mode)
___SYSCALL3(53, fchmodat, int, dfd, const char __user *, filename, mode_t, mode)
___SYSCALL5(54, fchownat, int, dfd, const char __user *, filename, uid_t, user, gid_t, group, int, flag)
___SYSCALL3(55, fchown, unsigned int, fd, uid_t, user, gid_t, group)
___SYSCALL4(56, openat, int, dfd, const char __user *, filename, int, flags, mode_t, mode)
___SYSCALL1(57, close, unsigned int, fd)
___SYSCALL0(58, vhangup)
___SYSCALL2(59, pipe2, int __user *, fildes, int, flags)
___SYSCALL4(60, quotactl, unsigned int, cmd, const char __user *, special, qid_t, id, void __user *, addr)
___SYSCALL3(61, getdents64, unsigned int, fd, struct linux_dirent64 __user *, dirent, unsigned int, count)
___SYSCALL3(62, lseek, unsigned int, fd, off_t, offset, unsigned int, whence)
___SYSCALL3(63, read, unsigned int, fd, char __user *, buf, size_t, count)
___SYSCALL3(64, write, unsigned int, fd, const char __user *, buf, size_t, count)
___SYSCALL3(65, readv, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen)
___SYSCALL3(66, writev, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen)
___SYSCALL4(67, pread64, unsigned int, fd, char __user *, buf, size_t, count, loff_t, pos)
___SYSCALL4(68, pwrite64, unsigned int, fd, const char __user *, buf, size_t, count, loff_t, pos)
___SYSCALL5(69, preadv, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
___SYSCALL5(70, pwritev, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
___SYSCALL4(71, sendfile64, int, out_fd, int, in_fd, loff_t __user *, offset, size_t, count)
___SYSCALL6(72, pselect6, int, n, fd_set __user *, inp, fd_set __user *, outp, fd_set __user *, exp, struct __kernel_timespec __user *, tsp, void __user *, sig)
___SYSCALL5(73, ppoll, struct pollfd __user *, ufds, unsigned int, nfds, struct __kernel_timespec __user *, tsp, const sigset_t __user *, sigmask, size_t, sigsetsize)
___SYSCALL4(74, signalfd4, int, ufd, sigset_t __user *, user_mask, size_t, sizemask, int, flags)
___SYSCALL4(75, vmsplice, int, fd, const struct iovec __user *, uiov, unsigned long, nr_segs, unsigned int, flags)
___SYSCALL6(76, splice, int, fd_in, loff_t __user *, off_in, int, fd_out, loff_t __user *, off_out, size_t, len, unsigned int, flags)
___SYSCALL4(77, tee, int, fdin, int, fdout, size_t, len, unsigned int, flags)
___SYSCALL4(78, readlinkat, int, dfd, const char __user *, pathname, char __user *, buf, int, bufsiz)
___SYSCALL4(79, newfstatat, int, dfd, const char __user *, filename, struct stat __user *, statbuf, int, flag)
___SYSCALL2(80, newfstat, unsigned int, fd, struct stat __user *, statbuf)
___SYSCALL0(81, sync)
___SYSCALL1(82, fsync, unsigned int, fd)
___SYSCALL1(83, fdatasync, unsigned int, fd)
___SYSCALL4(84, sync_file_range, int, fd, loff_t, offset, loff_t, nbytes, unsigned int, flags)
___SYSCALL2(85, timerfd_create, int, clockid, int, flags)
___SYSCALL4(86, timerfd_settime, int, ufd, int, flags, const struct __kernel_itimerspec __user *, utmr, struct __kernel_itimerspec __user *, otmr)
___SYSCALL2(87, timerfd_gettime, int, ufd, struct __kernel_itimerspec __user *, otmr)
___SYSCALL4(88, utimensat, int, dfd, const char __user *, filename, struct __kernel_timespec __user *, utimes, int, flags)
___SYSCALL1(89, acct, const char __user *, name)
___SYSCALL2(90, capget, cap_user_header_t, header, cap_user_data_t, dataptr)
___SYSCALL2(91, capset, cap_user_header_t, header, const cap_user_data_t, data)
___SYSCALL1(92, arm64_personality, unsigned int, personality)
___SYSCALL1(93, exit, int, error_code)
___SYSCALL1(94, exit_group, int, error_code)
___SYSCALL5(95, waitid, int, which, pid_t, upid, struct siginfo __user *, infop, int, options, struct rusage __user *, ru)
___SYSCALL1(96, set_tid_address, int __user *, tidptr)
___SYSCALL1(97, unshare, unsigned long, unshare_flags)
___SYSCALL6(98, futex, u32 __user *, uaddr, int, op, u32, val, struct __kernel_timespec __user *, utime, u32 __user *, uaddr2, u32, val3)
___SYSCALL2(99, set_robust_list, struct robust_list_head __user *, head, size_t, len)
___SYSCALL3(100, get_robust_list, int, pid, struct robust_list_head __user * __user *, head_ptr, size_t __user *, len_ptr)
___SYSCALL2(101, nanosleep, struct __kernel_timespec __user *, rqtp, struct __kernel_timespec __user *, rmtp)
___SYSCALL2(102, getitimer, int, which, struct itimerval __user *, value)
___SYSCALL3(103, setitimer, int, which, struct itimerval __user *, value, struct itimerval __user *, ovalue)
___SYSCALL4(104, kexec_load, unsigned long, entry, unsigned long, nr_segments, struct kexec_segment __user *, segments, unsigned long, flags)
___SYSCALL3(105, init_module, void __user *, umod, unsigned long, len, const char __user *, uargs)
___SYSCALL2(106, delete_module, const char __user *, name_user, unsigned int, flags)
___SYSCALL3(107, timer_create, const clockid_t, which_clock, struct sigevent __user *, timer_event_spec, timer_t __user *, created_timer_id)
___SYSCALL2(108, timer_gettime, timer_t, timer_id, struct __kernel_itimerspec __user *, setting)
___SYSCALL1(109, timer_getoverrun, timer_t, timer_id)
___SYSCALL4(110, timer_settime, timer_t, timer_id, int, flags, const struct __kernel_itimerspec __user *, new_setting, struct __kernel_itimerspec __user *, old_setting)
___SYSCALL1(111, timer_delete, timer_t, timer_id)
___SYSCALL2(112, clock_settime, const clockid_t, which_clock, const struct __kernel_timespec __user *, tp)
___SYSCALL2(113, clock_gettime, const clockid_t, which_clock, struct __kernel_timespec __user *, tp)
___SYSCALL2(114, clock_getres, const clockid_t, which_clock, struct __kernel_timespec __user *, tp)
___SYSCALL4(115, clock_nanosleep, const clockid_t, which_clock, int, flags, const struct __kernel_timespec __user *, rqtp, struct __kernel_timespec __user *, rmtp)
___SYSCALL3(116, syslog, int, type, char __user *, buf, int, len)
___SYSCALL4(117, ptrace, long, request, long, pid, unsigned long, addr, unsigned long, data)
___SYSCALL2(118, sched_setparam, pid_t, pid, struct sched_param __user *, param)
___SYSCALL3(119, sched_setscheduler, pid_t, pid, int, policy, struct sched_param __user *, param)
___SYSCALL1(120, sched_getscheduler, pid_t, pid)
___SYSCALL2(121, sched_getparam, pid_t, pid, struct sched_param __user *, param)
___SYSCALL3(122, sched_setaffinity, pid_t, pid, unsigned int, len, unsigned long __user *, user_mask_ptr)
___SYSCALL3(123, sched_getaffinity, pid_t, pid, unsigned int, len, unsigned long __user *, user_mask_ptr)
___SYSCALL0(124, sched_yield)
___SYSCALL1(125, sched_get_priority_max, int, policy)
___SYSCALL1(126, sched_get_priority_min, int, policy)
___SYSCALL2(127, sched_rr_get_interval, pid_t, pid, struct __kernel_timespec __user *, interval)
___SYSCALL0(128, restart_syscall)
___SYSCALL2(129, kill, pid_t, pid, int, sig)
___SYSCALL2(130, tkill, pid_t, pid, int, sig)
___SYSCALL3(131, tgkill, pid_t, tgid, pid_t, pid, int, sig)
___SYSCALL2(132, sigaltstack, const stack_t __user *,uss, stack_t __user *,uoss)
___SYSCALL2(133, rt_sigsuspend, sigset_t __user *, unewset, size_t, sigsetsize)
___SYSCALL4(134, rt_sigaction, int, sig, const struct sigaction __user *, act, struct sigaction __user *, oact, size_t, sigsetsize)
___SYSCALL4(135, rt_sigprocmask, int, how, sigset_t __user *, nset, sigset_t __user *, oset, size_t, sigsetsize)
___SYSCALL2(136, rt_sigpending, sigset_t __user *, uset, size_t, sigsetsize)
___SYSCALL4(137, rt_sigtimedwait, const sigset_t __user *, uthese, siginfo_t __user *, uinfo, const struct __kernel_timespec __user *, uts, size_t, sigsetsize)
___SYSCALL3(138, rt_sigqueueinfo, pid_t, pid, int, sig, siginfo_t __user *, uinfo)
___SYSCALL0(139, rt_sigreturn)
___SYSCALL3(140, setpriority, int, which, int, who, int, niceval)
___SYSCALL2(141, getpriority, int, which, int, who)
___SYSCALL4(142, reboot, int, magic1, int, magic2, unsigned int, cmd, void __user *, arg)
___SYSCALL2(143, setregid, gid_t, rgid, gid_t, egid)
___SYSCALL1(144, setgid, gid_t, gid)
___SYSCALL2(145, setreuid, uid_t, ruid, uid_t, euid)
___SYSCALL1(146, setuid, uid_t, uid)
___SYSCALL3(147, setresuid, uid_t, ruid, uid_t, euid, uid_t, suid)
___SYSCALL3(148, getresuid, uid_t __user *, ruidp, uid_t __user *, euidp, uid_t __user *, suidp)
___SYSCALL3(149, setresgid, gid_t, rgid, gid_t, egid, gid_t, sgid)
___SYSCALL3(150, getresgid, gid_t __user *, rgidp, gid_t __user *, egidp, gid_t __user *, sgidp)
___SYSCALL1(151, setfsuid, uid_t, uid)
___SYSCALL1(152, setfsgid, gid_t, gid)
___SYSCALL1(153, times, struct tms __user *, tbuf)
___SYSCALL2(154, setpgid, pid_t, pid, pid_t, pgid)
___SYSCALL1(155, getpgid, pid_t, pid)
___SYSCALL1(156, getsid, pid_t, pid)
___SYSCALL0(157, setsid)
___SYSCALL2(158, getgroups, int, gidsetsize, gid_t __user *, grouplist)
___SYSCALL2(159, setgroups, int, gidsetsize, gid_t __user *, grouplist)
___SYSCALL1(160, newuname, struct new_utsname __user *, name)
___SYSCALL2(161, sethostname, char __user *, name, int, len)
___SYSCALL2(162, setdomainname, char __user *, name, int, len)
___SYSCALL2(163, getrlimit, unsigned int, resource, struct rlimit __user *, rlim)
___SYSCALL2(164, setrlimit, unsigned int, resource, struct rlimit __user *, rlim)
___SYSCALL2(165, getrusage, int, who, struct rusage __user *, ru)
___SYSCALL1(166, umask, int, mask)
___SYSCALL5(167, prctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
___SYSCALL3(168, getcpu, unsigned __user *, cpup, unsigned __user *, nodep, struct getcpu_cache __user *, unused)
___SYSCALL2(169, gettimeofday, struct timeval __user *, tv, struct timezone __user *, tz)
___SYSCALL2(170, settimeofday, struct timeval __user *, tv, struct timezone __user *, tz)
___SYSCALL1(171, adjtimex, struct __kernel_timex __user *, txc_p)
___SYSCALL0(172, getpid)
___SYSCALL0(173, getppid)
___SYSCALL0(174, getuid)
___SYSCALL0(175, geteuid)
___SYSCALL0(176, getgid)
___SYSCALL0(177, getegid)
___SYSCALL0(178, gettid)
___SYSCALL1(179, sysinfo, struct sysinfo __user *, info)
___SYSCALL4(180, mq_open, const char __user *, u_name, int, oflag, mode_t, mode, struct mq_attr __user *, u_attr)
___SYSCALL1(181, mq_unlink, const char __user *, u_name)
___SYSCALL5(182, mq_timedsend, mqd_t, mqdes, const char __user *, u_msg_ptr, size_t, msg_len, unsigned int, msg_prio, const struct __kernel_timespec __user *, u_abs_timeout)
___SYSCALL5(183, mq_timedreceive, mqd_t, mqdes, char __user *, u_msg_ptr, size_t, msg_len, unsigned int __user *, u_msg_prio, const struct __kernel_timespec __user *, u_abs_timeout)
___SYSCALL2(184, mq_notify, mqd_t, mqdes, const struct sigevent __user *, u_notification)
___SYSCALL3(185, mq_getsetattr, mqd_t, mqdes, const struct mq_attr __user *, u_mqstat, struct mq_attr __user *, u_omqstat)
___SYSCALL2(186, msgget, key_t, key, int, msgflg)
___SYSCALL3(187, msgctl, int, msqid, int, cmd, struct msqid_ds __user *, buf)
___SYSCALL5(188, msgrcv, int, msqid, struct msgbuf __user *, msgp, size_t, msgsz, long, msgtyp, int, msgflg)
___SYSCALL4(189, msgsnd, int, msqid, struct msgbuf __user *, msgp, size_t, msgsz, int, msgflg)
___SYSCALL3(190, semget, key_t, key, int, nsems, int, semflg)
___SYSCALL4(191, semctl, int, semid, int, semnum, int, cmd, unsigned long, arg)
___SYSCALL4(192, semtimedop, int, semid, struct sembuf __user *, tsops, unsigned int, nsops, const struct __kernel_timespec __user *, timeout)
___SYSCALL3(193, semop, int, semid, struct sembuf __user *, tsops, unsigned, nsops)
___SYSCALL3(194, shmget, key_t, key, size_t, size, int, shmflg)
___SYSCALL3(195, shmctl, int, shmid, int, cmd, struct shmid_ds __user *, buf)
___SYSCALL3(196, shmat, int, shmid, char __user *, shmaddr, int, shmflg)
___SYSCALL1(197, shmdt, char __user *, shmaddr)
___SYSCALL3(198, socket, int, family, int, type, int, protocol)
___SYSCALL4(199, socketpair, int, family, int, type, int, protocol, int __user *, usockvec)
___SYSCALL3(200, bind, int, fd, struct sockaddr __user *, umyaddr, int, addrlen)
___SYSCALL2(201, listen, int, fd, int, backlog)
___SYSCALL3(202, accept, int, fd, struct sockaddr __user *, upeer_sockaddr, int __user *, upeer_addrlen)
___SYSCALL3(203, connect, int, fd, struct sockaddr __user *, uservaddr, int, addrlen)
___SYSCALL3(204, getsockname, int, fd, struct sockaddr __user *, usockaddr, int __user *, usockaddr_len)
___SYSCALL3(205, getpeername, int, fd, struct sockaddr __user *, usockaddr, int __user *, usockaddr_len)
___SYSCALL6(206, sendto, int, fd, void __user *, buff, size_t, len, unsigned int, flags, struct sockaddr __user *, addr, int, addr_len)
___SYSCALL6(207, recvfrom, int, fd, void __user *, ubuf, size_t, size, unsigned int, flags, struct sockaddr __user *, addr, int __user *, addr_len)
___SYSCALL5(208, setsockopt, int, fd, int, level, int, optname, char __user *, optval, int, optlen)
___SYSCALL5(209, getsockopt, int, fd, int, level, int, optname, char __user *, optval, int __user *, optlen)
___SYSCALL2(210, shutdown, int, fd, int, how)
___SYSCALL3(211, sendmsg, int, fd, struct user_msghdr __user *, msg, unsigned int, flags)
___SYSCALL3(212, recvmsg, int, fd, struct user_msghdr __user *, msg, unsigned int, flags)
___SYSCALL3(213, readahead, int, fd, loff_t, offset, size_t, count)
___SYSCALL1(214, brk, unsigned long, brk)
___SYSCALL2(215, munmap, unsigned long, addr, size_t, len)
___SYSCALL5(216, mremap, unsigned long, addr, unsigned long, old_len, unsigned long, new_len, unsigned long, flags, unsigned long, new_addr)
___SYSCALL5(217, add_key, const char __user *, _type, const char __user *, _description, const void __user *, _payload, size_t, plen, key_serial_t, ringid)
___SYSCALL4(218, request_key, const char __user *, _type, const char __user *, _description, const char __user *, _callout_info, key_serial_t, destringid)
___SYSCALL5(219, keyctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
___SYSCALL5(220, clone, unsigned long, clone_flags, unsigned long, newsp, int __user *, parent_tidptr, unsigned long, tls, int __user *, child_tidptr)
___SYSCALL3(221, execve, const char __user *, filename, const char __user *const __user *, argv, const char __user *const __user *, envp)
___SYSCALL6(222, mmap, unsigned long, addr, unsigned long, len, unsigned long, prot, unsigned long, flags, unsigned long, fd, unsigned long, off)
___SYSCALL4(223, fadvise64_64, int, fd, loff_t, offset, loff_t, len, int, advice)
___SYSCALL2(224, swapon, const char __user *, specialfile, int, swap_flags)
___SYSCALL1(225, swapoff, const char __user *, specialfile)
___SYSCALL3(226, mprotect, unsigned long, start, size_t, len, unsigned long, prot)
___SYSCALL3(227, msync, unsigned long, start, size_t, len, int, flags)
___SYSCALL2(228, mlock, unsigned long, start, size_t, len)
___SYSCALL2(229, munlock, unsigned long, start, size_t, len)
___SYSCALL1(230, mlockall, int, flags)
___SYSCALL0(231, munlockall)
___SYSCALL3(232, mincore, unsigned long, start, size_t, len, unsigned char __user *, vec)
___SYSCALL3(233, madvise, unsigned long, start, size_t, len_in, int, behavior)
___SYSCALL5(234, remap_file_pages, unsigned long, start, unsigned long, size, unsigned long, prot, unsigned long, pgoff, unsigned long, flags)
___SYSCALL6(235, mbind, unsigned long, start, unsigned long, len, unsigned long, mode, const unsigned long __user *, nmask, unsigned long, maxnode, unsigned int, flags)
___SYSCALL5(236, get_mempolicy, int __user *, policy, unsigned long __user *, nmask, unsigned long, maxnode, unsigned long, addr, unsigned long, flags)
___SYSCALL3(237, set_mempolicy, int, mode, const unsigned long __user *, nmask, unsigned long, maxnode)
___SYSCALL4(238, migrate_pages, pid_t, pid, unsigned long, maxnode, const unsigned long __user *, old_nodes, const unsigned long __user *, new_nodes)
___SYSCALL6(239, move_pages, pid_t, pid, unsigned long, nr_pages, const void __user * __user *, pages, const int __user *, nodes, int __user *, status, int, flags)
___SYSCALL4(240, rt_tgsigqueueinfo, pid_t, tgid, pid_t, pid, int, sig, siginfo_t __user *, uinfo)
___SYSCALL5(241, perf_event_open, struct perf_event_attr __user *, attr_uptr, pid_t, pid, int, cpu, int, group_fd, unsigned long, flags)
___SYSCALL4(242, accept4, int, fd, struct sockaddr __user *, upeer_sockaddr, int __user *, upeer_addrlen, int, flags)
___SYSCALL5(243, recvmmsg, int, fd, struct mmsghdr __user *, mmsg, unsigned int, vlen, unsigned int, flags, struct __kernel_timespec __user *, timeout)
___SYSCALL4(260, wait4, pid_t, upid, int __user *, stat_addr, int, options, struct rusage __user *, ru)
___SYSCALL4(261, prlimit64, pid_t, pid, unsigned int, resource, const struct rlimit64 __user *, new_rlim, struct rlimit64 __user *, old_rlim)
___SYSCALL2(262, fanotify_init, unsigned int, flags, unsigned int, event_f_flags)
___SYSCALL5(263, fanotify_mark, int, fanotify_fd, unsigned int, flags, __u64, mask, int, dfd, const char  __user *, pathname)
___SYSCALL5(264, name_to_handle_at, int, dfd, const char __user *, name, struct file_handle __user *, handle, int __user *, mnt_id, int, flag)
___SYSCALL3(265, open_by_handle_at, int, mountdirfd, struct file_handle __user *, handle, int, flags)
___SYSCALL2(266, clock_adjtime, const clockid_t, which_clock, struct __kernel_timex __user *, utx)
___SYSCALL1(267, syncfs, int, fd)
___SYSCALL2(268, setns, int, fd, int, nstype)
___SYSCALL4(269, sendmmsg, int, fd, struct mmsghdr __user *, mmsg, unsigned int, vlen, unsigned int, flags)
___SYSCALL6(270, process_vm_readv, pid_t, pid, const struct iovec __user *, lvec, unsigned long, liovcnt, const struct iovec __user *, rvec, unsigned long, riovcnt, unsigned long, flags)
___SYSCALL6(271, process_vm_writev, pid_t, pid, const struct iovec __user *, lvec, unsigned long, liovcnt, const struct iovec __user *, rvec, unsigned long, riovcnt, unsigned long, flags)
___SYSCALL5(272, kcmp, pid_t, pid1, pid_t, pid2, int, type, unsigned long, idx1, unsigned long, idx2)
___SYSCALL3(273, finit_module, int, fd, const char __user *, uargs, int, flags)
___SYSCALL3(274, sched_setattr, pid_t, pid, struct sched_attr __user *, uattr, unsigned int, flags)
___SYSCALL4(275, sched_getattr, pid_t, pid, struct sched_attr __user *, uattr, unsigned int, usize, unsigned int, flags)
___SYSCALL5(276, renameat2, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname, unsigned int, flags)
___SYSCALL3(277, seccomp, unsigned int, op, unsigned int, flags, void __user *, uargs)
___SYSCALL3(278, getrandom, char __user *, buf, size_t, count, unsigned int, flags)
___SYSCALL2(279, memfd_create, const char __user *, uname, unsigned int, flags)
___SYSCALL3(280, bpf, int, cmd, union bpf_attr __user *, uattr, unsigned int, size)
___SYSCALL5(281, execveat, int, fd, const char __user *, filename, const char __user *const __user *, argv, const char __user *const __user *, envp, int, flags)
___SYSCALL1(282, userfaultfd, int, flags)
___SYSCALL2(283, membarrier, int, cmd, int, flags)
___SYSCALL3(284, mlock2, unsigned long, start, size_t, len, int, flags)
___SYSCALL6(285, copy_file_range, int, fd_in, loff_t __user *, off_in, int, fd_out, loff_t __user *, off_out, size_t, len, unsigned int, flags)
___SYSCALL6(286, preadv2, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, rwf_t, flags)
___SYSCALL6(287, pwritev2, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, rwf_t, flags)
___SYSCALL4(288, pkey_mprotect, unsigned long, start, size_t, len, unsigned long, prot, int, pkey)
___SYSCALL2(289, pkey_alloc, unsigned long, flags, unsigned long, init_val)
___SYSCALL1(290, pkey_free, int, pkey)
___SYSCALL5(291, statx, int, dfd, const char __user *, filename, unsigned, flags, unsigned int, mask, struct statx __user *, buffer)
___SYSCALL6(292, io_pgetevents, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event __user *, events, struct __kernel_timespec __user *, timeout, const struct __aio_sigset __user *, usig)
___SYSCALL4(293, rseq, struct rseq __user *, rseq, u32, rseq_len, int, flags, u32, sig)
___SYSCALL5(294, kexec_file_load, int, kernel_fd, int, initrd_fd, unsigned long, cmdline_len, const char __user *, cmdline_ptr, unsigned long, flags)
___SYSCALL4(424, pidfd_send_signal, int, pidfd, int, sig, siginfo_t __user *, info, unsigned int, flags)
___SYSCALL2(425, io_uring_setup, u32, entries, struct io_uring_params __user *, params)
___SYSCALL6(426, io_uring_enter, unsigned int, fd, u32, to_submit, u32, min_complete, u32, flags, const sigset_t __user *, sig, size_t, sigsz)
___SYSCALL4(427, io_uring_register, unsigned int, fd, unsigned int, opcode, void __user *, arg, unsigned int, nr_args)
___SYSCALL3(428, open_tree, int, dfd, const char *, filename, unsigned, flags)
___SYSCALL5(429, move_mount, int, from_dfd, const char *, from_pathname, int, to_dfd, const char *, to_pathname, unsigned int, flags)
___SYSCALL2(430, fsopen, const char __user *, _fs_name, unsigned int, flags)
___SYSCALL5(431, fsconfig, int, fd, unsigned int, cmd, const char __user *, _key, const void __user *, _value, int, aux)
___SYSCALL3(432, fsmount, int, fs_fd, unsigned int, flags, unsigned int, attr_flags)
___SYSCALL3(433, fspick, int, dfd, const char __user *, path, unsigned int, flags)
___SYSCALL2(434, pidfd_open, pid_t, pid, unsigned int, flags)
___SYSCALL2(435, clone3, struct clone_args __user *, uargs, size_t, size)


#include "syscalls.inc.macros_end.h"
