___HOOK1(POST, void *, malloc, target_ulong)
___HOOK2(POST, void *, calloc, target_ulong, target_ulong)
___HOOK2(POST, char *, strchr, const char *, target_ulong)
___HOOK2(POST, void *, realloc, void *, target_ulong)
___HOOK3(POST, void *, memcpy, void *, const void *, target_ulong)
___HOOK3(POST, void *, memset, void *, target_ulong, target_ulong)
