___HOOK1(POST, void *, malloc, target_ulong)
___HOOK2(POST, void *, calloc, target_ulong, target_ulong)
___HOOK2(POST, char *, strchr, const char *, int)
___HOOK2(POST, char *, strrchr, const char *, int)
___HOOK2(POST, void *, realloc, void *, target_ulong)
___HOOK3(POST, void *, memcpy, void *, const void *, target_ulong)
___HOOK3(POST, void *, memset, void *, target_ulong, target_ulong)
___HOOK3(POST, char *, strncpy, char *, const char *, size_t)
___HOOK2(POST, char *, strcpy, char *, const char *)
___HOOK3(POST, char *, strlcpy, char *, const char *, size_t)
___HOOK2(POST, char *, strstr, const char *, const char *)
___HOOK3(POST, ssize_t, read, int, void *, size_t)
___HOOK3(POST, ssize_t, write, int, const void *, size_t)
___HOOK4(POST, ssize_t, recv, int, void *, size_t, int)
___HOOK6(POST, ssize_t, recvfrom, int, void *, size_t, int, struct sockaddr *, socklen_t *)
___HOOK4(POST, size_t, fread, void *, size_t, size_t, FILE *)
___HOOK4(POST, size_t, fwrite, const void *, size_t, size_t, FILE *)
___HOOK6(POST, void *, mmap, void *, size_t, int, int, int, off_t)
