___HOOK1(POST, void *, malloc, size_t)
___HOOK2(POST, void *, calloc, size_t, size_t)
___HOOK2(POST, char *, strchr, const char *, int)
___HOOK2(POST, void *, realloc, void *, size_t)
___HOOK3(POST, void *, memcpy, void *, const void *, size_t)
___HOOK3(POST, void *, memset, void *, int, size_t)
