#pragma once

#define _JOVE_MAX_BINARIES 512

#define JOVE_PAGE_SIZE 4096
#define JOVE_STACK_SIZE (8 * 512 * JOVE_PAGE_SIZE)

#define JOVE_CALLSTACK_SIZE (16 * JOVE_PAGE_SIZE)
#define JOVE_TRACE_BUFF_SIZE (8 * JOVE_PAGE_SIZE)

#define JOVE_MAX_PROC_MAPS (4 * 512 * JOVE_PAGE_SIZE)
#define JOVE_MAX_ENVIRON JOVE_MAX_PROC_MAPS
#define JOVE_LARGE_BUFF_SIZE JOVE_STACK_SIZE

#define JOVE_FUNCTION_MAP_HASH_BITS 15

#define JOVE_INVALID_BINARY_INDEX 0xffffffff
#define JOVE_INVALID_BASIC_BLOCK_INDEX 0xffffffff
