#pragma once

#define _JOVE_MAX_BINARIES 512

#define JOVE_PAGE_SIZE 4096
#define JOVE_STACK_SIZE (8 * 512 * JOVE_PAGE_SIZE)

#define JOVE_CALLSTACK_SIZE (32 * JOVE_PAGE_SIZE)
#define JOVE_TRACE_BUFF_SIZE (8 * JOVE_PAGE_SIZE)

#define JOVE_MAX_PROC_MAPS (4 * 512 * JOVE_PAGE_SIZE)
#define JOVE_LARGE_BUFF_SIZE JOVE_STACK_SIZE

#define JOVE_FUNCTION_MAP_HASH_BITS 15
