#include "syscalls.inc.macros_begin.h"

___SYSCALL3(2, open, const char __user *, filename, int, flags, mode_t, mode)
___SYSCALL2(4, newstat, const char __user *, filename, struct stat __user *, statbuf)
___SYSCALL2(6, newlstat, const char __user *, filename, struct stat __user *, statbuf)
___SYSCALL3(7, poll, struct pollfd __user *, ufds, unsigned int, nfds, int, timeout_msecs)
___SYSCALL2(20, access, const char __user *, filename, int, mode)
___SYSCALL0(21, sysm_pipe)
___SYSCALL5(22, select, int, n, fd_set __user *, inp, fd_set __user *, outp, fd_set __user *, exp, struct timeval __user *, tvp)
___SYSCALL3(30, old_shmctl, int, shmid, int, cmd, struct shmid_ds __user *, buf)
___SYSCALL2(32, dup2, unsigned int, oldfd, unsigned int, newfd)
___SYSCALL0(33, pause)
___SYSCALL1(37, alarm, unsigned int, seconds)
___SYSCALL0(56, fork)
___SYSCALL4(64, old_semctl, int, semid, int, semnum, int, cmd, unsigned long, arg)
___SYSCALL3(69, old_msgctl, int, msqid, int, cmd, struct msqid_ds __user *, buf)
___SYSCALL3(76, getdents, unsigned int, fd, struct linux_dirent __user *, dirent, unsigned int, count)
___SYSCALL2(80, rename, const char __user *, oldname, const char __user *, newname)
___SYSCALL2(81, mkdir, const char __user *, pathname, mode_t, mode)
___SYSCALL1(82, rmdir, const char __user *, pathname)
___SYSCALL2(83, creat, const char __user *, pathname, mode_t, mode)
___SYSCALL2(84, link, const char __user *, oldname, const char __user *, newname)
___SYSCALL1(85, unlink, const char __user *, pathname)
___SYSCALL2(86, symlink, const char __user *, oldname, const char __user *, newname)
___SYSCALL3(87, readlink, const char __user *, path, char __user *, buf, int, bufsiz)
___SYSCALL2(88, chmod, const char __user *, filename, mode_t, mode)
___SYSCALL3(90, chown, const char __user *, filename, uid_t, user, gid_t, group)
___SYSCALL3(92, lchown, const char __user *, filename, uid_t, user, gid_t, group)
___SYSCALL0(109, getpgrp)
___SYSCALL2(130, utime, char __user *, filename, struct utimbuf __user *, times)
___SYSCALL3(131, mknod, const char __user *, filename, mode_t, mode, unsigned, dev)
___SYSCALL1(132, personality, unsigned int, personality)
___SYSCALL2(133, ustat, unsigned, dev, struct ustat __user *, ubuf)
___SYSCALL3(136, sysfs, int, option, unsigned long, arg1, unsigned long, arg2)
___SYSCALL1(152, sysctl, struct __sysctl_args __user *, args)
___SYSCALL3(197, cacheflush, unsigned long, addr, unsigned long, bytes, unsigned int, cache)
___SYSCALL3(198, cachectl, char *, addr, int, nbytes, int, op)
___SYSCALL3(199, sysmips, long, cmd, long, arg1, long, arg2)
___SYSCALL1(207, epoll_create, int, size)
___SYSCALL4(209, epoll_wait, int, epfd, struct epoll_event __user *, events, int, maxevents, int, timeout)
___SYSCALL2(226, utimes, char __user *, filename, struct timeval __user *, utimes)
___SYSCALL1(242, set_thread_area, unsigned long, addr)
___SYSCALL0(243, inotify_init)
___SYSCALL3(251, futimesat, int, dfd, const char __user *, filename, struct timeval __user *, utimes)
___SYSCALL3(276, signalfd, int, ufd, sigset_t __user *, user_mask, size_t, sizemask)
___SYSCALL1(278, eventfd, unsigned int, count)
___SYSCALL4(437, openat2, int, dfd, const char __user *, filename, struct open_how __user *, how, size_t, usize)
___SYSCALL3(438, pidfd_getfd, int, pidfd, int, fd, unsigned int, flags)

___SYSCALL2(200, io_setup, unsigned, nr_events, aio_context_t __user *, ctxp)
___SYSCALL1(201, io_destroy, aio_context_t, ctx)
___SYSCALL3(203, io_submit, aio_context_t, ctx_id, long, nr, struct iocb __user * __user *, iocbpp)
___SYSCALL3(204, io_cancel, aio_context_t, ctx_id, struct iocb __user *, iocb, struct io_event __user *, result)
___SYSCALL5(202, io_getevents, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event __user *, events, struct __kernel_timespec __user *, timeout)
___SYSCALL5(180, setxattr, const char __user *, pathname, const char __user *, name, const void __user *, value, size_t, size, int, flags)
___SYSCALL5(181, lsetxattr, const char __user *, pathname, const char __user *, name, const void __user *, value, size_t, size, int, flags)
___SYSCALL5(182, fsetxattr, int, fd, const char __user *, name, const void __user *,value, size_t, size, int, flags)
___SYSCALL4(183, getxattr, const char __user *, pathname, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL4(184, lgetxattr, const char __user *, pathname, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL4(185, fgetxattr, int, fd, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL3(186, listxattr, const char __user *, pathname, char __user *, list, size_t, size)
___SYSCALL3(187, llistxattr, const char __user *, pathname, char __user *, list, size_t, size)
___SYSCALL3(188, flistxattr, int, fd, char __user *, list, size_t, size)
___SYSCALL2(189, removexattr, const char __user *, pathname, const char __user *, name)
___SYSCALL2(190, lremovexattr, const char __user *, pathname, const char __user *, name)
___SYSCALL2(191, fremovexattr, int, fd, const char __user *, name)
___SYSCALL2(77, getcwd, char __user *, buf, unsigned long, size)
___SYSCALL3(206, lookup_dcookie, uint64_t, cookie64, char __user *, buf, size_t, len)
___SYSCALL2(284, eventfd2, unsigned int, count, int, flags)
___SYSCALL1(285, epoll_create1, int, flags)
___SYSCALL4(208, epoll_ctl, int, epfd, int, op, int, fd, struct epoll_event __user *, event)
___SYSCALL6(272, epoll_pwait, int, epfd, struct epoll_event __user *, events, int, maxevents, int, timeout, const sigset_t __user *, sigmask, size_t, sigsetsize)
___SYSCALL1(31, dup, unsigned int, fildes)
___SYSCALL3(286, dup3, unsigned int, oldfd, unsigned int, newfd, int, flags)
___SYSCALL3(70, fcntl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL1(288, inotify_init1, int, flags)
___SYSCALL3(244, inotify_add_watch, int, fd, const char __user *, pathname, uint32_t, mask)
___SYSCALL2(245, inotify_rm_watch, int, fd, __s32, wd)
___SYSCALL3(15, ioctl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL3(273, ioprio_set, int, which, int, who, int, ioprio)
___SYSCALL2(274, ioprio_get, int, which, int, who)
___SYSCALL2(71, flock, unsigned int, fd, unsigned int, cmd)
___SYSCALL4(249, mknodat, int, dfd, const char __user *, filename, mode_t, mode, unsigned int, dev)
___SYSCALL3(248, mkdirat, int, dfd, const char __user *, pathname, mode_t, mode)
___SYSCALL3(253, unlinkat, int, dfd, const char __user *, pathname, int, flag)
___SYSCALL3(256, symlinkat, const char __user *, oldname, int, newdfd, const char __user *, newname)
___SYSCALL5(255, linkat, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname, int, flags)
___SYSCALL4(254, renameat, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname)
___SYSCALL2(161, umount, char __user *, name, int, flags)
___SYSCALL5(160, mount, char __user *, dev_name, char __user *, dir_name, char __user *, type, unsigned long, flags, void __user *, data)
___SYSCALL2(151, pivot_root, const char __user *, new_root, const char __user *, put_old)
___SYSCALL2(134, statfs, const char __user *, pathname, struct statfs __user *, buf)
___SYSCALL2(135, fstatfs, unsigned int, fd, struct statfs __user *, buf)
___SYSCALL2(74, truncate, const char __user *, path, long, length)
___SYSCALL2(75, ftruncate, unsigned int, fd, unsigned long, length)
___SYSCALL4(279, fallocate, int, fd, int, mode, loff_t, offset, loff_t, len)
___SYSCALL3(259, faccessat, int, dfd, const char __user *, filename, int, mode)
___SYSCALL1(78, chdir, const char __user *, filename)
___SYSCALL1(79, fchdir, unsigned int, fd)
___SYSCALL1(156, chroot, const char __user *, filename)
___SYSCALL2(89, fchmod, unsigned int, fd, mode_t, mode)
___SYSCALL3(258, fchmodat, int, dfd, const char __user *, filename, mode_t, mode)
___SYSCALL5(250, fchownat, int, dfd, const char __user *, filename, uid_t, user, gid_t, group, int, flag)
___SYSCALL3(91, fchown, unsigned int, fd, uid_t, user, gid_t, group)
___SYSCALL4(247, openat, int, dfd, const char __user *, filename, int, flags, mode_t, mode)
___SYSCALL1(3, close, unsigned int, fd)
___SYSCALL0(150, vhangup)
___SYSCALL2(287, pipe2, int __user *, fildes, int, flags)
___SYSCALL4(172, quotactl, unsigned int, cmd, const char __user *, special, int, id, void __user *, addr)
___SYSCALL3(308, getdents64, unsigned int, fd, struct linux_dirent64 __user *, dirent, unsigned int, count)
___SYSCALL3(8, lseek, unsigned int, fd, off_t, offset, unsigned int, whence)
___SYSCALL3(0, read, unsigned int, fd, char __user *, buf, size_t, count)
___SYSCALL3(1, write, unsigned int, fd, const char __user *, buf, size_t, count)
___SYSCALL3(18, readv, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen)
___SYSCALL3(19, writev, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen)
___SYSCALL4(16, pread64, unsigned int, fd, char __user *, buf, size_t, count, loff_t, pos)
___SYSCALL4(17, pwrite64, unsigned int, fd, const char __user *, buf, size_t, count, loff_t, pos)
___SYSCALL5(289, preadv, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
___SYSCALL5(290, pwritev, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
___SYSCALL4(39, sendfile64, int, out_fd, int, in_fd, loff_t __user *, offset, size_t, count)
___SYSCALL6(260, pselect6, int, n, fd_set __user *, inp, fd_set __user *, outp, fd_set __user *, exp, struct __kernel_timespec __user *, tsp, void __user *, sig)
___SYSCALL5(261, ppoll, struct pollfd __user *, ufds, unsigned int, nfds, struct __kernel_timespec __user *, tsp, const sigset_t __user *, sigmask, size_t, sigsetsize)
___SYSCALL4(283, signalfd4, int, ufd, sigset_t __user *, user_mask, size_t, sizemask, int, flags)
___SYSCALL4(266, vmsplice, int, fd, const struct iovec __user *, uiov, unsigned long, nr_segs, unsigned int, flags)
___SYSCALL6(263, splice, int, fd_in, loff_t __user *, off_in, int, fd_out, loff_t __user *, off_out, size_t, len, unsigned int, flags)
___SYSCALL4(265, tee, int, fdin, int, fdout, size_t, len, unsigned int, flags)
___SYSCALL4(257, readlinkat, int, dfd, const char __user *, pathname, char __user *, buf, int, bufsiz)
___SYSCALL4(252, newfstatat, int, dfd, const char __user *, filename, struct stat __user *, statbuf, int, flag)
___SYSCALL2(5, newfstat, unsigned int, fd, struct stat __user *, statbuf)
___SYSCALL0(157, sync)
___SYSCALL1(72, fsync, unsigned int, fd)
___SYSCALL1(73, fdatasync, unsigned int, fd)
___SYSCALL4(264, sync_file_range, int, fd, loff_t, offset, loff_t, nbytes, unsigned int, flags)
___SYSCALL2(280, timerfd_create, int, clockid, int, flags)
___SYSCALL4(282, timerfd_settime, int, ufd, int, flags, const struct __kernel_itimerspec __user *, utmr, struct __kernel_itimerspec __user *, otmr)
___SYSCALL2(281, timerfd_gettime, int, ufd, struct __kernel_itimerspec __user *, otmr)
___SYSCALL4(275, utimensat, int, dfd, const char __user *, filename, struct __kernel_timespec __user *, utimes, int, flags)
___SYSCALL1(158, acct, const char __user *, name)
___SYSCALL2(123, capget, cap_user_header_t, header, cap_user_data_t, dataptr)
___SYSCALL2(124, capset, cap_user_header_t, header, const cap_user_data_t, data)
___SYSCALL1(58, exit, int, error_code)
___SYSCALL1(205, exit_group, int, error_code)
___SYSCALL5(237, waitid, int, which, pid_t, upid, struct siginfo __user *, infop, int, options, struct rusage __user *, ru)
___SYSCALL1(212, set_tid_address, int __user *, tidptr)
___SYSCALL1(262, unshare, unsigned long, unshare_flags)
___SYSCALL6(194, futex, uint32_t __user *, uaddr, int, op, uint32_t, val, struct __kernel_timespec __user *, utime, uint32_t __user *, uaddr2, uint32_t, val3)
___SYSCALL2(268, set_robust_list, struct robust_list_head __user *, head, size_t, len)
___SYSCALL3(269, get_robust_list, int, pid, struct robust_list_head __user * __user *, head_ptr, size_t __user *, len_ptr)
___SYSCALL2(34, nanosleep, struct __kernel_timespec __user *, rqtp, struct __kernel_timespec __user *, rmtp)
___SYSCALL2(35, getitimer, int, which, struct itimerval __user *, value)
___SYSCALL3(36, setitimer, int, which, struct itimerval __user *, value, struct itimerval __user *, ovalue)
___SYSCALL4(270, kexec_load, unsigned long, entry, unsigned long, nr_segments, struct kexec_segment __user *, segments, unsigned long, flags)
___SYSCALL3(168, init_module, void __user *, umod, unsigned long, len, const char __user *, uargs)
___SYSCALL2(169, delete_module, const char __user *, name_user, unsigned int, flags)
___SYSCALL3(216, timer_create, const clockid_t, which_clock, struct sigevent __user *, timer_event_spec, timer_t __user *, created_timer_id)
___SYSCALL2(218, timer_gettime, timer_t, timer_id, struct __kernel_itimerspec __user *, setting)
___SYSCALL1(219, timer_getoverrun, timer_t, timer_id)
___SYSCALL4(217, timer_settime, timer_t, timer_id, int, flags, const struct __kernel_itimerspec __user *, new_setting, struct __kernel_itimerspec __user *, old_setting)
___SYSCALL1(220, timer_delete, timer_t, timer_id)
___SYSCALL2(221, clock_settime, const clockid_t, which_clock, const struct __kernel_timespec __user *, tp)
___SYSCALL2(222, clock_gettime, const clockid_t, which_clock, struct __kernel_timespec __user *, tp)
___SYSCALL2(223, clock_getres, const clockid_t, which_clock, struct __kernel_timespec __user *, tp)
___SYSCALL4(224, clock_nanosleep, const clockid_t, which_clock, int, flags, const struct __kernel_timespec __user *, rqtp, struct __kernel_timespec __user *, rmtp)
___SYSCALL3(101, syslog, int, type, char __user *, buf, int, len)
___SYSCALL4(99, ptrace, long, request, long, pid, unsigned long, addr, unsigned long, data)
___SYSCALL2(139, sched_setparam, pid_t, pid, struct sched_param __user *, param)
___SYSCALL3(141, sched_setscheduler, pid_t, pid, int, policy, struct sched_param __user *, param)
___SYSCALL1(142, sched_getscheduler, pid_t, pid)
___SYSCALL2(140, sched_getparam, pid_t, pid, struct sched_param __user *, param)
___SYSCALL3(195, sched_setaffinity, pid_t, pid, unsigned int, len, unsigned long __user *, user_mask_ptr)
___SYSCALL3(196, sched_getaffinity, pid_t, pid, unsigned int, len, unsigned long __user *, user_mask_ptr)
___SYSCALL0(23, sched_yield)
___SYSCALL1(143, sched_get_priority_max, int, policy)
___SYSCALL1(144, sched_get_priority_min, int, policy)
___SYSCALL2(145, sched_rr_get_interval, pid_t, pid, struct __kernel_timespec __user *, interval)
___SYSCALL0(213, restart_syscall)
___SYSCALL2(60, kill, pid_t, pid, int, sig)
___SYSCALL2(192, tkill, pid_t, pid, int, sig)
___SYSCALL3(225, tgkill, pid_t, tgid, pid_t, pid, int, sig)
___SYSCALL2(129, sigaltstack, const stack_t __user *,uss, stack_t __user *,uoss)
___SYSCALL2(128, rt_sigsuspend, sigset_t __user *, unewset, size_t, sigsetsize)
___SYSCALL4(13, rt_sigaction, int, sig, const struct sigaction __user *, act, struct sigaction __user *, oact, size_t, sigsetsize)
___SYSCALL4(14, rt_sigprocmask, int, how, sigset_t __user *, nset, sigset_t __user *, oset, size_t, sigsetsize)
___SYSCALL2(125, rt_sigpending, sigset_t __user *, uset, size_t, sigsetsize)
___SYSCALL4(126, rt_sigtimedwait, const sigset_t __user *, uthese, siginfo_t __user *, uinfo, const struct __kernel_timespec __user *, uts, size_t, sigsetsize)
___SYSCALL3(127, rt_sigqueueinfo, pid_t, pid, int, sig, siginfo_t __user *, uinfo)
___SYSCALL0(211, rt_sigreturn)
___SYSCALL3(138, setpriority, int, which, int, who, int, niceval)
___SYSCALL2(137, getpriority, int, which, int, who)
___SYSCALL4(164, reboot, int, magic1, int, magic2, unsigned int, cmd, void __user *, arg)
___SYSCALL2(112, setregid, gid_t, rgid, gid_t, egid)
___SYSCALL1(104, setgid, gid_t, gid)
___SYSCALL2(111, setreuid, uid_t, ruid, uid_t, euid)
___SYSCALL1(103, setuid, uid_t, uid)
___SYSCALL3(115, setresuid, uid_t, ruid, uid_t, euid, uid_t, suid)
___SYSCALL3(116, getresuid, uid_t __user *, ruidp, uid_t __user *, euidp, uid_t __user *, suidp)
___SYSCALL3(117, setresgid, gid_t, rgid, gid_t, egid, gid_t, sgid)
___SYSCALL3(118, getresgid, gid_t __user *, rgidp, gid_t __user *, egidp, gid_t __user *, sgidp)
___SYSCALL1(120, setfsuid, uid_t, uid)
___SYSCALL1(121, setfsgid, gid_t, gid)
___SYSCALL1(98, times, struct tms __user *, tbuf)
___SYSCALL2(107, setpgid, pid_t, pid, pid_t, pgid)
___SYSCALL1(119, getpgid, pid_t, pid)
___SYSCALL1(122, getsid, pid_t, pid)
___SYSCALL0(110, setsid)
___SYSCALL2(113, getgroups, int, gidsetsize, gid_t __user *, grouplist)
___SYSCALL2(114, setgroups, int, gidsetsize, gid_t __user *, grouplist)
___SYSCALL1(61, newuname, struct new_utsname __user *, name)
___SYSCALL2(165, sethostname, char __user *, name, int, len)
___SYSCALL2(166, setdomainname, char __user *, name, int, len)
___SYSCALL2(95, getrlimit, unsigned int, resource, struct rlimit __user *, rlim)
___SYSCALL2(155, setrlimit, unsigned int, resource, struct rlimit __user *, rlim)
___SYSCALL2(96, getrusage, int, who, struct rusage __user *, ru)
___SYSCALL1(93, umask, int, mask)
___SYSCALL5(153, prctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
___SYSCALL3(271, getcpu, unsigned __user *, cpup, unsigned __user *, nodep, struct getcpu_cache __user *, unused)
___SYSCALL2(94, gettimeofday, struct timeval __user *, tv, struct timezone __user *, tz)
___SYSCALL2(159, settimeofday, struct timeval __user *, tv, struct timezone __user *, tz)
___SYSCALL1(154, adjtimex, struct __kernel_timex __user *, txc_p)
___SYSCALL0(38, getpid)
___SYSCALL0(108, getppid)
___SYSCALL0(100, getuid)
___SYSCALL0(105, geteuid)
___SYSCALL0(102, getgid)
___SYSCALL0(106, getegid)
___SYSCALL0(178, gettid)
___SYSCALL1(97, sysinfo, struct sysinfo __user *, info)
___SYSCALL4(230, mq_open, const char __user *, u_name, int, oflag, mode_t, mode, struct mq_attr __user *, u_attr)
___SYSCALL1(231, mq_unlink, const char __user *, u_name)
___SYSCALL5(232, mq_timedsend, mqd_t, mqdes, const char __user *, u_msg_ptr, size_t, msg_len, unsigned int, msg_prio, const struct __kernel_timespec __user *, u_abs_timeout)
___SYSCALL5(233, mq_timedreceive, mqd_t, mqdes, char __user *, u_msg_ptr, size_t, msg_len, unsigned int __user *, u_msg_prio, const struct __kernel_timespec __user *, u_abs_timeout)
___SYSCALL2(234, mq_notify, mqd_t, mqdes, const struct sigevent __user *, u_notification)
___SYSCALL3(235, mq_getsetattr, mqd_t, mqdes, const struct mq_attr __user *, u_mqstat, struct mq_attr __user *, u_omqstat)
___SYSCALL2(66, msgget, key_t, key, int, msgflg)
___SYSCALL5(68, msgrcv, int, msqid, struct msgbuf __user *, msgp, size_t, msgsz, long, msgtyp, int, msgflg)
___SYSCALL4(67, msgsnd, int, msqid, struct msgbuf __user *, msgp, size_t, msgsz, int, msgflg)
___SYSCALL3(62, semget, key_t, key, int, nsems, int, semflg)
___SYSCALL4(214, semtimedop, int, semid, struct sembuf __user *, tsops, unsigned int, nsops, const struct __kernel_timespec __user *, timeout)
___SYSCALL3(63, semop, int, semid, struct sembuf __user *, tsops, unsigned, nsops)
___SYSCALL3(28, shmget, key_t, key, size_t, size, int, shmflg)
___SYSCALL3(29, shmat, int, shmid, char __user *, shmaddr, int, shmflg)
___SYSCALL1(65, shmdt, char __user *, shmaddr)
___SYSCALL3(40, socket, int, family, int, type, int, protocol)
___SYSCALL4(52, socketpair, int, family, int, type, int, protocol, int __user *, usockvec)
___SYSCALL3(48, bind, int, fd, struct sockaddr __user *, umyaddr, int, addrlen)
___SYSCALL2(49, listen, int, fd, int, backlog)
___SYSCALL3(42, accept, int, fd, struct sockaddr __user *, upeer_sockaddr, int __user *, upeer_addrlen)
___SYSCALL3(41, connect, int, fd, struct sockaddr __user *, uservaddr, int, addrlen)
___SYSCALL3(50, getsockname, int, fd, struct sockaddr __user *, usockaddr, int __user *, usockaddr_len)
___SYSCALL3(51, getpeername, int, fd, struct sockaddr __user *, usockaddr, int __user *, usockaddr_len)
___SYSCALL6(43, sendto, int, fd, void __user *, buff, size_t, len, unsigned int, flags, struct sockaddr __user *, addr, int, addr_len)
___SYSCALL6(44, recvfrom, int, fd, void __user *, ubuf, size_t, size, unsigned int, flags, struct sockaddr __user *, addr, int __user *, addr_len)
___SYSCALL5(53, setsockopt, int, fd, int, level, int, optname, char __user *, optval, int, optlen)
___SYSCALL5(54, getsockopt, int, fd, int, level, int, optname, char __user *, optval, int __user *, optlen)
___SYSCALL2(47, shutdown, int, fd, int, how)
___SYSCALL3(45, sendmsg, int, fd, struct user_msghdr __user *, msg, unsigned int, flags)
___SYSCALL3(46, recvmsg, int, fd, struct user_msghdr __user *, msg, unsigned int, flags)
___SYSCALL3(179, readahead, int, fd, loff_t, offset, size_t, count)
___SYSCALL1(12, brk, unsigned long, brk)
___SYSCALL2(11, munmap, unsigned long, addr, size_t, len)
___SYSCALL5(24, mremap, unsigned long, addr, unsigned long, old_len, unsigned long, new_len, unsigned long, flags, unsigned long, new_addr)
___SYSCALL5(239, add_key, const char __user *, _type, const char __user *, _description, const void __user *, _payload, size_t, plen, key_serial_t, ringid)
___SYSCALL4(240, request_key, const char __user *, _type, const char __user *, _description, const char __user *, _callout_info, key_serial_t, destringid)
___SYSCALL5(241, keyctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
___SYSCALL5(55, clone, unsigned long, clone_flags, unsigned long, newsp, int __user *, parent_tidptr, unsigned long, tls, int __user *, child_tidptr)
___SYSCALL3(57, execve, const char __user *, filename, const char __user *const __user *, argv, const char __user *const __user *, envp)
___SYSCALL6(9, mmap, unsigned long, addr, unsigned long, len, unsigned long, prot, unsigned long, flags, unsigned long, fd, unsigned long, off)
___SYSCALL4(215, fadvise64_64, int, fd, loff_t, offset, loff_t, len, int, advice)
___SYSCALL2(162, swapon, const char __user *, specialfile, int, swap_flags)
___SYSCALL1(163, swapoff, const char __user *, specialfile)
___SYSCALL3(10, mprotect, unsigned long, start, size_t, len, unsigned long, prot)
___SYSCALL3(25, msync, unsigned long, start, size_t, len, int, flags)
___SYSCALL2(146, mlock, unsigned long, start, size_t, len)
___SYSCALL2(147, munlock, unsigned long, start, size_t, len)
___SYSCALL1(148, mlockall, int, flags)
___SYSCALL0(149, munlockall)
___SYSCALL3(26, mincore, unsigned long, start, size_t, len, unsigned char __user *, vec)
___SYSCALL3(27, madvise, unsigned long, start, size_t, len_in, int, behavior)
___SYSCALL5(210, remap_file_pages, unsigned long, start, unsigned long, size, unsigned long, prot, unsigned long, pgoff, unsigned long, flags)
___SYSCALL6(227, mbind, unsigned long, start, unsigned long, len, unsigned long, mode, const unsigned long __user *, nmask, unsigned long, maxnode, unsigned int, flags)
___SYSCALL5(228, get_mempolicy, int __user *, policy, unsigned long __user *, nmask, unsigned long, maxnode, unsigned long, addr, unsigned long, flags)
___SYSCALL3(229, set_mempolicy, int, mode, const unsigned long __user *, nmask, unsigned long, maxnode)
___SYSCALL4(246, migrate_pages, pid_t, pid, unsigned long, maxnode, const unsigned long __user *, old_nodes, const unsigned long __user *, new_nodes)
___SYSCALL6(267, move_pages, pid_t, pid, unsigned long, nr_pages, const void __user * __user *, pages, const int __user *, nodes, int __user *, status, int, flags)
___SYSCALL4(291, rt_tgsigqueueinfo, pid_t, tgid, pid_t, pid, int, sig, siginfo_t __user *, uinfo)
___SYSCALL5(292, perf_event_open, struct perf_event_attr __user *, attr_uptr, pid_t, pid, int, cpu, int, group_fd, unsigned long, flags)
___SYSCALL4(293, accept4, int, fd, struct sockaddr __user *, upeer_sockaddr, int __user *, upeer_addrlen, int, flags)
___SYSCALL5(294, recvmmsg, int, fd, struct mmsghdr __user *, mmsg, unsigned int, vlen, unsigned int, flags, struct __kernel_timespec __user *, timeout)
___SYSCALL4(59, wait4, pid_t, upid, int __user *, stat_addr, int, options, struct rusage __user *, ru)
___SYSCALL4(297, prlimit64, pid_t, pid, unsigned int, resource, const struct rlimit64 __user *, new_rlim, struct rlimit64 __user *, old_rlim)
___SYSCALL2(295, fanotify_init, unsigned int, flags, unsigned int, event_f_flags)
___SYSCALL5(296, fanotify_mark, int, fanotify_fd, unsigned int, flags, __u64, mask, int, dfd, const char  __user *, pathname)
___SYSCALL5(298, name_to_handle_at, int, dfd, const char __user *, name, struct file_handle __user *, handle, int __user *, mnt_id, int, flag)
___SYSCALL3(299, open_by_handle_at, int, mountdirfd, struct file_handle __user *, handle, int, flags)
___SYSCALL2(300, clock_adjtime, const clockid_t, which_clock, struct __kernel_timex __user *, utx)
___SYSCALL1(301, syncfs, int, fd)
___SYSCALL2(303, setns, int, fd, int, nstype)
___SYSCALL4(302, sendmmsg, int, fd, struct mmsghdr __user *, mmsg, unsigned int, vlen, unsigned int, flags)
___SYSCALL6(304, process_vm_readv, pid_t, pid, const struct iovec __user *, lvec, unsigned long, liovcnt, const struct iovec __user *, rvec, unsigned long, riovcnt, unsigned long, flags)
___SYSCALL6(305, process_vm_writev, pid_t, pid, const struct iovec __user *, lvec, unsigned long, liovcnt, const struct iovec __user *, rvec, unsigned long, riovcnt, unsigned long, flags)
___SYSCALL5(306, kcmp, pid_t, pid1, pid_t, pid2, int, type, unsigned long, idx1, unsigned long, idx2)
___SYSCALL3(307, finit_module, int, fd, const char __user *, uargs, int, flags)
___SYSCALL3(309, sched_setattr, pid_t, pid, struct sched_attr __user *, uattr, unsigned int, flags)
___SYSCALL4(310, sched_getattr, pid_t, pid, struct sched_attr __user *, uattr, unsigned int, usize, unsigned int, flags)
___SYSCALL5(311, renameat2, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname, unsigned int, flags)
___SYSCALL3(312, seccomp, unsigned int, op, unsigned int, flags, void __user *, uargs)
___SYSCALL3(313, getrandom, char __user *, buf, size_t, count, unsigned int, flags)
___SYSCALL2(314, memfd_create, const char __user *, uname, unsigned int, flags)
___SYSCALL3(315, bpf, int, cmd, union bpf_attr __user *, uattr, unsigned int, size)
___SYSCALL5(316, execveat, int, fd, const char __user *, filename, const char __user *const __user *, argv, const char __user *const __user *, envp, int, flags)
___SYSCALL1(317, userfaultfd, int, flags)
___SYSCALL2(318, membarrier, int, cmd, int, flags)
___SYSCALL3(319, mlock2, unsigned long, start, size_t, len, int, flags)
___SYSCALL6(320, copy_file_range, int, fd_in, loff_t __user *, off_in, int, fd_out, loff_t __user *, off_out, size_t, len, unsigned int, flags)
___SYSCALL6(321, preadv2, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, int, flags)
___SYSCALL6(322, pwritev2, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, int, flags)
___SYSCALL4(323, pkey_mprotect, unsigned long, start, size_t, len, unsigned long, prot, int, pkey)
___SYSCALL2(324, pkey_alloc, unsigned long, flags, unsigned long, init_val)
___SYSCALL1(325, pkey_free, int, pkey)
___SYSCALL5(326, statx, int, dfd, const char __user *, filename, unsigned, flags, unsigned int, mask, struct statx __user *, buffer)
___SYSCALL6(328, io_pgetevents, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event __user *, events, struct __kernel_timespec __user *, timeout, const struct __aio_sigset __user *, usig)
___SYSCALL4(327, rseq, struct rseq __user *, rseq, uint32_t, rseq_len, int, flags, uint32_t, sig)
___SYSCALL4(424, pidfd_send_signal, int, pidfd, int, sig, siginfo_t __user *, info, unsigned int, flags)
___SYSCALL2(425, io_uring_setup, uint32_t, entries, struct io_uring_params __user *, params)
___SYSCALL6(426, io_uring_enter, unsigned int, fd, uint32_t, to_submit, uint32_t, min_complete, uint32_t, flags, const sigset_t __user *, sig, size_t, sigsz)
___SYSCALL4(427, io_uring_register, unsigned int, fd, unsigned int, opcode, void __user *, arg, unsigned int, nr_args)
___SYSCALL3(428, open_tree, int, dfd, const char *, filename, unsigned, flags)
___SYSCALL5(429, move_mount, int, from_dfd, const char *, from_pathname, int, to_dfd, const char *, to_pathname, unsigned int, flags)
___SYSCALL2(430, fsopen, const char __user *, _fs_name, unsigned int, flags)
___SYSCALL5(431, fsconfig, int, fd, unsigned int, cmd, const char __user *, _key, const void __user *, _value, int, aux)
___SYSCALL3(432, fsmount, int, fs_fd, unsigned int, flags, unsigned int, attr_flags)
___SYSCALL3(433, fspick, int, dfd, const char __user *, path, unsigned int, flags)
___SYSCALL2(434, pidfd_open, pid_t, pid, unsigned int, flags)
___SYSCALL2(435, clone3, struct clone_args __user *, uargs, size_t, size)

#include "syscalls.inc.macros_end.h"
