#include "syscalls.inc.macros_begin.h"

___SYSCALL3(5002, open, const char __user *, filename, int, flags, mode_t, mode)
___SYSCALL2(5004, newstat, const char __user *, filename, struct stat __user *, statbuf)
___SYSCALL2(5006, newlstat, const char __user *, filename, struct stat __user *, statbuf)
___SYSCALL3(5007, poll, struct pollfd __user *, ufds, unsigned int, nfds, int, timeout_msecs)
___SYSCALL2(5020, access, const char __user *, filename, int, mode)
___SYSCALL0(5021, sysm_pipe)
___SYSCALL5(5022, select, int, n, fd_set __user *, inp, fd_set __user *, outp, fd_set __user *, exp, struct timeval __user *, tvp)
___SYSCALL3(5030, old_shmctl, int, shmid, int, cmd, struct shmid_ds __user *, buf)
___SYSCALL2(5032, dup2, unsigned int, oldfd, unsigned int, newfd)
___SYSCALL0(5033, pause)
___SYSCALL1(5037, alarm, unsigned int, seconds)
___SYSCALL0(5056, fork)
___SYSCALL4(5064, old_semctl, int, semid, int, semnum, int, cmd, unsigned long, arg)
___SYSCALL3(5069, old_msgctl, int, msqid, int, cmd, struct msqid_ds __user *, buf)
___SYSCALL3(5076, getdents, unsigned int, fd, struct linux_dirent __user *, dirent, unsigned int, count)
___SYSCALL2(5080, rename, const char __user *, oldname, const char __user *, newname)
___SYSCALL2(5081, mkdir, const char __user *, pathname, mode_t, mode)
___SYSCALL1(5082, rmdir, const char __user *, pathname)
___SYSCALL2(5083, creat, const char __user *, pathname, mode_t, mode)
___SYSCALL2(5084, link, const char __user *, oldname, const char __user *, newname)
___SYSCALL1(5085, unlink, const char __user *, pathname)
___SYSCALL2(5086, symlink, const char __user *, oldname, const char __user *, newname)
___SYSCALL3(5087, readlink, const char __user *, path, char __user *, buf, int, bufsiz)
___SYSCALL2(5088, chmod, const char __user *, filename, mode_t, mode)
___SYSCALL3(5090, chown, const char __user *, filename, uid_t, user, gid_t, group)
___SYSCALL3(5092, lchown, const char __user *, filename, uid_t, user, gid_t, group)
___SYSCALL0(5109, getpgrp)
___SYSCALL2(5130, utime, char __user *, filename, struct utimbuf __user *, times)
___SYSCALL3(5131, mknod, const char __user *, filename, mode_t, mode, unsigned, dev)
___SYSCALL1(5132, personality, unsigned int, personality)
___SYSCALL2(5133, ustat, unsigned, dev, struct ustat __user *, ubuf)
___SYSCALL3(5136, sysfs, int, option, unsigned long, arg1, unsigned long, arg2)
___SYSCALL1(5152, sysctl, struct __sysctl_args __user *, args)
___SYSCALL3(5197, cacheflush, unsigned long, addr, unsigned long, bytes, unsigned int, cache)
___SYSCALL3(5198, cachectl, char *, addr, int, nbytes, int, op)
___SYSCALL3(5199, sysmips, long, cmd, long, arg1, long, arg2)
___SYSCALL1(5207, epoll_create, int, size)
___SYSCALL4(5209, epoll_wait, int, epfd, struct epoll_event __user *, events, int, maxevents, int, timeout)
___SYSCALL2(5226, utimes, char __user *, filename, struct timeval __user *, utimes)
___SYSCALL1(5242, set_thread_area, unsigned long, addr)
___SYSCALL0(5243, inotify_init)
___SYSCALL3(5251, futimesat, int, dfd, const char __user *, filename, struct timeval __user *, utimes)
___SYSCALL3(5276, signalfd, int, ufd, sigset_t __user *, user_mask, size_t, sizemask)
___SYSCALL1(5278, eventfd, unsigned int, count)
___SYSCALL4(5437, openat2, int, dfd, const char __user *, filename, struct open_how __user *, how, size_t, usize)
___SYSCALL3(5438, pidfd_getfd, int, pidfd, int, fd, unsigned int, flags)

___SYSCALL2(5200, io_setup, unsigned, nr_events, aio_context_t __user *, ctxp)
___SYSCALL1(5201, io_destroy, aio_context_t, ctx)
___SYSCALL3(5203, io_submit, aio_context_t, ctx_id, long, nr, struct iocb __user * __user *, iocbpp)
___SYSCALL3(5204, io_cancel, aio_context_t, ctx_id, struct iocb __user *, iocb, struct io_event __user *, result)
___SYSCALL5(5202, io_getevents, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event __user *, events, struct __kernel_timespec __user *, timeout)
___SYSCALL5(5180, setxattr, const char __user *, pathname, const char __user *, name, const void __user *, value, size_t, size, int, flags)
___SYSCALL5(5181, lsetxattr, const char __user *, pathname, const char __user *, name, const void __user *, value, size_t, size, int, flags)
___SYSCALL5(5182, fsetxattr, int, fd, const char __user *, name, const void __user *,value, size_t, size, int, flags)
___SYSCALL4(5183, getxattr, const char __user *, pathname, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL4(5184, lgetxattr, const char __user *, pathname, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL4(5185, fgetxattr, int, fd, const char __user *, name, void __user *, value, size_t, size)
___SYSCALL3(5186, listxattr, const char __user *, pathname, char __user *, list, size_t, size)
___SYSCALL3(5187, llistxattr, const char __user *, pathname, char __user *, list, size_t, size)
___SYSCALL3(5188, flistxattr, int, fd, char __user *, list, size_t, size)
___SYSCALL2(5189, removexattr, const char __user *, pathname, const char __user *, name)
___SYSCALL2(5190, lremovexattr, const char __user *, pathname, const char __user *, name)
___SYSCALL2(5191, fremovexattr, int, fd, const char __user *, name)
___SYSCALL2(5077, getcwd, char __user *, buf, unsigned long, size)
___SYSCALL3(5206, lookup_dcookie, u64, cookie64, char __user *, buf, size_t, len)
___SYSCALL2(5284, eventfd2, unsigned int, count, int, flags)
___SYSCALL1(5285, epoll_create1, int, flags)
___SYSCALL4(5208, epoll_ctl, int, epfd, int, op, int, fd, struct epoll_event __user *, event)
___SYSCALL6(5272, epoll_pwait, int, epfd, struct epoll_event __user *, events, int, maxevents, int, timeout, const sigset_t __user *, sigmask, size_t, sigsetsize)
___SYSCALL1(5031, dup, unsigned int, fildes)
___SYSCALL3(5286, dup3, unsigned int, oldfd, unsigned int, newfd, int, flags)
___SYSCALL3(5070, fcntl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL1(5288, inotify_init1, int, flags)
___SYSCALL3(5244, inotify_add_watch, int, fd, const char __user *, pathname, u32, mask)
___SYSCALL2(5245, inotify_rm_watch, int, fd, __s32, wd)
___SYSCALL3(5015, ioctl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
___SYSCALL3(5273, ioprio_set, int, which, int, who, int, ioprio)
___SYSCALL2(5274, ioprio_get, int, which, int, who)
___SYSCALL2(5071, flock, unsigned int, fd, unsigned int, cmd)
___SYSCALL4(5249, mknodat, int, dfd, const char __user *, filename, mode_t, mode, unsigned int, dev)
___SYSCALL3(5248, mkdirat, int, dfd, const char __user *, pathname, mode_t, mode)
___SYSCALL3(5253, unlinkat, int, dfd, const char __user *, pathname, int, flag)
___SYSCALL3(5256, symlinkat, const char __user *, oldname, int, newdfd, const char __user *, newname)
___SYSCALL5(5255, linkat, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname, int, flags)
___SYSCALL4(5254, renameat, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname)
___SYSCALL2(5161, umount, char __user *, name, int, flags)
___SYSCALL5(5160, mount, char __user *, dev_name, char __user *, dir_name, char __user *, type, unsigned long, flags, void __user *, data)
___SYSCALL2(5151, pivot_root, const char __user *, new_root, const char __user *, put_old)
___SYSCALL2(5134, statfs, const char __user *, pathname, struct statfs __user *, buf)
___SYSCALL2(5135, fstatfs, unsigned int, fd, struct statfs __user *, buf)
___SYSCALL2(5074, truncate, const char __user *, path, long, length)
___SYSCALL2(5075, ftruncate, unsigned int, fd, unsigned long, length)
___SYSCALL4(5279, fallocate, int, fd, int, mode, loff_t, offset, loff_t, len)
___SYSCALL3(5259, faccessat, int, dfd, const char __user *, filename, int, mode)
___SYSCALL1(5078, chdir, const char __user *, filename)
___SYSCALL1(5079, fchdir, unsigned int, fd)
___SYSCALL1(5156, chroot, const char __user *, filename)
___SYSCALL2(5089, fchmod, unsigned int, fd, mode_t, mode)
___SYSCALL3(5258, fchmodat, int, dfd, const char __user *, filename, mode_t, mode)
___SYSCALL5(5250, fchownat, int, dfd, const char __user *, filename, uid_t, user, gid_t, group, int, flag)
___SYSCALL3(5091, fchown, unsigned int, fd, uid_t, user, gid_t, group)
___SYSCALL4(5247, openat, int, dfd, const char __user *, filename, int, flags, mode_t, mode)
___SYSCALL1(5003, close, unsigned int, fd)
___SYSCALL0(5150, vhangup)
___SYSCALL2(5287, pipe2, int __user *, fildes, int, flags)
___SYSCALL4(5172, quotactl, unsigned int, cmd, const char __user *, special, qid_t, id, void __user *, addr)
___SYSCALL3(5308, getdents64, unsigned int, fd, struct linux_dirent64 __user *, dirent, unsigned int, count)
___SYSCALL3(5008, lseek, unsigned int, fd, off_t, offset, unsigned int, whence)
___SYSCALL3(5000, read, unsigned int, fd, char __user *, buf, size_t, count)
___SYSCALL3(5001, write, unsigned int, fd, const char __user *, buf, size_t, count)
___SYSCALL3(5018, readv, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen)
___SYSCALL3(5019, writev, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen)
___SYSCALL4(5016, pread64, unsigned int, fd, char __user *, buf, size_t, count, loff_t, pos)
___SYSCALL4(5017, pwrite64, unsigned int, fd, const char __user *, buf, size_t, count, loff_t, pos)
___SYSCALL5(5289, preadv, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
___SYSCALL5(5290, pwritev, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
___SYSCALL4(5039, sendfile64, int, out_fd, int, in_fd, loff_t __user *, offset, size_t, count)
___SYSCALL6(5260, pselect6, int, n, fd_set __user *, inp, fd_set __user *, outp, fd_set __user *, exp, struct __kernel_timespec __user *, tsp, void __user *, sig)
___SYSCALL5(5261, ppoll, struct pollfd __user *, ufds, unsigned int, nfds, struct __kernel_timespec __user *, tsp, const sigset_t __user *, sigmask, size_t, sigsetsize)
___SYSCALL4(5283, signalfd4, int, ufd, sigset_t __user *, user_mask, size_t, sizemask, int, flags)
___SYSCALL4(5266, vmsplice, int, fd, const struct iovec __user *, uiov, unsigned long, nr_segs, unsigned int, flags)
___SYSCALL6(5263, splice, int, fd_in, loff_t __user *, off_in, int, fd_out, loff_t __user *, off_out, size_t, len, unsigned int, flags)
___SYSCALL4(5265, tee, int, fdin, int, fdout, size_t, len, unsigned int, flags)
___SYSCALL4(5257, readlinkat, int, dfd, const char __user *, pathname, char __user *, buf, int, bufsiz)
___SYSCALL4(5252, newfstatat, int, dfd, const char __user *, filename, struct stat __user *, statbuf, int, flag)
___SYSCALL2(5005, newfstat, unsigned int, fd, struct stat __user *, statbuf)
___SYSCALL0(5157, sync)
___SYSCALL1(5072, fsync, unsigned int, fd)
___SYSCALL1(5073, fdatasync, unsigned int, fd)
___SYSCALL4(5264, sync_file_range, int, fd, loff_t, offset, loff_t, nbytes, unsigned int, flags)
___SYSCALL2(5280, timerfd_create, int, clockid, int, flags)
___SYSCALL4(5282, timerfd_settime, int, ufd, int, flags, const struct __kernel_itimerspec __user *, utmr, struct __kernel_itimerspec __user *, otmr)
___SYSCALL2(5281, timerfd_gettime, int, ufd, struct __kernel_itimerspec __user *, otmr)
___SYSCALL4(5275, utimensat, int, dfd, const char __user *, filename, struct __kernel_timespec __user *, utimes, int, flags)
___SYSCALL1(5158, acct, const char __user *, name)
___SYSCALL2(5123, capget, cap_user_header_t, header, cap_user_data_t, dataptr)
___SYSCALL2(5124, capset, cap_user_header_t, header, const cap_user_data_t, data)
___SYSCALL1(5058, exit, int, error_code)
___SYSCALL1(5205, exit_group, int, error_code)
___SYSCALL5(5237, waitid, int, which, pid_t, upid, struct siginfo __user *, infop, int, options, struct rusage __user *, ru)
___SYSCALL1(5212, set_tid_address, int __user *, tidptr)
___SYSCALL1(5262, unshare, unsigned long, unshare_flags)
___SYSCALL6(5194, futex, u32 __user *, uaddr, int, op, u32, val, struct __kernel_timespec __user *, utime, u32 __user *, uaddr2, u32, val3)
___SYSCALL2(5268, set_robust_list, struct robust_list_head __user *, head, size_t, len)
___SYSCALL3(5269, get_robust_list, int, pid, struct robust_list_head __user * __user *, head_ptr, size_t __user *, len_ptr)
___SYSCALL2(5034, nanosleep, struct __kernel_timespec __user *, rqtp, struct __kernel_timespec __user *, rmtp)
___SYSCALL2(5035, getitimer, int, which, struct itimerval __user *, value)
___SYSCALL3(5036, setitimer, int, which, struct itimerval __user *, value, struct itimerval __user *, ovalue)
___SYSCALL4(5270, kexec_load, unsigned long, entry, unsigned long, nr_segments, struct kexec_segment __user *, segments, unsigned long, flags)
___SYSCALL3(5168, init_module, void __user *, umod, unsigned long, len, const char __user *, uargs)
___SYSCALL2(5169, delete_module, const char __user *, name_user, unsigned int, flags)
___SYSCALL3(5216, timer_create, const clockid_t, which_clock, struct sigevent __user *, timer_event_spec, timer_t __user *, created_timer_id)
___SYSCALL2(5218, timer_gettime, timer_t, timer_id, struct __kernel_itimerspec __user *, setting)
___SYSCALL1(5219, timer_getoverrun, timer_t, timer_id)
___SYSCALL4(5217, timer_settime, timer_t, timer_id, int, flags, const struct __kernel_itimerspec __user *, new_setting, struct __kernel_itimerspec __user *, old_setting)
___SYSCALL1(5220, timer_delete, timer_t, timer_id)
___SYSCALL2(5221, clock_settime, const clockid_t, which_clock, const struct __kernel_timespec __user *, tp)
___SYSCALL2(5222, clock_gettime, const clockid_t, which_clock, struct __kernel_timespec __user *, tp)
___SYSCALL2(5223, clock_getres, const clockid_t, which_clock, struct __kernel_timespec __user *, tp)
___SYSCALL4(5224, clock_nanosleep, const clockid_t, which_clock, int, flags, const struct __kernel_timespec __user *, rqtp, struct __kernel_timespec __user *, rmtp)
___SYSCALL3(5101, syslog, int, type, char __user *, buf, int, len)
___SYSCALL4(5099, ptrace, long, request, long, pid, unsigned long, addr, unsigned long, data)
___SYSCALL2(5139, sched_setparam, pid_t, pid, struct sched_param __user *, param)
___SYSCALL3(5141, sched_setscheduler, pid_t, pid, int, policy, struct sched_param __user *, param)
___SYSCALL1(5142, sched_getscheduler, pid_t, pid)
___SYSCALL2(5140, sched_getparam, pid_t, pid, struct sched_param __user *, param)
___SYSCALL3(5195, sched_setaffinity, pid_t, pid, unsigned int, len, unsigned long __user *, user_mask_ptr)
___SYSCALL3(5196, sched_getaffinity, pid_t, pid, unsigned int, len, unsigned long __user *, user_mask_ptr)
___SYSCALL0(5023, sched_yield)
___SYSCALL1(5143, sched_get_priority_max, int, policy)
___SYSCALL1(5144, sched_get_priority_min, int, policy)
___SYSCALL2(5145, sched_rr_get_interval, pid_t, pid, struct __kernel_timespec __user *, interval)
___SYSCALL0(5213, restart_syscall)
___SYSCALL2(5060, kill, pid_t, pid, int, sig)
___SYSCALL2(5192, tkill, pid_t, pid, int, sig)
___SYSCALL3(5225, tgkill, pid_t, tgid, pid_t, pid, int, sig)
___SYSCALL2(5129, sigaltstack, const stack_t __user *,uss, stack_t __user *,uoss)
___SYSCALL2(5128, rt_sigsuspend, sigset_t __user *, unewset, size_t, sigsetsize)
___SYSCALL4(5013, rt_sigaction, int, sig, const struct sigaction __user *, act, struct sigaction __user *, oact, size_t, sigsetsize)
___SYSCALL4(5014, rt_sigprocmask, int, how, sigset_t __user *, nset, sigset_t __user *, oset, size_t, sigsetsize)
___SYSCALL2(5125, rt_sigpending, sigset_t __user *, uset, size_t, sigsetsize)
___SYSCALL4(5126, rt_sigtimedwait, const sigset_t __user *, uthese, siginfo_t __user *, uinfo, const struct __kernel_timespec __user *, uts, size_t, sigsetsize)
___SYSCALL3(5127, rt_sigqueueinfo, pid_t, pid, int, sig, siginfo_t __user *, uinfo)
___SYSCALL0(5211, rt_sigreturn)
___SYSCALL3(5138, setpriority, int, which, int, who, int, niceval)
___SYSCALL2(5137, getpriority, int, which, int, who)
___SYSCALL4(5164, reboot, int, magic1, int, magic2, unsigned int, cmd, void __user *, arg)
___SYSCALL2(5112, setregid, gid_t, rgid, gid_t, egid)
___SYSCALL1(5104, setgid, gid_t, gid)
___SYSCALL2(5111, setreuid, uid_t, ruid, uid_t, euid)
___SYSCALL1(5103, setuid, uid_t, uid)
___SYSCALL3(5115, setresuid, uid_t, ruid, uid_t, euid, uid_t, suid)
___SYSCALL3(5116, getresuid, uid_t __user *, ruidp, uid_t __user *, euidp, uid_t __user *, suidp)
___SYSCALL3(5117, setresgid, gid_t, rgid, gid_t, egid, gid_t, sgid)
___SYSCALL3(5118, getresgid, gid_t __user *, rgidp, gid_t __user *, egidp, gid_t __user *, sgidp)
___SYSCALL1(5120, setfsuid, uid_t, uid)
___SYSCALL1(5121, setfsgid, gid_t, gid)
___SYSCALL1(5098, times, struct tms __user *, tbuf)
___SYSCALL2(5107, setpgid, pid_t, pid, pid_t, pgid)
___SYSCALL1(5119, getpgid, pid_t, pid)
___SYSCALL1(5122, getsid, pid_t, pid)
___SYSCALL0(5110, setsid)
___SYSCALL2(5113, getgroups, int, gidsetsize, gid_t __user *, grouplist)
___SYSCALL2(5114, setgroups, int, gidsetsize, gid_t __user *, grouplist)
___SYSCALL1(5061, newuname, struct new_utsname __user *, name)
___SYSCALL2(5165, sethostname, char __user *, name, int, len)
___SYSCALL2(5166, setdomainname, char __user *, name, int, len)
___SYSCALL2(5095, getrlimit, unsigned int, resource, struct rlimit __user *, rlim)
___SYSCALL2(5155, setrlimit, unsigned int, resource, struct rlimit __user *, rlim)
___SYSCALL2(5096, getrusage, int, who, struct rusage __user *, ru)
___SYSCALL1(5093, umask, int, mask)
___SYSCALL5(5153, prctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
___SYSCALL3(5271, getcpu, unsigned __user *, cpup, unsigned __user *, nodep, struct getcpu_cache __user *, unused)
___SYSCALL2(5094, gettimeofday, struct timeval __user *, tv, struct timezone __user *, tz)
___SYSCALL2(5159, settimeofday, struct timeval __user *, tv, struct timezone __user *, tz)
___SYSCALL1(5154, adjtimex, struct __kernel_timex __user *, txc_p)
___SYSCALL0(5038, getpid)
___SYSCALL0(5108, getppid)
___SYSCALL0(5100, getuid)
___SYSCALL0(5105, geteuid)
___SYSCALL0(5102, getgid)
___SYSCALL0(5106, getegid)
___SYSCALL0(5178, gettid)
___SYSCALL1(5097, sysinfo, struct sysinfo __user *, info)
___SYSCALL4(5230, mq_open, const char __user *, u_name, int, oflag, mode_t, mode, struct mq_attr __user *, u_attr)
___SYSCALL1(5231, mq_unlink, const char __user *, u_name)
___SYSCALL5(5232, mq_timedsend, mqd_t, mqdes, const char __user *, u_msg_ptr, size_t, msg_len, unsigned int, msg_prio, const struct __kernel_timespec __user *, u_abs_timeout)
___SYSCALL5(5233, mq_timedreceive, mqd_t, mqdes, char __user *, u_msg_ptr, size_t, msg_len, unsigned int __user *, u_msg_prio, const struct __kernel_timespec __user *, u_abs_timeout)
___SYSCALL2(5234, mq_notify, mqd_t, mqdes, const struct sigevent __user *, u_notification)
___SYSCALL3(5235, mq_getsetattr, mqd_t, mqdes, const struct mq_attr __user *, u_mqstat, struct mq_attr __user *, u_omqstat)
___SYSCALL2(5066, msgget, key_t, key, int, msgflg)
___SYSCALL5(5068, msgrcv, int, msqid, struct msgbuf __user *, msgp, size_t, msgsz, long, msgtyp, int, msgflg)
___SYSCALL4(5067, msgsnd, int, msqid, struct msgbuf __user *, msgp, size_t, msgsz, int, msgflg)
___SYSCALL3(5062, semget, key_t, key, int, nsems, int, semflg)
___SYSCALL4(5214, semtimedop, int, semid, struct sembuf __user *, tsops, unsigned int, nsops, const struct __kernel_timespec __user *, timeout)
___SYSCALL3(5063, semop, int, semid, struct sembuf __user *, tsops, unsigned, nsops)
___SYSCALL3(5028, shmget, key_t, key, size_t, size, int, shmflg)
___SYSCALL3(5029, shmat, int, shmid, char __user *, shmaddr, int, shmflg)
___SYSCALL1(5065, shmdt, char __user *, shmaddr)
___SYSCALL3(5040, socket, int, family, int, type, int, protocol)
___SYSCALL4(5052, socketpair, int, family, int, type, int, protocol, int __user *, usockvec)
___SYSCALL3(5048, bind, int, fd, struct sockaddr __user *, umyaddr, int, addrlen)
___SYSCALL2(5049, listen, int, fd, int, backlog)
___SYSCALL3(5042, accept, int, fd, struct sockaddr __user *, upeer_sockaddr, int __user *, upeer_addrlen)
___SYSCALL3(5041, connect, int, fd, struct sockaddr __user *, uservaddr, int, addrlen)
___SYSCALL3(5050, getsockname, int, fd, struct sockaddr __user *, usockaddr, int __user *, usockaddr_len)
___SYSCALL3(5051, getpeername, int, fd, struct sockaddr __user *, usockaddr, int __user *, usockaddr_len)
___SYSCALL6(5043, sendto, int, fd, void __user *, buff, size_t, len, unsigned int, flags, struct sockaddr __user *, addr, int, addr_len)
___SYSCALL6(5044, recvfrom, int, fd, void __user *, ubuf, size_t, size, unsigned int, flags, struct sockaddr __user *, addr, int __user *, addr_len)
___SYSCALL5(5053, setsockopt, int, fd, int, level, int, optname, char __user *, optval, int, optlen)
___SYSCALL5(5054, getsockopt, int, fd, int, level, int, optname, char __user *, optval, int __user *, optlen)
___SYSCALL2(5047, shutdown, int, fd, int, how)
___SYSCALL3(5045, sendmsg, int, fd, struct user_msghdr __user *, msg, unsigned int, flags)
___SYSCALL3(5046, recvmsg, int, fd, struct user_msghdr __user *, msg, unsigned int, flags)
___SYSCALL3(5179, readahead, int, fd, loff_t, offset, size_t, count)
___SYSCALL1(5012, brk, unsigned long, brk)
___SYSCALL2(5011, munmap, unsigned long, addr, size_t, len)
___SYSCALL5(5024, mremap, unsigned long, addr, unsigned long, old_len, unsigned long, new_len, unsigned long, flags, unsigned long, new_addr)
___SYSCALL5(5239, add_key, const char __user *, _type, const char __user *, _description, const void __user *, _payload, size_t, plen, key_serial_t, ringid)
___SYSCALL4(5240, request_key, const char __user *, _type, const char __user *, _description, const char __user *, _callout_info, key_serial_t, destringid)
___SYSCALL5(5241, keyctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
___SYSCALL5(5055, clone, unsigned long, clone_flags, unsigned long, newsp, int __user *, parent_tidptr, unsigned long, tls, int __user *, child_tidptr)
___SYSCALL3(5057, execve, const char __user *, filename, const char __user *const __user *, argv, const char __user *const __user *, envp)
___SYSCALL6(5009, mmap, unsigned long, addr, unsigned long, len, unsigned long, prot, unsigned long, flags, unsigned long, fd, unsigned long, off)
___SYSCALL4(5215, fadvise64_64, int, fd, loff_t, offset, loff_t, len, int, advice)
___SYSCALL2(5162, swapon, const char __user *, specialfile, int, swap_flags)
___SYSCALL1(5163, swapoff, const char __user *, specialfile)
___SYSCALL3(5010, mprotect, unsigned long, start, size_t, len, unsigned long, prot)
___SYSCALL3(5025, msync, unsigned long, start, size_t, len, int, flags)
___SYSCALL2(5146, mlock, unsigned long, start, size_t, len)
___SYSCALL2(5147, munlock, unsigned long, start, size_t, len)
___SYSCALL1(5148, mlockall, int, flags)
___SYSCALL0(5149, munlockall)
___SYSCALL3(5026, mincore, unsigned long, start, size_t, len, unsigned char __user *, vec)
___SYSCALL3(5027, madvise, unsigned long, start, size_t, len_in, int, behavior)
___SYSCALL5(5210, remap_file_pages, unsigned long, start, unsigned long, size, unsigned long, prot, unsigned long, pgoff, unsigned long, flags)
___SYSCALL6(5227, mbind, unsigned long, start, unsigned long, len, unsigned long, mode, const unsigned long __user *, nmask, unsigned long, maxnode, unsigned int, flags)
___SYSCALL5(5228, get_mempolicy, int __user *, policy, unsigned long __user *, nmask, unsigned long, maxnode, unsigned long, addr, unsigned long, flags)
___SYSCALL3(5229, set_mempolicy, int, mode, const unsigned long __user *, nmask, unsigned long, maxnode)
___SYSCALL4(5246, migrate_pages, pid_t, pid, unsigned long, maxnode, const unsigned long __user *, old_nodes, const unsigned long __user *, new_nodes)
___SYSCALL6(5267, move_pages, pid_t, pid, unsigned long, nr_pages, const void __user * __user *, pages, const int __user *, nodes, int __user *, status, int, flags)
___SYSCALL4(5291, rt_tgsigqueueinfo, pid_t, tgid, pid_t, pid, int, sig, siginfo_t __user *, uinfo)
___SYSCALL5(5292, perf_event_open, struct perf_event_attr __user *, attr_uptr, pid_t, pid, int, cpu, int, group_fd, unsigned long, flags)
___SYSCALL4(5293, accept4, int, fd, struct sockaddr __user *, upeer_sockaddr, int __user *, upeer_addrlen, int, flags)
___SYSCALL5(5294, recvmmsg, int, fd, struct mmsghdr __user *, mmsg, unsigned int, vlen, unsigned int, flags, struct __kernel_timespec __user *, timeout)
___SYSCALL4(5059, wait4, pid_t, upid, int __user *, stat_addr, int, options, struct rusage __user *, ru)
___SYSCALL4(5297, prlimit64, pid_t, pid, unsigned int, resource, const struct rlimit64 __user *, new_rlim, struct rlimit64 __user *, old_rlim)
___SYSCALL2(5295, fanotify_init, unsigned int, flags, unsigned int, event_f_flags)
___SYSCALL5(5296, fanotify_mark, int, fanotify_fd, unsigned int, flags, __u64, mask, int, dfd, const char  __user *, pathname)
___SYSCALL5(5298, name_to_handle_at, int, dfd, const char __user *, name, struct file_handle __user *, handle, int __user *, mnt_id, int, flag)
___SYSCALL3(5299, open_by_handle_at, int, mountdirfd, struct file_handle __user *, handle, int, flags)
___SYSCALL2(5300, clock_adjtime, const clockid_t, which_clock, struct __kernel_timex __user *, utx)
___SYSCALL1(5301, syncfs, int, fd)
___SYSCALL2(5303, setns, int, fd, int, nstype)
___SYSCALL4(5302, sendmmsg, int, fd, struct mmsghdr __user *, mmsg, unsigned int, vlen, unsigned int, flags)
___SYSCALL6(5304, process_vm_readv, pid_t, pid, const struct iovec __user *, lvec, unsigned long, liovcnt, const struct iovec __user *, rvec, unsigned long, riovcnt, unsigned long, flags)
___SYSCALL6(5305, process_vm_writev, pid_t, pid, const struct iovec __user *, lvec, unsigned long, liovcnt, const struct iovec __user *, rvec, unsigned long, riovcnt, unsigned long, flags)
___SYSCALL5(5306, kcmp, pid_t, pid1, pid_t, pid2, int, type, unsigned long, idx1, unsigned long, idx2)
___SYSCALL3(5307, finit_module, int, fd, const char __user *, uargs, int, flags)
___SYSCALL3(5309, sched_setattr, pid_t, pid, struct sched_attr __user *, uattr, unsigned int, flags)
___SYSCALL4(5310, sched_getattr, pid_t, pid, struct sched_attr __user *, uattr, unsigned int, usize, unsigned int, flags)
___SYSCALL5(5311, renameat2, int, olddfd, const char __user *, oldname, int, newdfd, const char __user *, newname, unsigned int, flags)
___SYSCALL3(5312, seccomp, unsigned int, op, unsigned int, flags, void __user *, uargs)
___SYSCALL3(5313, getrandom, char __user *, buf, size_t, count, unsigned int, flags)
___SYSCALL2(5314, memfd_create, const char __user *, uname, unsigned int, flags)
___SYSCALL3(5315, bpf, int, cmd, union bpf_attr __user *, uattr, unsigned int, size)
___SYSCALL5(5316, execveat, int, fd, const char __user *, filename, const char __user *const __user *, argv, const char __user *const __user *, envp, int, flags)
___SYSCALL1(5317, userfaultfd, int, flags)
___SYSCALL2(5318, membarrier, int, cmd, int, flags)
___SYSCALL3(5319, mlock2, unsigned long, start, size_t, len, int, flags)
___SYSCALL6(5320, copy_file_range, int, fd_in, loff_t __user *, off_in, int, fd_out, loff_t __user *, off_out, size_t, len, unsigned int, flags)
___SYSCALL6(5321, preadv2, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, rwf_t, flags)
___SYSCALL6(5322, pwritev2, unsigned long, fd, const struct iovec __user *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, rwf_t, flags)
___SYSCALL4(5323, pkey_mprotect, unsigned long, start, size_t, len, unsigned long, prot, int, pkey)
___SYSCALL2(5324, pkey_alloc, unsigned long, flags, unsigned long, init_val)
___SYSCALL1(5325, pkey_free, int, pkey)
___SYSCALL5(5326, statx, int, dfd, const char __user *, filename, unsigned, flags, unsigned int, mask, struct statx __user *, buffer)
___SYSCALL6(5328, io_pgetevents, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event __user *, events, struct __kernel_timespec __user *, timeout, const struct __aio_sigset __user *, usig)
___SYSCALL4(5327, rseq, struct rseq __user *, rseq, u32, rseq_len, int, flags, u32, sig)
___SYSCALL4(5424, pidfd_send_signal, int, pidfd, int, sig, siginfo_t __user *, info, unsigned int, flags)
___SYSCALL2(5425, io_uring_setup, u32, entries, struct io_uring_params __user *, params)
___SYSCALL6(5426, io_uring_enter, unsigned int, fd, u32, to_submit, u32, min_complete, u32, flags, const sigset_t __user *, sig, size_t, sigsz)
___SYSCALL4(5427, io_uring_register, unsigned int, fd, unsigned int, opcode, void __user *, arg, unsigned int, nr_args)
___SYSCALL3(5428, open_tree, int, dfd, const char *, filename, unsigned, flags)
___SYSCALL5(5429, move_mount, int, from_dfd, const char *, from_pathname, int, to_dfd, const char *, to_pathname, unsigned int, flags)
___SYSCALL2(5430, fsopen, const char __user *, _fs_name, unsigned int, flags)
___SYSCALL5(5431, fsconfig, int, fd, unsigned int, cmd, const char __user *, _key, const void __user *, _value, int, aux)
___SYSCALL3(5432, fsmount, int, fs_fd, unsigned int, flags, unsigned int, attr_flags)
___SYSCALL3(5433, fspick, int, dfd, const char __user *, path, unsigned int, flags)
___SYSCALL2(5434, pidfd_open, pid_t, pid, unsigned int, flags)
___SYSCALL2(5435, clone3, struct clone_args __user *, uargs, size_t, size)

#include "syscalls.inc.macros_end.h"
