#pragma once
#ifdef __cplusplus
#include <bitset>
#include <array>
#include <cstdint>

/* NOTE: THIS FILE IS AUTO-GENERATED BY GEN-TCGCONSTANTS */
namespace jove {

//
// I64 _frame
// I64 env
// I32 cc_op
// I64 cc_dst
// I64 cc_src
// I64 cc_src2
// I64 rip
// I64 rax
// I64 rcx
// I64 rdx
// I64 rbx
// I64 rsp
// I64 rbp
// I64 rsi
// I64 rdi
// I64 r8
// I64 r9
// I64 r10
// I64 r11
// I64 r12
// I64 r13
// I64 r14
// I64 r15
// I64 es_base
// I64 cs_base
// I64 ss_base
// I64 ds_base
// I64 fs_base
// I64 gs_base
// I64 bnd0_lb
// I64 bnd0_ub
// I64 bnd1_lb
// I64 bnd1_ub
// I64 bnd2_lb
// I64 bnd2_ub
// I64 bnd3_lb
// I64 bnd3_ub
//

typedef uint64_t taddr_t;
constexpr int tcg_num_globals = 37;
constexpr int tcg_max_temps = 512;
constexpr int tcg_env_index = 1;
constexpr int tcg_program_counter_index = 6;
constexpr int tcg_frame_pointer_index = 12;
constexpr int tcg_stack_pointer_index = 11;
constexpr int tcg_program_counter_env_offset = 128;
constexpr int tcg_syscall_number_index = 7;
constexpr int tcg_syscall_return_index = 7;
constexpr int tcg_syscall_arg1_index = 14;
constexpr int tcg_syscall_arg2_index = 13;
constexpr int tcg_syscall_arg3_index = 9;
constexpr int tcg_syscall_arg4_index = 17;
constexpr int tcg_syscall_arg5_index = 15;
constexpr int tcg_syscall_arg6_index = 16;
constexpr int tcg_fs_base_index = 27;
constexpr int tcg_r12_index = 19;
constexpr int tcg_r13_index = 20;
constexpr int tcg_r14_index = 21;
constexpr int tcg_r15_index = 22;
typedef std::bitset<tcg_num_globals> tcg_global_set_t;
constexpr tcg_global_set_t NotArgs(137430564991);
constexpr tcg_global_set_t NotRets(137430564991);
constexpr tcg_global_set_t CallConvArgs(123648);
typedef std::array<unsigned, 6> CallConvArgArrayTy;
static const CallConvArgArrayTy CallConvArgArray{14, 13, 9, 8, 15, 16};
constexpr tcg_global_set_t CallConvRets(640);
typedef std::array<unsigned, 2> CallConvRetArrayTy;
static const CallConvRetArrayTy CallConvRetArray{7, 9};
constexpr tcg_global_set_t CalleeSavedRegs(7869440);
static const uint8_t tcg_global_by_offset_lookup_table[585] = {
[0 ... 584] = 0xff,
[168] = 2,
[144] = 3,
[152] = 4,
[160] = 5,
[128] = 6,
[0] = 7,
[8] = 8,
[16] = 9,
[24] = 10,
[32] = 11,
[40] = 12,
[48] = 13,
[56] = 14,
[64] = 15,
[72] = 16,
[80] = 17,
[88] = 18,
[96] = 19,
[104] = 20,
[112] = 21,
[120] = 22,
[192] = 23,
[216] = 24,
[240] = 25,
[264] = 26,
[288] = 27,
[312] = 28,
[528] = 29,
[536] = 30,
[544] = 31,
[552] = 32,
[560] = 33,
[568] = 34,
[576] = 35,
[584] = 36,
};
constexpr tcg_global_set_t PinnedEnvGlbs(0);
}
#endif /* __cplusplus */

#define TARGET_NUM_REG_ARGS 6
