#pragma once
#include <bitset>
#include <array>
#include <cstdint>

/* NOTE: THIS FILE IS AUTO-GENERATED BY GEN-TCGCONSTANTS */
namespace jove {

#ifdef __x86_64__ /* XXX cross-compiling */

//
// I64 _frame
// I64 env
// I32 at
// I32 v0
// I32 v1
// I32 a0
// I32 a1
// I32 a2
// I32 a3
// I32 t0
// I32 t1
// I32 t2
// I32 t3
// I32 t4
// I32 t5
// I32 t6
// I32 t7
// I32 s0
// I32 s1
// I32 s2
// I32 s3
// I32 s4
// I32 s5
// I32 s6
// I32 s7
// I32 t8
// I32 t9
// I32 k0
// I32 k1
// I32 gp
// I32 sp
// I32 s8
// I32 ra
// I64 w0.d0
// I64 w0.d1
// I64 w1.d0
// I64 w1.d1
// I64 w2.d0
// I64 w2.d1
// I64 w3.d0
// I64 w3.d1
// I64 w4.d0
// I64 w4.d1
// I64 w5.d0
// I64 w5.d1
// I64 w6.d0
// I64 w6.d1
// I64 w7.d0
// I64 w7.d1
// I64 w8.d0
// I64 w8.d1
// I64 w9.d0
// I64 w9.d1
// I64 w10.d0
// I64 w10.d1
// I64 w11.d0
// I64 w11.d1
// I64 w12.d0
// I64 w12.d1
// I64 w13.d0
// I64 w13.d1
// I64 w14.d0
// I64 w14.d1
// I64 w15.d0
// I64 w15.d1
// I64 w16.d0
// I64 w16.d1
// I64 w17.d0
// I64 w17.d1
// I64 w18.d0
// I64 w18.d1
// I64 w19.d0
// I64 w19.d1
// I64 w20.d0
// I64 w20.d1
// I64 w21.d0
// I64 w21.d1
// I64 w22.d0
// I64 w22.d1
// I64 w23.d0
// I64 w23.d1
// I64 w24.d0
// I64 w24.d1
// I64 w25.d0
// I64 w25.d1
// I64 w26.d0
// I64 w26.d1
// I64 w27.d0
// I64 w27.d1
// I64 w28.d0
// I64 w28.d1
// I64 w29.d0
// I64 w29.d1
// I64 w30.d0
// I64 w30.d1
// I64 w31.d0
// I64 w31.d1
// I32 PC
// I32 HI0
// I32 LO0
// I32 HI1
// I32 LO1
// I32 HI2
// I32 LO2
// I32 HI3
// I32 LO3
// I32 DSPControl
// I32 bcond
// I32 btarget
// I32 hflags
// I32 fcr0
// I32 fcr31
// I32 lladdr
// I32 llval
// I32 XR1
// I32 XR2
// I32 XR3
// I32 XR4
// I32 XR5
// I32 XR6
// I32 XR7
// I32 XR8
// I32 XR9
// I32 XR10
// I32 XR11
// I32 XR12
// I32 XR13
// I32 XR14
// I32 XR15
// I32 MXU_CR
//

typedef uint32_t tcg_uintptr_t;
constexpr int tcg_num_globals = 194 /* 130 */;
constexpr int tcg_num_helpers = 1069;
constexpr int tcg_max_temps = 512;
constexpr int tcg_env_index = 1;
constexpr int tcg_program_counter_index = 97;
constexpr int tcg_frame_pointer_index = 31;
constexpr int tcg_stack_pointer_index = 30;
constexpr int tcg_program_counter_env_offset = 128;
constexpr int tcg_syscall_number_index = 3;
constexpr int tcg_syscall_return_index = 3;
constexpr int tcg_syscall_arg1_index = 5;
constexpr int tcg_syscall_arg2_index = 6;
constexpr int tcg_syscall_arg3_index = 7;
constexpr int tcg_syscall_arg4_index = 8;
constexpr int tcg_syscall_arg5_index = -1;
constexpr int tcg_syscall_arg6_index = -1;
constexpr int tcg_t9_index = 26;
constexpr int tcg_ra_index = 32;
constexpr int tcg_gp_index = 29;
constexpr int tcg_llval_index = 113;
constexpr int tcg_lladdr_index = 112;
constexpr int tcg_btarget_index = 108;
typedef std::bitset<tcg_num_globals> tcg_global_set_t;
static const tcg_global_set_t NotArgs("0000000000000000000001100000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011");
static const tcg_global_set_t NotRets("0000000000000000000001100000000010000000000000000000000000000000000000000000000000000000000000000100100000000000000000000000000011");
constexpr tcg_global_set_t CallConvArgs(480);
typedef std::array<unsigned, 4> CallConvArgArrayTy;
static const CallConvArgArrayTy CallConvArgArray{5, 6, 7, 8};
constexpr tcg_global_set_t CallConvRets(24);
typedef std::array<unsigned, 2> CallConvRetArrayTy;
static const CallConvRetArrayTy CallConvRetArray{3, 4};
constexpr tcg_global_set_t CalleeSavedRegs(33423360);
static const uint8_t tcg_global_by_offset_lookup_table[11133] = {
[0 ... 11132] = 0xff,
[4] = 2,
[8] = 3,
[12] = 4,
[16] = 5,
[20] = 6,
[24] = 7,
[28] = 8,
[32] = 9,
[36] = 10,
[40] = 11,
[44] = 12,
[48] = 13,
[52] = 14,
[56] = 15,
[60] = 16,
[64] = 17,
[68] = 18,
[72] = 19,
[76] = 20,
[80] = 21,
[84] = 22,
[88] = 23,
[92] = 24,
[96] = 25,
[100] = 26,
[104] = 27,
[108] = 28,
[112] = 29,
[116] = 30,
[120] = 31,
[124] = 32,
[552] = 33,
[560] = 34,
[568] = 35,
[576] = 36,
[584] = 37,
[592] = 38,
[600] = 39,
[608] = 40,
[616] = 41,
[624] = 42,
[632] = 43,
[640] = 44,
[648] = 45,
[656] = 46,
[664] = 47,
[672] = 48,
[680] = 49,
[688] = 50,
[696] = 51,
[704] = 52,
[712] = 53,
[720] = 54,
[728] = 55,
[736] = 56,
[744] = 57,
[752] = 58,
[760] = 59,
[768] = 60,
[776] = 61,
[784] = 62,
[792] = 63,
[800] = 64,
[808] = 65,
[816] = 66,
[824] = 67,
[832] = 68,
[840] = 69,
[848] = 70,
[856] = 71,
[864] = 72,
[872] = 73,
[880] = 74,
[888] = 75,
[896] = 76,
[904] = 77,
[912] = 78,
[920] = 79,
[928] = 80,
[936] = 81,
[944] = 82,
[952] = 83,
[960] = 84,
[968] = 85,
[976] = 86,
[984] = 87,
[992] = 88,
[1000] = 89,
[1008] = 90,
[1016] = 91,
[1024] = 92,
[1032] = 93,
[1040] = 94,
[1048] = 95,
[1056] = 96,
[128] = 97,
[132] = 98,
[148] = 99,
[136] = 100,
[152] = 101,
[140] = 102,
[156] = 103,
[144] = 104,
[160] = 105,
[180] = 106,
[11132] = 107,
[11128] = 108,
[11124] = 109,
[1072] = 110,
[1080] = 111,
[1564] = 112,
[1568] = 113,
[488] = 114,
[492] = 115,
[496] = 116,
[500] = 117,
[504] = 118,
[508] = 119,
[512] = 120,
[516] = 121,
[520] = 122,
[524] = 123,
[528] = 124,
[532] = 125,
[536] = 126,
[540] = 127,
[544] = 128,
[548] = 129,
};
static const tcg_global_set_t PinnedEnvGlbs("0000000000000000001110000000000001111111111111111111111111111111111111111111111111111111111111111000000000000000000000000000000000");

#else

//
// I32 _frame
// I32 env
// I32 at
// I32 v0
// I32 v1
// I32 a0
// I32 a1
// I32 a2
// I32 a3
// I32 t0
// I32 t1
// I32 t2
// I32 t3
// I32 t4
// I32 t5
// I32 t6
// I32 t7
// I32 s0
// I32 s1
// I32 s2
// I32 s3
// I32 s4
// I32 s5
// I32 s6
// I32 s7
// I32 t8
// I32 t9
// I32 k0
// I32 k1
// I32 gp
// I32 sp
// I32 s8
// I32 ra
// I32 w0.d0_0
// I32 w0.d0_1
// I32 w0.d1_0
// I32 w0.d1_1
// I32 w1.d0_0
// I32 w1.d0_1
// I32 w1.d1_0
// I32 w1.d1_1
// I32 w2.d0_0
// I32 w2.d0_1
// I32 w2.d1_0
// I32 w2.d1_1
// I32 w3.d0_0
// I32 w3.d0_1
// I32 w3.d1_0
// I32 w3.d1_1
// I32 w4.d0_0
// I32 w4.d0_1
// I32 w4.d1_0
// I32 w4.d1_1
// I32 w5.d0_0
// I32 w5.d0_1
// I32 w5.d1_0
// I32 w5.d1_1
// I32 w6.d0_0
// I32 w6.d0_1
// I32 w6.d1_0
// I32 w6.d1_1
// I32 w7.d0_0
// I32 w7.d0_1
// I32 w7.d1_0
// I32 w7.d1_1
// I32 w8.d0_0
// I32 w8.d0_1
// I32 w8.d1_0
// I32 w8.d1_1
// I32 w9.d0_0
// I32 w9.d0_1
// I32 w9.d1_0
// I32 w9.d1_1
// I32 w10.d0_0
// I32 w10.d0_1
// I32 w10.d1_0
// I32 w10.d1_1
// I32 w11.d0_0
// I32 w11.d0_1
// I32 w11.d1_0
// I32 w11.d1_1
// I32 w12.d0_0
// I32 w12.d0_1
// I32 w12.d1_0
// I32 w12.d1_1
// I32 w13.d0_0
// I32 w13.d0_1
// I32 w13.d1_0
// I32 w13.d1_1
// I32 w14.d0_0
// I32 w14.d0_1
// I32 w14.d1_0
// I32 w14.d1_1
// I32 w15.d0_0
// I32 w15.d0_1
// I32 w15.d1_0
// I32 w15.d1_1
// I32 w16.d0_0
// I32 w16.d0_1
// I32 w16.d1_0
// I32 w16.d1_1
// I32 w17.d0_0
// I32 w17.d0_1
// I32 w17.d1_0
// I32 w17.d1_1
// I32 w18.d0_0
// I32 w18.d0_1
// I32 w18.d1_0
// I32 w18.d1_1
// I32 w19.d0_0
// I32 w19.d0_1
// I32 w19.d1_0
// I32 w19.d1_1
// I32 w20.d0_0
// I32 w20.d0_1
// I32 w20.d1_0
// I32 w20.d1_1
// I32 w21.d0_0
// I32 w21.d0_1
// I32 w21.d1_0
// I32 w21.d1_1
// I32 w22.d0_0
// I32 w22.d0_1
// I32 w22.d1_0
// I32 w22.d1_1
// I32 w23.d0_0
// I32 w23.d0_1
// I32 w23.d1_0
// I32 w23.d1_1
// I32 w24.d0_0
// I32 w24.d0_1
// I32 w24.d1_0
// I32 w24.d1_1
// I32 w25.d0_0
// I32 w25.d0_1
// I32 w25.d1_0
// I32 w25.d1_1
// I32 w26.d0_0
// I32 w26.d0_1
// I32 w26.d1_0
// I32 w26.d1_1
// I32 w27.d0_0
// I32 w27.d0_1
// I32 w27.d1_0
// I32 w27.d1_1
// I32 w28.d0_0
// I32 w28.d0_1
// I32 w28.d1_0
// I32 w28.d1_1
// I32 w29.d0_0
// I32 w29.d0_1
// I32 w29.d1_0
// I32 w29.d1_1
// I32 w30.d0_0
// I32 w30.d0_1
// I32 w30.d1_0
// I32 w30.d1_1
// I32 w31.d0_0
// I32 w31.d0_1
// I32 w31.d1_0
// I32 w31.d1_1
// I32 PC
// I32 HI0
// I32 LO0
// I32 HI1
// I32 LO1
// I32 HI2
// I32 LO2
// I32 HI3
// I32 LO3
// I32 DSPControl
// I32 bcond
// I32 btarget
// I32 hflags
// I32 fcr0
// I32 fcr31
// I32 lladdr
// I32 llval
// I32 XR1
// I32 XR2
// I32 XR3
// I32 XR4
// I32 XR5
// I32 XR6
// I32 XR7
// I32 XR8
// I32 XR9
// I32 XR10
// I32 XR11
// I32 XR12
// I32 XR13
// I32 XR14
// I32 XR15
// I32 MXU_CR
//

typedef uint32_t tcg_uintptr_t;
constexpr int tcg_num_globals = 194;
constexpr int tcg_num_helpers = 1069;
constexpr int tcg_max_temps = 512;
constexpr int tcg_env_index = 1;
constexpr int tcg_program_counter_index = 161;
constexpr int tcg_frame_pointer_index = 31;
constexpr int tcg_stack_pointer_index = 30;
constexpr int tcg_program_counter_env_offset = 128;
constexpr int tcg_syscall_number_index = 3;
constexpr int tcg_syscall_return_index = 3;
constexpr int tcg_syscall_arg1_index = 5;
constexpr int tcg_syscall_arg2_index = 6;
constexpr int tcg_syscall_arg3_index = 7;
constexpr int tcg_syscall_arg4_index = 8;
constexpr int tcg_syscall_arg5_index = -1;
constexpr int tcg_syscall_arg6_index = -1;
constexpr int tcg_t9_index = 26;
constexpr int tcg_ra_index = 32;
constexpr int tcg_gp_index = 29;
constexpr int tcg_llval_index = 177;
constexpr int tcg_lladdr_index = 176;
constexpr int tcg_btarget_index = 172;
typedef std::bitset<tcg_num_globals> tcg_global_set_t;
static const tcg_global_set_t NotArgs("00000000000000000000011000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011");
static const tcg_global_set_t NotRets("00000000000000000000011000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100100000000000000000000000000011");
constexpr tcg_global_set_t CallConvArgs(480);
typedef std::array<unsigned, 4> CallConvArgArrayTy;
static const CallConvArgArrayTy CallConvArgArray{5, 6, 7, 8};
constexpr tcg_global_set_t CallConvRets(24);
typedef std::array<unsigned, 2> CallConvRetArrayTy;
static const CallConvRetArrayTy CallConvRetArray{3, 4};
constexpr tcg_global_set_t CalleeSavedRegs(33423360);
static const uint8_t tcg_global_by_offset_lookup_table[11133] = {
[0 ... 11132] = 0xff,
[4] = 2,
[8] = 3,
[12] = 4,
[16] = 5,
[20] = 6,
[24] = 7,
[28] = 8,
[32] = 9,
[36] = 10,
[40] = 11,
[44] = 12,
[48] = 13,
[52] = 14,
[56] = 15,
[60] = 16,
[64] = 17,
[68] = 18,
[72] = 19,
[76] = 20,
[80] = 21,
[84] = 22,
[88] = 23,
[92] = 24,
[96] = 25,
[100] = 26,
[104] = 27,
[108] = 28,
[112] = 29,
[116] = 30,
[120] = 31,
[124] = 32,
[556] = 33,
[552] = 34,
[564] = 35,
[560] = 36,
[572] = 37,
[568] = 38,
[580] = 39,
[576] = 40,
[588] = 41,
[584] = 42,
[596] = 43,
[592] = 44,
[604] = 45,
[600] = 46,
[612] = 47,
[608] = 48,
[620] = 49,
[616] = 50,
[628] = 51,
[624] = 52,
[636] = 53,
[632] = 54,
[644] = 55,
[640] = 56,
[652] = 57,
[648] = 58,
[660] = 59,
[656] = 60,
[668] = 61,
[664] = 62,
[676] = 63,
[672] = 64,
[684] = 65,
[680] = 66,
[692] = 67,
[688] = 68,
[700] = 69,
[696] = 70,
[708] = 71,
[704] = 72,
[716] = 73,
[712] = 74,
[724] = 75,
[720] = 76,
[732] = 77,
[728] = 78,
[740] = 79,
[736] = 80,
[748] = 81,
[744] = 82,
[756] = 83,
[752] = 84,
[764] = 85,
[760] = 86,
[772] = 87,
[768] = 88,
[780] = 89,
[776] = 90,
[788] = 91,
[784] = 92,
[796] = 93,
[792] = 94,
[804] = 95,
[800] = 96,
[812] = 97,
[808] = 98,
[820] = 99,
[816] = 100,
[828] = 101,
[824] = 102,
[836] = 103,
[832] = 104,
[844] = 105,
[840] = 106,
[852] = 107,
[848] = 108,
[860] = 109,
[856] = 110,
[868] = 111,
[864] = 112,
[876] = 113,
[872] = 114,
[884] = 115,
[880] = 116,
[892] = 117,
[888] = 118,
[900] = 119,
[896] = 120,
[908] = 121,
[904] = 122,
[916] = 123,
[912] = 124,
[924] = 125,
[920] = 126,
[932] = 127,
[928] = 128,
[940] = 129,
[936] = 130,
[948] = 131,
[944] = 132,
[956] = 133,
[952] = 134,
[964] = 135,
[960] = 136,
[972] = 137,
[968] = 138,
[980] = 139,
[976] = 140,
[988] = 141,
[984] = 142,
[996] = 143,
[992] = 144,
[1004] = 145,
[1000] = 146,
[1012] = 147,
[1008] = 148,
[1020] = 149,
[1016] = 150,
[1028] = 151,
[1024] = 152,
[1036] = 153,
[1032] = 154,
[1044] = 155,
[1040] = 156,
[1052] = 157,
[1048] = 158,
[1060] = 159,
[1056] = 160,
[128] = 161,
[132] = 162,
[148] = 163,
[136] = 164,
[152] = 165,
[140] = 166,
[156] = 167,
[144] = 168,
[160] = 169,
[180] = 170,
[11132] = 171,
[11128] = 172,
[11124] = 173,
[1072] = 174,
[1080] = 175,
[1564] = 176,
[1568] = 177,
[488] = 178,
[492] = 179,
[496] = 180,
[500] = 181,
[504] = 182,
[508] = 183,
[512] = 184,
[516] = 185,
[520] = 186,
[524] = 187,
[528] = 188,
[532] = 189,
[536] = 190,
[540] = 191,
[544] = 192,
[548] = 193,
};
static const tcg_global_set_t PinnedEnvGlbs("00000000000000000011100000000000011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111000000000000000000000000000000000");

#endif

}
