#pragma once
#ifdef __cplusplus
#include <bitset>
#include <array>
#include <cstdint>

/* NOTE: THIS FILE IS AUTO-GENERATED BY GEN-TCGCONSTANTS */
namespace jove {

#ifdef __x86_64__ /* cross-compiling */

//
// I64 _frame
// I64 env
// I64 at
// I64 v0
// I64 v1
// I64 a0
// I64 a1
// I64 a2
// I64 a3
// I64 t0
// I64 t1
// I64 t2
// I64 t3
// I64 t4
// I64 t5
// I64 t6
// I64 t7
// I64 s0
// I64 s1
// I64 s2
// I64 s3
// I64 s4
// I64 s5
// I64 s6
// I64 s7
// I64 t8
// I64 t9
// I64 k0
// I64 k1
// I64 gp
// I64 sp
// I64 s8
// I64 ra
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 f0
// I64 f1
// I64 f2
// I64 f3
// I64 f4
// I64 f5
// I64 f6
// I64 f7
// I64 f8
// I64 f9
// I64 f10
// I64 f11
// I64 f12
// I64 f13
// I64 f14
// I64 f15
// I64 f16
// I64 f17
// I64 f18
// I64 f19
// I64 f20
// I64 f21
// I64 f22
// I64 f23
// I64 f24
// I64 f25
// I64 f26
// I64 f27
// I64 f28
// I64 f29
// I64 f30
// I64 f31
// I64 w0.d1
// I64 w1.d1
// I64 w2.d1
// I64 w3.d1
// I64 w4.d1
// I64 w5.d1
// I64 w6.d1
// I64 w7.d1
// I64 w8.d1
// I64 w9.d1
// I64 w10.d1w11.d0w11.d1w12.d0w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w11.d1w12.d0w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w30.d1w31.d0w31.d1
// I64 w31.d1
// I64 PC
// I64 HI0
// I64 LO0
// I64 HI1
// I64 LO1
// I64 HI2
// I64 LO2
// I64 HI3
// I64 LO3
// I64 DSPControl
// I64 bcond
// I64 btarget
// I32 hflags
// I32 fcr0
// I32 fcr31
// I64 lladdr
// I64 llval
//

typedef uint64_t tcg_uintptr_t;
constexpr int tcg_num_globals = 145;
constexpr int tcg_max_temps = 512;
constexpr int tcg_env_index = 1;
constexpr int tcg_program_counter_index = 128;
constexpr int tcg_frame_pointer_index = 31;
constexpr int tcg_stack_pointer_index = 30;
constexpr int tcg_program_counter_env_offset = 512;
constexpr int tcg_syscall_number_index = 3;
constexpr int tcg_syscall_return_index = 3;
constexpr int tcg_syscall_arg1_index = 5;
constexpr int tcg_syscall_arg2_index = 6;
constexpr int tcg_syscall_arg3_index = 7;
constexpr int tcg_syscall_arg4_index = 8;
constexpr int tcg_syscall_arg5_index = 9;
constexpr int tcg_syscall_arg6_index = 10;
typedef std::bitset<tcg_num_globals> tcg_global_set_t;
static const tcg_global_set_t NotArgs("0000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011");
static const tcg_global_set_t NotRets("0000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011");
constexpr tcg_global_set_t CallConvArgs(8160);
typedef std::array<unsigned, 8> CallConvArgArrayTy;
static const CallConvArgArrayTy CallConvArgArray{5, 6, 7, 8, 9, 10, 11, 12};
constexpr tcg_global_set_t CallConvRets(24);
typedef std::array<unsigned, 2> CallConvRetArrayTy;
static const CallConvRetArrayTy CallConvRetArray{3, 4};
constexpr tcg_global_set_t CalleeSavedRegs(33423360);
static const uint8_t tcg_global_by_offset_lookup_table[16121] = {
[0 ... 16120] = 0xff,
[8] = 2,
[16] = 3,
[24] = 4,
[32] = 5,
[40] = 6,
[48] = 7,
[56] = 8,
[64] = 9,
[72] = 10,
[80] = 11,
[88] = 12,
[96] = 13,
[104] = 14,
[112] = 15,
[120] = 16,
[128] = 17,
[136] = 18,
[144] = 19,
[152] = 20,
[160] = 21,
[168] = 22,
[176] = 23,
[184] = 24,
[192] = 25,
[200] = 26,
[208] = 27,
[216] = 28,
[224] = 29,
[232] = 30,
[240] = 31,
[248] = 32,
[264] = 33,
[272] = 34,
[280] = 35,
[288] = 36,
[296] = 37,
[304] = 38,
[312] = 39,
[320] = 40,
[328] = 41,
[336] = 42,
[344] = 43,
[352] = 44,
[360] = 45,
[368] = 46,
[376] = 47,
[384] = 48,
[392] = 49,
[400] = 50,
[408] = 51,
[416] = 52,
[424] = 53,
[432] = 54,
[440] = 55,
[448] = 56,
[456] = 57,
[464] = 58,
[472] = 59,
[480] = 60,
[488] = 61,
[496] = 62,
[504] = 63,
[832] = 64,
[848] = 65,
[864] = 66,
[880] = 67,
[896] = 68,
[912] = 69,
[928] = 70,
[944] = 71,
[960] = 72,
[976] = 73,
[992] = 74,
[1008] = 75,
[1024] = 76,
[1040] = 77,
[1056] = 78,
[1072] = 79,
[1088] = 80,
[1104] = 81,
[1120] = 82,
[1136] = 83,
[1152] = 84,
[1168] = 85,
[1184] = 86,
[1200] = 87,
[1216] = 88,
[1232] = 89,
[1248] = 90,
[1264] = 91,
[1280] = 92,
[1296] = 93,
[1312] = 94,
[1328] = 95,
[840] = 96,
[856] = 97,
[872] = 98,
[888] = 99,
[904] = 100,
[920] = 101,
[936] = 102,
[952] = 103,
[968] = 104,
[984] = 105,
[1000] = 106,
[1016] = 107,
[1032] = 108,
[1048] = 109,
[1064] = 110,
[1080] = 111,
[1096] = 112,
[1112] = 113,
[1128] = 114,
[1144] = 115,
[1160] = 116,
[1176] = 117,
[1192] = 118,
[1208] = 119,
[1224] = 120,
[1240] = 121,
[1256] = 122,
[1272] = 123,
[1288] = 124,
[1304] = 125,
[1320] = 126,
[1336] = 127,
[512] = 128,
[520] = 129,
[552] = 130,
[528] = 131,
[560] = 132,
[536] = 133,
[568] = 134,
[544] = 135,
[576] = 136,
[616] = 137,
[16120] = 138,
[16112] = 139,
[16108] = 140,
[1360] = 141,
[1368] = 142,
[1952] = 143,
[1960] = 144,
};
constexpr tcg_global_set_t PinnedEnvGlbs(0);

#else

//
// I64 _frame
// I64 env
// I64 at
// I64 v0
// I64 v1
// I64 a0
// I64 a1
// I64 a2
// I64 a3
// I64 t0
// I64 t1
// I64 t2
// I64 t3
// I64 t4
// I64 t5
// I64 t6
// I64 t7
// I64 s0
// I64 s1
// I64 s2
// I64 s3
// I64 s4
// I64 s5
// I64 s6
// I64 s7
// I64 t8
// I64 t9
// I64 k0
// I64 k1
// I64 gp
// I64 sp
// I64 s8
// I64 ra
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 
// I64 f0
// I64 f1
// I64 f2
// I64 f3
// I64 f4
// I64 f5
// I64 f6
// I64 f7
// I64 f8
// I64 f9
// I64 f10
// I64 f11
// I64 f12
// I64 f13
// I64 f14
// I64 f15
// I64 f16
// I64 f17
// I64 f18
// I64 f19
// I64 f20
// I64 f21
// I64 f22
// I64 f23
// I64 f24
// I64 f25
// I64 f26
// I64 f27
// I64 f28
// I64 f29
// I64 f30
// I64 f31
// I64 w0.d1
// I64 w1.d1
// I64 w2.d1
// I64 w3.d1
// I64 w4.d1
// I64 w5.d1
// I64 w6.d1
// I64 w7.d1
// I64 w8.d1
// I64 w9.d1
// I64 w10.d1w11.d0w11.d1w12.d0w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w11.d1w12.d0w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w30.d1w31.d0w31.d1
// I64 w31.d1
// I64 PC
// I64 HI0
// I64 LO0
// I64 HI1
// I64 LO1
// I64 HI2
// I64 LO2
// I64 HI3
// I64 LO3
// I64 DSPControl
// I64 bcond
// I64 btarget
// I32 hflags
// I32 fcr0
// I32 fcr31
// I64 lladdr
// I64 llval
//

typedef uint64_t tcg_uintptr_t;
constexpr int tcg_num_globals = 145;
constexpr int tcg_max_temps = 512;
constexpr int tcg_env_index = 1;
constexpr int tcg_program_counter_index = 128;
constexpr int tcg_frame_pointer_index = 31;
constexpr int tcg_stack_pointer_index = 30;
constexpr int tcg_program_counter_env_offset = 512;
constexpr int tcg_syscall_number_index = 3;
constexpr int tcg_syscall_return_index = 3;
constexpr int tcg_syscall_arg1_index = 5;
constexpr int tcg_syscall_arg2_index = 6;
constexpr int tcg_syscall_arg3_index = 7;
constexpr int tcg_syscall_arg4_index = 8;
constexpr int tcg_syscall_arg5_index = 9;
constexpr int tcg_syscall_arg6_index = 10;
typedef std::bitset<tcg_num_globals> tcg_global_set_t;
static const tcg_global_set_t NotArgs("0000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011");
static const tcg_global_set_t NotRets("0000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011");
constexpr tcg_global_set_t CallConvArgs(8160);
typedef std::array<unsigned, 8> CallConvArgArrayTy;
static const CallConvArgArrayTy CallConvArgArray{5, 6, 7, 8, 9, 10, 11, 12};
constexpr tcg_global_set_t CallConvRets(24);
typedef std::array<unsigned, 2> CallConvRetArrayTy;
static const CallConvRetArrayTy CallConvRetArray{3, 4};
constexpr tcg_global_set_t CalleeSavedRegs(33423360);
static const uint8_t tcg_global_by_offset_lookup_table[16121] = {
[0 ... 16120] = 0xff,
[8] = 2,
[16] = 3,
[24] = 4,
[32] = 5,
[40] = 6,
[48] = 7,
[56] = 8,
[64] = 9,
[72] = 10,
[80] = 11,
[88] = 12,
[96] = 13,
[104] = 14,
[112] = 15,
[120] = 16,
[128] = 17,
[136] = 18,
[144] = 19,
[152] = 20,
[160] = 21,
[168] = 22,
[176] = 23,
[184] = 24,
[192] = 25,
[200] = 26,
[208] = 27,
[216] = 28,
[224] = 29,
[232] = 30,
[240] = 31,
[248] = 32,
[264] = 33,
[272] = 34,
[280] = 35,
[288] = 36,
[296] = 37,
[304] = 38,
[312] = 39,
[320] = 40,
[328] = 41,
[336] = 42,
[344] = 43,
[352] = 44,
[360] = 45,
[368] = 46,
[376] = 47,
[384] = 48,
[392] = 49,
[400] = 50,
[408] = 51,
[416] = 52,
[424] = 53,
[432] = 54,
[440] = 55,
[448] = 56,
[456] = 57,
[464] = 58,
[472] = 59,
[480] = 60,
[488] = 61,
[496] = 62,
[504] = 63,
[832] = 64,
[848] = 65,
[864] = 66,
[880] = 67,
[896] = 68,
[912] = 69,
[928] = 70,
[944] = 71,
[960] = 72,
[976] = 73,
[992] = 74,
[1008] = 75,
[1024] = 76,
[1040] = 77,
[1056] = 78,
[1072] = 79,
[1088] = 80,
[1104] = 81,
[1120] = 82,
[1136] = 83,
[1152] = 84,
[1168] = 85,
[1184] = 86,
[1200] = 87,
[1216] = 88,
[1232] = 89,
[1248] = 90,
[1264] = 91,
[1280] = 92,
[1296] = 93,
[1312] = 94,
[1328] = 95,
[840] = 96,
[856] = 97,
[872] = 98,
[888] = 99,
[904] = 100,
[920] = 101,
[936] = 102,
[952] = 103,
[968] = 104,
[984] = 105,
[1000] = 106,
[1016] = 107,
[1032] = 108,
[1048] = 109,
[1064] = 110,
[1080] = 111,
[1096] = 112,
[1112] = 113,
[1128] = 114,
[1144] = 115,
[1160] = 116,
[1176] = 117,
[1192] = 118,
[1208] = 119,
[1224] = 120,
[1240] = 121,
[1256] = 122,
[1272] = 123,
[1288] = 124,
[1304] = 125,
[1320] = 126,
[1336] = 127,
[512] = 128,
[520] = 129,
[552] = 130,
[528] = 131,
[560] = 132,
[536] = 133,
[568] = 134,
[544] = 135,
[576] = 136,
[616] = 137,
[16120] = 138,
[16112] = 139,
[16108] = 140,
[1360] = 141,
[1368] = 142,
[1952] = 143,
[1960] = 144,
};
constexpr tcg_global_set_t PinnedEnvGlbs(0);

#endif

}
#endif /* __cplusplus */

#define TARGET_NUM_REG_ARGS 8
