#pragma once
#ifdef __cplusplus
#include <bitset>
#include <array>
#include <cstdint>

/* NOTE: THIS FILE IS AUTO-GENERATED BY GEN-TCGCONSTANTS */
namespace jove {

//
// I64 _frame
// I64 env
// I32 r0
// I32 r1
// I32 r2
// I32 r3
// I32 r4
// I32 r5
// I32 r6
// I32 r7
// I32 r8
// I32 r9
// I32 r10
// I32 r11
// I32 r12
// I32 r13
// I32 r14
// I32 pc
// I32 CF
// I32 NF
// I32 VF
// I32 ZF
// I64 exclusive_addr
// I64 exclusive_val
// I64 pc
// I64 x0
// I64 x1
// I64 x2
// I64 x3
// I64 x4
// I64 x5
// I64 x6
// I64 x7
// I64 x8
// I64 x9
// I64 x10
// I64 x11
// I64 x12
// I64 x13
// I64 x14
// I64 x15
// I64 x16
// I64 x17
// I64 x18
// I64 x19
// I64 x20
// I64 x21
// I64 x22
// I64 x23
// I64 x24
// I64 x25
// I64 x26
// I64 x27
// I64 x28
// I64 x29
// I64 lr
// I64 sp
// I64 exclusive_high
//

typedef uint64_t tcg_uintptr_t;
constexpr int tcg_num_globals = 58;
constexpr int tcg_max_temps = 512;
constexpr int tcg_env_index = 1;
constexpr int tcg_program_counter_index = 24;
constexpr int tcg_frame_pointer_index = 54;
constexpr int tcg_stack_pointer_index = 56;
constexpr int tcg_program_counter_env_offset = -1;
constexpr int tcg_syscall_number_index = 33;
constexpr int tcg_syscall_return_index = 25;
constexpr int tcg_syscall_arg1_index = 25;
constexpr int tcg_syscall_arg2_index = 26;
constexpr int tcg_syscall_arg3_index = 27;
constexpr int tcg_syscall_arg4_index = 28;
constexpr int tcg_syscall_arg5_index = 29;
constexpr int tcg_syscall_arg6_index = 30;
constexpr int tcg_tpidr_el0_env_offset = 1304;
typedef std::bitset<tcg_num_globals> tcg_global_set_t;
constexpr tcg_global_set_t NotArgs(131074);
constexpr tcg_global_set_t NotRets(180143985111465986);
constexpr tcg_global_set_t CallConvArgs(8556380160);
typedef std::array<unsigned, 8> CallConvArgArrayTy;
static const CallConvArgArrayTy CallConvArgArray{25, 26, 27, 28, 29, 30, 31, 32};
constexpr tcg_global_set_t CallConvRets(100663296);
typedef std::array<unsigned, 2> CallConvRetArrayTy;
static const CallConvRetArrayTy CallConvRetArray{25, 26};
constexpr tcg_global_set_t CalleeSavedRegs(17996806323437568);
static const uint8_t tcg_global_by_offset_lookup_table[12257] = {
[0 ... 12256] = 0xff,
[0] = 2,
[4] = 3,
[8] = 4,
[12] = 5,
[16] = 6,
[20] = 7,
[24] = 8,
[28] = 9,
[32] = 10,
[36] = 11,
[40] = 12,
[44] = 13,
[48] = 14,
[52] = 15,
[56] = 16,
[60] = 17,
[528] = 18,
[536] = 19,
[532] = 20,
[540] = 21,
[12240] = 22,
[12248] = 23,
[320] = 24,
[64] = 25,
[72] = 26,
[80] = 27,
[88] = 28,
[96] = 29,
[104] = 30,
[112] = 31,
[120] = 32,
[128] = 33,
[136] = 34,
[144] = 35,
[152] = 36,
[160] = 37,
[168] = 38,
[176] = 39,
[184] = 40,
[192] = 41,
[200] = 42,
[208] = 43,
[216] = 44,
[224] = 45,
[232] = 46,
[240] = 47,
[248] = 48,
[256] = 49,
[264] = 50,
[272] = 51,
[280] = 52,
[288] = 53,
[296] = 54,
[304] = 55,
[312] = 56,
[12256] = 57,
};
constexpr tcg_global_set_t PinnedEnvGlbs(0);
}
#endif /* __cplusplus */

#define TARGET_NUM_REG_ARGS 8
