#pragma once
#ifdef __cplusplus
#include <bitset>
#include <array>
#include <cstdint>

/* NOTE: THIS FILE IS AUTO-GENERATED BY GEN-TCGCONSTANTS */
namespace jove {

#ifdef __x86_64__ /* cross-compiling */

//
// I64 _frame
// I64 env
// I32 at
// I32 v0
// I32 v1
// I32 a0
// I32 a1
// I32 a2
// I32 a3
// I32 t0
// I32 t1
// I32 t2
// I32 t3
// I32 t4
// I32 t5
// I32 t6
// I32 t7
// I32 s0
// I32 s1
// I32 s2
// I32 s3
// I32 s4
// I32 s5
// I32 s6
// I32 s7
// I32 t8
// I32 t9
// I32 k0
// I32 k1
// I32 gp
// I32 sp
// I32 s8
// I32 ra
// I64 f0
// I64 f1
// I64 f2
// I64 f3
// I64 f4
// I64 f5
// I64 f6
// I64 f7
// I64 f8
// I64 f9
// I64 f10
// I64 f11
// I64 f12
// I64 f13
// I64 f14
// I64 f15
// I64 f16
// I64 f17
// I64 f18
// I64 f19
// I64 f20
// I64 f21
// I64 f22
// I64 f23
// I64 f24
// I64 f25
// I64 f26
// I64 f27
// I64 f28
// I64 f29
// I64 f30
// I64 f31
// I64 w0.d1
// I64 w1.d1
// I64 w2.d1
// I64 w3.d1
// I64 w4.d1
// I64 w5.d1
// I64 w6.d1
// I64 w7.d1
// I64 w8.d1
// I64 w9.d1
// I64 w10.d1w11.d0w11.d1w12.d0w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w11.d1w12.d0w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w29.d1w30.d0w30.d1w31.d0w31.d1
// I64 w30.d1w31.d0w31.d1
// I64 w31.d1
// I32 PC
// I32 HI0
// I32 LO0
// I32 HI1
// I32 LO1
// I32 HI2
// I32 LO2
// I32 HI3
// I32 LO3
// I32 DSPControl
// I32 bcond
// I32 btarget
// I32 hflags
// I32 fcr0
// I32 fcr31
// I32 lladdr
// I32 llval
// I32 XR1
// I32 XR2
// I32 XR3
// I32 XR4
// I32 XR5
// I32 XR6
// I32 XR7
// I32 XR8
// I32 XR9
// I32 XR10XR11XR12XR13XR14XR15XCR
// I32 XR11XR12XR13XR14XR15XCR
// I32 XR12XR13XR14XR15XCR
// I32 XR13XR14XR15XCR
// I32 XR14XR15XCR
// I32 XR15XCR
// I32 XCR
//

typedef uint32_t tcg_uintptr_t;
constexpr int tcg_num_globals = 130;
constexpr int tcg_max_temps = 512;
constexpr int tcg_env_index = 1;
constexpr int tcg_program_counter_index = 97;
constexpr int tcg_frame_pointer_index = 31;
constexpr int tcg_stack_pointer_index = 30;
constexpr int tcg_program_counter_env_offset = 128;
constexpr int tcg_syscall_number_index = 3;
constexpr int tcg_syscall_return_index = 3;
constexpr int tcg_syscall_arg1_index = 5;
constexpr int tcg_syscall_arg2_index = 6;
constexpr int tcg_syscall_arg3_index = 7;
constexpr int tcg_syscall_arg4_index = 8;
constexpr int tcg_syscall_arg5_index = -1;
constexpr int tcg_syscall_arg6_index = -1;
constexpr int tcg_t9_index = 26;
constexpr int tcg_ra_index = 32;
constexpr int tcg_gp_index = 29;
constexpr int tcg_llval_index = 113;
constexpr int tcg_lladdr_index = 112;
constexpr int tcg_btarget_index = 108;
typedef std::bitset<194> tcg_global_set_t;
static const tcg_global_set_t NotArgs("00000000000000000000000000000000000000000000000000000000000000000000000000000000000001100000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011");
static const tcg_global_set_t NotRets("00000000000000000000000000000000000000000000000000000000000000000000000000000000000001100000000010000000000000000000000000000000000000000000000000000000000000000100100000000000000000000000000011");
constexpr tcg_global_set_t CallConvArgs(480);
typedef std::array<unsigned, 4> CallConvArgArrayTy;
static const CallConvArgArrayTy CallConvArgArray{5, 6, 7, 8};
constexpr tcg_global_set_t CallConvRets(24);
typedef std::array<unsigned, 2> CallConvRetArrayTy;
static const CallConvRetArrayTy CallConvRetArray{3, 4};
constexpr tcg_global_set_t CalleeSavedRegs(33423360);
static const uint8_t tcg_global_by_offset_lookup_table[6909] = {
[0 ... 6908] = 0xff,
[4] = 2,
[8] = 3,
[12] = 4,
[16] = 5,
[20] = 6,
[24] = 7,
[28] = 8,
[32] = 9,
[36] = 10,
[40] = 11,
[44] = 12,
[48] = 13,
[52] = 14,
[56] = 15,
[60] = 16,
[64] = 17,
[68] = 18,
[72] = 19,
[76] = 20,
[80] = 21,
[84] = 22,
[88] = 23,
[92] = 24,
[96] = 25,
[100] = 26,
[104] = 27,
[108] = 28,
[112] = 29,
[116] = 30,
[120] = 31,
[124] = 32,
[304] = 33,
[320] = 34,
[336] = 35,
[352] = 36,
[368] = 37,
[384] = 38,
[400] = 39,
[416] = 40,
[432] = 41,
[448] = 42,
[464] = 43,
[480] = 44,
[496] = 45,
[512] = 46,
[528] = 47,
[544] = 48,
[560] = 49,
[576] = 50,
[592] = 51,
[608] = 52,
[624] = 53,
[640] = 54,
[656] = 55,
[672] = 56,
[688] = 57,
[704] = 58,
[720] = 59,
[736] = 60,
[752] = 61,
[768] = 62,
[784] = 63,
[800] = 64,
[312] = 65,
[328] = 66,
[344] = 67,
[360] = 68,
[376] = 69,
[392] = 70,
[408] = 71,
[424] = 72,
[440] = 73,
[456] = 74,
[472] = 75,
[488] = 76,
[504] = 77,
[520] = 78,
[536] = 79,
[552] = 80,
[568] = 81,
[584] = 82,
[600] = 83,
[616] = 84,
[632] = 85,
[648] = 86,
[664] = 87,
[680] = 88,
[696] = 89,
[712] = 90,
[728] = 91,
[744] = 92,
[760] = 93,
[776] = 94,
[792] = 95,
[808] = 96,
[128] = 97,
[132] = 98,
[148] = 99,
[136] = 100,
[152] = 101,
[140] = 102,
[156] = 103,
[144] = 104,
[160] = 105,
[180] = 106,
[6908] = 107,
[6904] = 108,
[6900] = 109,
[832] = 110,
[840] = 111,
[1332] = 112,
[1336] = 113,
[236] = 114,
[240] = 115,
[244] = 116,
[248] = 117,
[252] = 118,
[256] = 119,
[260] = 120,
[264] = 121,
[268] = 122,
[272] = 123,
[276] = 124,
[280] = 125,
[284] = 126,
[288] = 127,
[292] = 128,
[296] = 129,
};
static const tcg_global_set_t PinnedEnvGlbs("00000000000000000000000000000000000000000000000000000000000000000000000000000000001110000000000000000000000000000000000111111111100000000000000000000000000000000000000000000000000000000000000000");

#else

//
// I32 _frame
// I32 env
// I32 at
// I32 v0
// I32 v1
// I32 a0
// I32 a1
// I32 a2
// I32 a3
// I32 t0
// I32 t1
// I32 t2
// I32 t3
// I32 t4
// I32 t5
// I32 t6
// I32 t7
// I32 s0
// I32 s1
// I32 s2
// I32 s3
// I32 s4
// I32 s5
// I32 s6
// I32 s7
// I32 t8
// I32 t9
// I32 k0
// I32 k1
// I32 gp
// I32 sp
// I32 s8
// I32 ra
// I32 f0_0
// I32 f0_1
// I32 f1_0
// I32 f1_1
// I32 f2_0
// I32 f2_1
// I32 f3_0
// I32 f3_1
// I32 f4_0
// I32 f4_1
// I32 f5_0
// I32 f5_1
// I32 f6_0
// I32 f6_1
// I32 f7_0
// I32 f7_1
// I32 f8_0
// I32 f8_1
// I32 f9_0
// I32 f9_1
// I32 f10_0
// I32 f10_1
// I32 f11_0
// I32 f11_1
// I32 f12_0
// I32 f12_1
// I32 f13_0
// I32 f13_1
// I32 f14_0
// I32 f14_1
// I32 f15_0
// I32 f15_1
// I32 f16_0
// I32 f16_1
// I32 f17_0
// I32 f17_1
// I32 f18_0
// I32 f18_1
// I32 f19_0
// I32 f19_1
// I32 f20_0
// I32 f20_1
// I32 f21_0
// I32 f21_1
// I32 f22_0
// I32 f22_1
// I32 f23_0
// I32 f23_1
// I32 f24_0
// I32 f24_1
// I32 f25_0
// I32 f25_1
// I32 f26_0
// I32 f26_1
// I32 f27_0
// I32 f27_1
// I32 f28_0
// I32 f28_1
// I32 f29_0
// I32 f29_1
// I32 f30_0
// I32 f30_1
// I32 f31_0
// I32 f31_1
// I32 w0.d1_0
// I32 w0.d1_1
// I32 w1.d1_0
// I32 w1.d1_1
// I32 w2.d1_0
// I32 w2.d1_1
// I32 w3.d1_0
// I32 w3.d1_1
// I32 w4.d1_0
// I32 w4.d1_1
// I32 w5.d1_0
// I32 w5.d1_1
// I32 w6.d1_0
// I32 w6.d1_1
// I32 w7.d1_0
// I32 w7.d1_1
// I32 w8.d1_0
// I32 w8.d1_1
// I32 w9.d1_0
// I32 w9.d1_1
// I32 w10.d1w11.d0w11.d1w12.d0w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15
// I32 w10.d1w11.d0w11.d1w12.d0w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15
// I32 w11.d1w12.d0w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16
// I32 w11.d1w12.d0w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16
// I32 w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17
// I32 w12.d1w13.d0w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17
// I32 w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18
// I32 w13.d1w14.d0w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18
// I32 w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19
// I32 w14.d1w15.d0w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19
// I32 w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20
// I32 w15.d1w16.d0w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20
// I32 w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21
// I32 w16.d1w17.d0w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21
// I32 w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22
// I32 w17.d1w18.d0w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22
// I32 w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23
// I32 w18.d1w19.d0w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23
// I32 w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24
// I32 w19.d1w20.d0w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24
// I32 w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25
// I32 w20.d1w21.d0w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25
// I32 w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26
// I32 w21.d1w22.d0w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26
// I32 w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27
// I32 w22.d1w23.d0w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27
// I32 w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28
// I32 w23.d1w24.d0w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28
// I32 w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29
// I32 w24.d1w25.d0w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29
// I32 w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30
// I32 w25.d1w26.d0w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30
// I32 w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31
// I32 w26.d1w27.d0w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31
// I32 w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1_0
// I32 w27.d1w28.d0w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1_1
// I32 w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1_0
// I32 w28.d1w29.d0w29.d1w30.d0w30.d1w31.d0w31.d1_1
// I32 w29.d1w30.d0w30.d1w31.d0w31.d1_0
// I32 w29.d1w30.d0w30.d1w31.d0w31.d1_1
// I32 w30.d1w31.d0w31.d1_0
// I32 w30.d1w31.d0w31.d1_1
// I32 w31.d1_0
// I32 w31.d1_1
// I32 PC
// I32 HI0
// I32 LO0
// I32 HI1
// I32 LO1
// I32 HI2
// I32 LO2
// I32 HI3
// I32 LO3
// I32 DSPControl
// I32 bcond
// I32 btarget
// I32 hflags
// I32 fcr0
// I32 fcr31
// I32 lladdr
// I32 llval
// I32 XR1
// I32 XR2
// I32 XR3
// I32 XR4
// I32 XR5
// I32 XR6
// I32 XR7
// I32 XR8
// I32 XR9
// I32 XR10XR11XR12XR13XR14XR15XCR
// I32 XR11XR12XR13XR14XR15XCR
// I32 XR12XR13XR14XR15XCR
// I32 XR13XR14XR15XCR
// I32 XR14XR15XCR
// I32 XR15XCR
// I32 XCR
//

typedef uint32_t tcg_uintptr_t;
constexpr int tcg_num_globals = 194;
constexpr int tcg_max_temps = 512;
constexpr int tcg_env_index = 1;
constexpr int tcg_program_counter_index = 161;
constexpr int tcg_frame_pointer_index = 31;
constexpr int tcg_stack_pointer_index = 30;
constexpr int tcg_program_counter_env_offset = 128;
constexpr int tcg_syscall_number_index = 3;
constexpr int tcg_syscall_return_index = 3;
constexpr int tcg_syscall_arg1_index = 5;
constexpr int tcg_syscall_arg2_index = 6;
constexpr int tcg_syscall_arg3_index = 7;
constexpr int tcg_syscall_arg4_index = 8;
constexpr int tcg_syscall_arg5_index = -1;
constexpr int tcg_syscall_arg6_index = -1;
constexpr int tcg_t9_index = 26;
constexpr int tcg_ra_index = 32;
constexpr int tcg_gp_index = 29;
constexpr int tcg_llval_index = 177;
constexpr int tcg_lladdr_index = 176;
constexpr int tcg_btarget_index = 172;
typedef std::bitset<tcg_num_globals> tcg_global_set_t;
static const tcg_global_set_t NotArgs("00000000000000000000011000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011");
static const tcg_global_set_t NotRets("00000000000000000000011000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100100000000000000000000000000011");
constexpr tcg_global_set_t CallConvArgs(480);
typedef std::array<unsigned, 4> CallConvArgArrayTy;
static const CallConvArgArrayTy CallConvArgArray{5, 6, 7, 8};
constexpr tcg_global_set_t CallConvRets(24);
typedef std::array<unsigned, 2> CallConvRetArrayTy;
static const CallConvRetArrayTy CallConvRetArray{3, 4};
constexpr tcg_global_set_t CalleeSavedRegs(33423360);
static const uint8_t tcg_global_by_offset_lookup_table[6909] = {
[0 ... 6908] = 0xff,
[4] = 2,
[8] = 3,
[12] = 4,
[16] = 5,
[20] = 6,
[24] = 7,
[28] = 8,
[32] = 9,
[36] = 10,
[40] = 11,
[44] = 12,
[48] = 13,
[52] = 14,
[56] = 15,
[60] = 16,
[64] = 17,
[68] = 18,
[72] = 19,
[76] = 20,
[80] = 21,
[84] = 22,
[88] = 23,
[92] = 24,
[96] = 25,
[100] = 26,
[104] = 27,
[108] = 28,
[112] = 29,
[116] = 30,
[120] = 31,
[124] = 32,
[304] = 33,
[308] = 34,
[320] = 35,
[324] = 36,
[336] = 37,
[340] = 38,
[352] = 39,
[356] = 40,
[368] = 41,
[372] = 42,
[384] = 43,
[388] = 44,
[400] = 45,
[404] = 46,
[416] = 47,
[420] = 48,
[432] = 49,
[436] = 50,
[448] = 51,
[452] = 52,
[464] = 53,
[468] = 54,
[480] = 55,
[484] = 56,
[496] = 57,
[500] = 58,
[512] = 59,
[516] = 60,
[528] = 61,
[532] = 62,
[544] = 63,
[548] = 64,
[560] = 65,
[564] = 66,
[576] = 67,
[580] = 68,
[592] = 69,
[596] = 70,
[608] = 71,
[612] = 72,
[624] = 73,
[628] = 74,
[640] = 75,
[644] = 76,
[656] = 77,
[660] = 78,
[672] = 79,
[676] = 80,
[688] = 81,
[692] = 82,
[704] = 83,
[708] = 84,
[720] = 85,
[724] = 86,
[736] = 87,
[740] = 88,
[752] = 89,
[756] = 90,
[768] = 91,
[772] = 92,
[784] = 93,
[788] = 94,
[800] = 95,
[804] = 96,
[312] = 97,
[316] = 98,
[328] = 99,
[332] = 100,
[344] = 101,
[348] = 102,
[360] = 103,
[364] = 104,
[376] = 105,
[380] = 106,
[392] = 107,
[396] = 108,
[408] = 109,
[412] = 110,
[424] = 111,
[428] = 112,
[440] = 113,
[444] = 114,
[456] = 115,
[460] = 116,
[472] = 117,
[476] = 118,
[488] = 119,
[492] = 120,
[504] = 121,
[508] = 122,
[520] = 123,
[524] = 124,
[536] = 125,
[540] = 126,
[552] = 127,
[556] = 128,
[568] = 129,
[572] = 130,
[584] = 131,
[588] = 132,
[600] = 133,
[604] = 134,
[616] = 135,
[620] = 136,
[632] = 137,
[636] = 138,
[648] = 139,
[652] = 140,
[664] = 141,
[668] = 142,
[680] = 143,
[684] = 144,
[696] = 145,
[700] = 146,
[712] = 147,
[716] = 148,
[728] = 149,
[732] = 150,
[744] = 151,
[748] = 152,
[760] = 153,
[764] = 154,
[776] = 155,
[780] = 156,
[792] = 157,
[796] = 158,
[808] = 159,
[812] = 160,
[128] = 161,
[132] = 162,
[148] = 163,
[136] = 164,
[152] = 165,
[140] = 166,
[156] = 167,
[144] = 168,
[160] = 169,
[180] = 170,
[6908] = 171,
[6904] = 172,
[6900] = 173,
[832] = 174,
[840] = 175,
[1332] = 176,
[1336] = 177,
[236] = 178,
[240] = 179,
[244] = 180,
[248] = 181,
[252] = 182,
[256] = 183,
[260] = 184,
[264] = 185,
[268] = 186,
[272] = 187,
[276] = 188,
[280] = 189,
[284] = 190,
[288] = 191,
[292] = 192,
[296] = 193,
};
static const tcg_global_set_t PinnedEnvGlbs("00000000000000000011100000000000011000000000000000000000000000000000000000000111111111111111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");

#endif

}
#endif /* __cplusplus */

#define TARGET_NUM_REG_ARGS 4
