#pragma once
#ifdef __cplusplus
#include <bitset>
#include <array>
#include <cstdint>

/* NOTE: THIS FILE IS AUTO-GENERATED BY GEN-TCGCONSTANTS */
namespace jove {

#ifdef __x86_64__ /* XXX cross-compiling */

//
// I64 _frame
// I64 env
// I32 cc_op
// I32 cc_dst
// I32 cc_src
// I32 cc_src2
// I32 eip
// I32 eax
// I32 ecx
// I32 edx
// I32 ebx
// I32 esp
// I32 ebp
// I32 esi
// I32 edi
// I32 es_base
// I32 cs_base
// I32 ss_base
// I32 ds_base
// I32 fs_base
// I32 gs_base
// I64 bnd0_lb
// I64 bnd0_ub
// I64 bnd1_lb
// I64 bnd1_ub
// I64 bnd2_lb
// I64 bnd2_ub
// I64 bnd3_lb
// I64 bnd3_ub
//

typedef uint32_t taddr_t;
constexpr int tcg_num_globals = 29;
constexpr int tcg_max_temps = 512;
constexpr int tcg_env_index = 1;
constexpr int tcg_program_counter_index = 6;
constexpr int tcg_frame_pointer_index = 12;
constexpr int tcg_stack_pointer_index = 11;
constexpr int tcg_program_counter_env_offset = 32;
constexpr int tcg_syscall_number_index = 7;
constexpr int tcg_syscall_return_index = 7;
constexpr int tcg_syscall_arg1_index = 10;
constexpr int tcg_syscall_arg2_index = 8;
constexpr int tcg_syscall_arg3_index = 9;
constexpr int tcg_syscall_arg4_index = 13;
constexpr int tcg_syscall_arg5_index = 14;
constexpr int tcg_syscall_arg6_index = 12;
constexpr int tcg_gs_base_index = 20;
typedef std::bitset<37> tcg_global_set_t;
constexpr tcg_global_set_t NotArgs(536838207);
constexpr tcg_global_set_t NotRets(536838207);
constexpr tcg_global_set_t CallConvArgs(896);
typedef std::array<unsigned, 3> CallConvArgArrayTy;
static const CallConvArgArrayTy CallConvArgArray{7, 9, 8};
constexpr tcg_global_set_t CallConvRets(640);
typedef std::array<unsigned, 2> CallConvRetArrayTy;
static const CallConvRetArrayTy CallConvRetArray{7, 9};
constexpr tcg_global_set_t CalleeSavedRegs(29696);
static const uint8_t tcg_global_by_offset_lookup_table[353] = {
[0 ... 352] = 0xff,
[52] = 2,
[40] = 3,
[44] = 4,
[48] = 5,
[32] = 6,
[0] = 7,
[4] = 8,
[8] = 9,
[12] = 10,
[16] = 11,
[20] = 12,
[24] = 13,
[28] = 14,
[72] = 15,
[88] = 16,
[104] = 17,
[120] = 18,
[136] = 19,
[152] = 20,
[296] = 21,
[304] = 22,
[312] = 23,
[320] = 24,
[328] = 25,
[336] = 26,
[344] = 27,
[352] = 28,
};
constexpr tcg_global_set_t PinnedEnvGlbs(0);

#else

//
// I32 _frame
// I32 env
// I32 cc_op
// I32 cc_dst
// I32 cc_src
// I32 cc_src2
// I32 eip
// I32 eax
// I32 ecx
// I32 edx
// I32 ebx
// I32 esp
// I32 ebp
// I32 esi
// I32 edi
// I32 es_base
// I32 cs_base
// I32 ss_base
// I32 ds_base
// I32 fs_base
// I32 gs_base
// I32 bnd0_lb_0
// I32 bnd0_lb_1
// I32 bnd0_ub_0
// I32 bnd0_ub_1
// I32 bnd1_lb_0
// I32 bnd1_lb_1
// I32 bnd1_ub_0
// I32 bnd1_ub_1
// I32 bnd2_lb_0
// I32 bnd2_lb_1
// I32 bnd2_ub_0
// I32 bnd2_ub_1
// I32 bnd3_lb_0
// I32 bnd3_lb_1
// I32 bnd3_ub_0
// I32 bnd3_ub_1
//

typedef uint32_t taddr_t;
constexpr int tcg_num_globals = 37;
constexpr int tcg_max_temps = 512;
constexpr int tcg_env_index = 1;
constexpr int tcg_program_counter_index = 6;
constexpr int tcg_frame_pointer_index = 12;
constexpr int tcg_stack_pointer_index = 11;
constexpr int tcg_program_counter_env_offset = 32;
constexpr int tcg_syscall_number_index = 7;
constexpr int tcg_syscall_return_index = 7;
constexpr int tcg_syscall_arg1_index = 10;
constexpr int tcg_syscall_arg2_index = 8;
constexpr int tcg_syscall_arg3_index = 9;
constexpr int tcg_syscall_arg4_index = 13;
constexpr int tcg_syscall_arg5_index = 14;
constexpr int tcg_syscall_arg6_index = 12;
constexpr int tcg_gs_base_index = 20;
typedef std::bitset<tcg_num_globals> tcg_global_set_t;
constexpr tcg_global_set_t NotArgs(137438920767);
constexpr tcg_global_set_t NotRets(137438920767);
constexpr tcg_global_set_t CallConvArgs(896);
typedef std::array<unsigned, 3> CallConvArgArrayTy;
static const CallConvArgArrayTy CallConvArgArray{7, 9, 8};
constexpr tcg_global_set_t CallConvRets(640);
typedef std::array<unsigned, 2> CallConvRetArrayTy;
static const CallConvRetArrayTy CallConvRetArray{7, 9};
constexpr tcg_global_set_t CalleeSavedRegs(29696);
static const uint8_t tcg_global_by_offset_lookup_table[349] = {
[0 ... 348] = 0xff,
[52] = 2,
[40] = 3,
[44] = 4,
[48] = 5,
[32] = 6,
[0] = 7,
[4] = 8,
[8] = 9,
[12] = 10,
[16] = 11,
[20] = 12,
[24] = 13,
[28] = 14,
[72] = 15,
[88] = 16,
[104] = 17,
[120] = 18,
[136] = 19,
[152] = 20,
[288] = 21,
[292] = 22,
[296] = 23,
[300] = 24,
[304] = 25,
[308] = 26,
[312] = 27,
[316] = 28,
[320] = 29,
[324] = 30,
[328] = 31,
[332] = 32,
[336] = 33,
[340] = 34,
[344] = 35,
[348] = 36,
};
constexpr tcg_global_set_t PinnedEnvGlbs(0);

#endif

}
#endif /* __cplusplus */

#define TARGET_NUM_REG_ARGS 3
