"""
This is a script to explore output generated by trace2addrs. Run by going
  File... -> Script File -> /path/to/jove/scripts/ida/66/jove_view_addrs.py

Hotkeys:
Ctrl+Shift+B - Previous block in trace
Ctrl+Shift+N - Next block in trace
Ctrl+Shift+V - Jump 1% behind current position in trace
Ctrl+Shift+M - Jump 1% ahead of current position in trace
Ctrl+Shift+= - Skip to next occurence of given address
Ctrl+Shift+] - Skip to given position in trace
"""

import subprocess
import idaapi
import idc
import sys

trace_filename = None
trace = []
pos = 0

def open_trace_file():
  global trace_filename
  global trace
  global pos

  trace_filename = idc.AskFile(0, "*.txt", "addresses")
  if not trace_filename:
    return

  #
  # reset global state
  #
  trace = []
  pos = 0
  print("opening trace file %s..." % trace_filename)
  with open(trace_filename) as f:
    for line in f:
      colon = line.find(":")
      if (colon > 0):
        addrstr = line[colon+1:]
      else:
        addrstr = line

      trace.append(int(addrstr, 16))

def next_trace_block():
  global trace_filename
  global trace
  global pos

  if len(trace) == 0 or not trace_filename:
    print("[jove] no trace file opened?")
    return

  pos = min(pos + 1, len(trace) - 1)

  Addr = trace[pos]
  print("Block @ 0x%x (%d / %d) in %s" % (Addr, pos + 1, len(trace), trace_filename))
  idc.Jump(Addr)

def prev_trace_block():
  global trace_filename
  global trace
  global pos

  if len(trace) == 0 or not trace_filename:
    print("[jove] no trace file opened?")
    return

  pos = max(pos - 1, 0)

  Addr = trace[pos]
  print("Block @ 0x%x (%d / %d) in %s" % (Addr, pos + 1, len(trace), trace_filename));
  idc.Jump(Addr)

def skip_ahead():
  global trace_filename
  global trace
  global pos

  if len(trace) == 0 or not trace_filename:
    print("[jove] no trace file opened?")
    return

  x = float(pos) / float(len(trace));
  x = min(x + 0.01, 1.0)
  pos = min(int(x * len(trace)), len(trace) - 1)

  Addr = trace[pos]
  print("Block @ 0x%x (%d / %d) in %s" % (Addr, pos + 1, len(trace), trace_filename));
  idc.Jump(Addr)

def skip_behind():
  global trace_filename
  global trace
  global pos

  if len(trace) == 0 or not trace_filename:
    print("[jove] no trace file opened?")
    return

  x = float(pos) / float(len(trace));
  x = max(x - 0.01, 0.0)
  pos = min(int(x * len(trace)), len(trace) - 1)

  Addr = trace[pos]
  print("Block 0x%x (%d / %d) in %s" % (Addr, pos + 1, len(trace), trace_filename))
  idc.Jump(Addr)

def skip_to_bb():
  global trace_filename
  global trace
  global pos

  if len(trace) == 0 or not trace_filename:
    print("[jove] no trace file opened?")
    return

  Addr = idc.AskAddr(0, "Skip to next occurence of specified address")
  if not Addr or Addr == idaapi.BADADDR:
    return

  saved_pos = pos
  assert(saved_pos >= 0 and saved_pos < len(trace))

  print("Searching for next occurence of address 0x%x in %s" % (Addr, trace_filename))

  while True:
    pos += 1
    if pos >= len(trace):
      print("No such block found in trace")
      pos = saved_pos # not found: undo change to pos
      return

    if trace[pos] == Addr:
      print("Found address 0x%x" % Addr)
      idc.Jump(Addr)
      return

def skip_to_pos():
  global trace_filename
  global trace
  global pos

  if len(trace) == 0 or not trace_filename:
    print("[jove] no trace file opened?")
    return

  Pos = idc.AskLong(0, "Skip to given position in trace")
  if not Pos or Pos < 0:
    return

  saved_pos = pos
  assert(saved_pos >= 0 and saved_pos < len(trace))

  pos = Pos
  if pos < 0 or pos >= len(trace):
    pos = saved_pos
    return

  Addr = trace[pos]
  print("Block 0x%x (%d / %d) in %s" % (Addr, pos + 1, len(trace), trace_filename))
  idc.Jump(Addr)

open_trace_file()
if len(trace) > 0:
  actions = [
    ("Jump to next block in trace",             "Ctrl+Shift+N", next_trace_block),
    ("Jump to previous block in trace",         "Ctrl+Shift+B", prev_trace_block),
    ("Skip ahead",                              "Ctrl+Shift+M", skip_ahead),
    ("Skip behind",                             "Ctrl+Shift+V", skip_behind),
    ("Skip to next occurence of given address", "Ctrl+Shift+=", skip_to_bb),
    ("Skip to position in trace",               "Ctrl+Shift+]", skip_to_pos),
  ]

  for label, shortcut, f in actions:
    print("%s - %s" % (label, shortcut))
    if idaapi.add_hotkey(shortcut, f) is None:
      print("WARNING failed to add hotkey")
